use crate::schema::*;
use harness::prelude::*;

#[derive(Clone, Copy)]
pub struct Eligibility {
    pub person_id: Str,
    pub member_id: Str,
    pub subscriber_id: Option<Str>,
    pub subscriber_relation: Option<Str>,
    pub enrollment_start_date: Date,
    pub enrollment_end_date: Date,
    pub payer: Str,
    pub payer_type: Str,
    pub plan: Str,
    pub first_name: Option<Str>,
    pub middle_name: Option<Str>,
    pub last_name: Option<Str>,
    pub name_suffix: Option<Str>,
    pub social_security_number: Option<Str>,
    pub address: Option<Str>,
    pub city: Option<Str>,
    pub state: Str,
    pub zip_code: Option<Str>,
    pub phone: Option<Str>,
    pub email: Option<Str>,
    pub ethnicity: Option<Str>,
    pub sex: Str,
    pub race: Str,
    pub birth_date: Date,
    pub death_date: Option<Date>,
    pub death_flag: i64,
    pub original_reason_entitlement_code: Str,
    pub dual_status_code: Option<Str>,
    pub medicare_status_code: Str,
    pub enrollment_status: Option<Str>,
    pub hospice_flag: i64,
    pub institutional_snp_flag: i64,
    pub medicaid_indicator: Option<i64>,
    pub long_term_institutional_flag: i64,
    pub part_d_raf_type: Option<Str>,
    pub low_income_subsidy_indicator: Option<i64>,
    pub metal_level: Option<Str>,
    pub csr_indicator: Option<i64>,
    pub enrollment_duration_months: Option<i64>,
    pub esrd_status: Option<i64>,
    pub transplant_duration_months: Option<i64>,
    pub group_id: Str,
    pub group_name: Str,
    pub x_temp_record_origin: Str,
    pub x_temp_person_id: Str,
    pub x_temp_first_name: Option<Str>,
    pub x_tuva_test_extension: Str,
    pub ext_tuva_test_extension: Str,
    pub x_first_name: Str,
    pub ext_first_name: Str,
    pub file_date: Date,
    pub file_name: Str,
    pub ingest_datetime: Ts,
    pub data_source: Str,
}

fn leak(s: String) -> Str {
    Box::leak(s.into_boxed_str())
}

pub fn eligibility(db: &'static Db) -> Vec<Eligibility> {
    let t = &db.eligibility;
    let mut out = Vec::new();
    t.id.drive(|_, id| {
        out.push(Eligibility {
                person_id: t.person_id.get(id).unwrap(),
                member_id: t.member_id.get(id).unwrap(),
                subscriber_id: t.subscriber_id.get(id),
                subscriber_relation: t.subscriber_relation.get(id),
                enrollment_start_date: t.enrollment_start_date.get(id).unwrap(),
                enrollment_end_date: t.enrollment_end_date.get(id).unwrap(),
                payer: t.payer.get(id).unwrap(),
                payer_type: t.payer_type.get(id).unwrap(),
                plan: t.plan.get(id).unwrap(),
                first_name: t.first_name.get(id),
                middle_name: t.middle_name.get(id),
                last_name: t.last_name.get(id),
                name_suffix: t.name_suffix.get(id),
                social_security_number: t.social_security_number.get(id),
                address: t.address.get(id),
                city: t.city.get(id),
                state: t.state.get(id).unwrap(),
                zip_code: t.zip_code.get(id),
                phone: t.phone.get(id),
                email: t.email.get(id),
                ethnicity: t.ethnicity.get(id),
                sex: t.sex.get(id).unwrap(),
                race: t.race.get(id).unwrap(),
                birth_date: t.birth_date.get(id).unwrap(),
                death_date: t.death_date.get(id),
                death_flag: t.death_flag.get(id).unwrap(),
                original_reason_entitlement_code: t.original_reason_entitlement_code.get(id).unwrap(),
                dual_status_code: t.dual_status_code.get(id),
                medicare_status_code: t.medicare_status_code.get(id).unwrap(),
                enrollment_status: t.enrollment_status.get(id),
                hospice_flag: t.hospice_flag.get(id).unwrap(),
                institutional_snp_flag: t.institutional_snp_flag.get(id).unwrap(),
                medicaid_indicator: t.medicaid_indicator.get(id),
                long_term_institutional_flag: t.long_term_institutional_flag.get(id).unwrap(),
                part_d_raf_type: t.part_d_raf_type.get(id),
                low_income_subsidy_indicator: t.low_income_subsidy_indicator.get(id),
                metal_level: t.metal_level.get(id),
                csr_indicator: t.csr_indicator.get(id),
                enrollment_duration_months: t.enrollment_duration_months.get(id),
                esrd_status: t.esrd_status.get(id),
                transplant_duration_months: t.transplant_duration_months.get(id),
                group_id: t.group_id.get(id).unwrap(),
                group_name: t.group_name.get(id).unwrap(),
                x_temp_record_origin: leak(format!("claims_{}", t.person_id.get(id).unwrap())),
                x_temp_person_id: t.person_id.get(id).unwrap(),
                x_temp_first_name: t.first_name.get(id),
                x_tuva_test_extension: "eligibility",
                ext_tuva_test_extension: "eligibility",
                x_first_name: "extension-first-name",
                ext_first_name: "extension-first-name",
                file_date: t.file_date.get(id).unwrap(),
                file_name: t.file_name.get(id).unwrap(),
                ingest_datetime: t.ingest_datetime.get(id).unwrap(),
                data_source: t.data_source.get(id).unwrap(),
        })
    });
    out
}

pub fn fmt(v: &Eligibility) -> String {
    row(vec![
        V::S(v.person_id),
        V::S(v.member_id),
        ostr(v.subscriber_id),
        ostr(v.subscriber_relation),
        V::D(v.enrollment_start_date),
        V::D(v.enrollment_end_date),
        V::S(v.payer),
        V::S(v.payer_type),
        V::S(v.plan),
        ostr(v.first_name),
        ostr(v.middle_name),
        ostr(v.last_name),
        ostr(v.name_suffix),
        ostr(v.social_security_number),
        ostr(v.address),
        ostr(v.city),
        V::S(v.state),
        ostr(v.zip_code),
        ostr(v.phone),
        ostr(v.email),
        ostr(v.ethnicity),
        V::S(v.sex),
        V::S(v.race),
        V::D(v.birth_date),
        odate(v.death_date),
        V::I(v.death_flag),
        V::S(v.original_reason_entitlement_code),
        ostr(v.dual_status_code),
        V::S(v.medicare_status_code),
        ostr(v.enrollment_status),
        V::I(v.hospice_flag),
        V::I(v.institutional_snp_flag),
        oint(v.medicaid_indicator),
        V::I(v.long_term_institutional_flag),
        ostr(v.part_d_raf_type),
        oint(v.low_income_subsidy_indicator),
        ostr(v.metal_level),
        oint(v.csr_indicator),
        oint(v.enrollment_duration_months),
        oint(v.esrd_status),
        oint(v.transplant_duration_months),
        V::S(v.group_id),
        V::S(v.group_name),
        V::S(v.x_temp_record_origin),
        V::S(v.x_temp_person_id),
        ostr(v.x_temp_first_name),
        V::S(v.x_tuva_test_extension),
        V::S(v.ext_tuva_test_extension),
        V::S(v.x_first_name),
        V::S(v.ext_first_name),
        V::D(v.file_date),
        V::S(v.file_name),
        V::T(v.ingest_datetime),
        V::S(v.data_source),
    ])
}

pub fn q(db: &'static Db) -> String {
    rows(eligibility(db).iter().map(fmt))
}
