use crate::concepts::normalized_input__stg_medical_claim::NormalizedInputStgMedicalClaim;
use crate::schema::Db;
use harness::prelude::*;

#[derive(Clone, Copy)]
pub struct IntNormalizedInputUndeterminedClaimType {
    pub claim_id: Str,
    pub claim_line_number: i64,
    pub claim_type: Str,
    pub person_id: Str,
    pub member_id: Str,
    pub payer: Str,
    pub plan: Str,
    pub claim_start_date: Date,
    pub claim_end_date: Date,
    pub claim_line_start_date: Option<Date>,
    pub claim_line_end_date: Option<Date>,
    pub admission_date: Option<Date>,
    pub discharge_date: Option<Date>,
    pub admit_source_code: Option<Str>,
    pub admit_source_description: Option<Str>,
    pub admit_type_code: Option<Str>,
    pub admit_type_description: Option<Str>,
    pub discharge_disposition_code: Option<Str>,
    pub discharge_disposition_description: Option<Str>,
    pub place_of_service_code: Option<Str>,
    pub place_of_service_description: Option<Str>,
    pub bill_type_code: Option<Str>,
    pub bill_type_description: Option<Str>,
    pub drg_code_type: Str,
    pub drg_code: Option<Str>,
    pub drg_description: Option<Str>,
    pub revenue_center_code: Option<Str>,
    pub revenue_center_description: Option<Str>,
    pub service_unit_quantity: Option<i64>,
    pub hcpcs_code: Option<Str>,
    pub hcpcs_modifier_1: Option<Str>,
    pub hcpcs_modifier_2: Option<Str>,
    pub hcpcs_modifier_3: Option<Str>,
    pub hcpcs_modifier_4: Option<Str>,
    pub hcpcs_modifier_5: Option<Str>,
    pub rendering_npi: Str,
    pub rendering_name: Option<Str>,
    pub billing_npi: Option<Str>,
    pub billing_name: Option<Str>,
    pub facility_npi: Option<Str>,
    pub facility_name: Option<Str>,
    pub paid_date: Option<Date>,
    pub paid_amount: Option<f64>,
    pub allowed_amount: Option<f64>,
    pub charge_amount: f64,
    pub coinsurance_amount: Option<f64>,
    pub copayment_amount: Option<f64>,
    pub deductible_amount: Option<f64>,
    pub total_cost_amount: Option<f64>,
    pub diagnosis_code_type: Option<Str>,
    pub diagnosis_code_1: Option<Str>,
    pub diagnosis_code_2: Option<Str>,
    pub diagnosis_code_3: Option<Str>,
    pub diagnosis_code_4: Option<Str>,
    pub diagnosis_code_5: Option<Str>,
    pub diagnosis_code_6: Option<Str>,
    pub diagnosis_code_7: Option<Str>,
    pub diagnosis_code_8: Option<Str>,
    pub diagnosis_code_9: Option<Str>,
    pub diagnosis_code_10: Option<Str>,
    pub diagnosis_code_11: Option<Str>,
    pub diagnosis_code_12: Option<Str>,
    pub diagnosis_code_13: Option<Str>,
    pub diagnosis_code_14: Option<Str>,
    pub diagnosis_code_15: Option<Str>,
    pub diagnosis_code_16: Option<Str>,
    pub diagnosis_code_17: Option<Str>,
    pub diagnosis_code_18: Option<Str>,
    pub diagnosis_code_19: Option<Str>,
    pub diagnosis_code_20: Option<Str>,
    pub diagnosis_code_21: Option<Str>,
    pub diagnosis_code_22: Option<Str>,
    pub diagnosis_code_23: Option<Str>,
    pub diagnosis_code_24: Option<Str>,
    pub diagnosis_code_25: Option<Str>,
    pub diagnosis_poa_1: Option<Str>,
    pub diagnosis_poa_2: Option<Str>,
    pub diagnosis_poa_3: Option<Str>,
    pub diagnosis_poa_4: Option<Str>,
    pub diagnosis_poa_5: Option<Str>,
    pub diagnosis_poa_6: Option<Str>,
    pub diagnosis_poa_7: Option<Str>,
    pub diagnosis_poa_8: Option<Str>,
    pub diagnosis_poa_9: Option<Str>,
    pub diagnosis_poa_10: Option<Str>,
    pub diagnosis_poa_11: Option<Str>,
    pub diagnosis_poa_12: Option<Str>,
    pub diagnosis_poa_13: Option<Str>,
    pub diagnosis_poa_14: Option<Str>,
    pub diagnosis_poa_15: Option<Str>,
    pub diagnosis_poa_16: Option<Str>,
    pub diagnosis_poa_17: Option<Str>,
    pub diagnosis_poa_18: Option<Str>,
    pub diagnosis_poa_19: Option<Str>,
    pub diagnosis_poa_20: Option<Str>,
    pub diagnosis_poa_21: Option<Str>,
    pub diagnosis_poa_22: Option<Str>,
    pub diagnosis_poa_23: Option<Str>,
    pub diagnosis_poa_24: Option<Str>,
    pub diagnosis_poa_25: Option<Str>,
    pub procedure_code_type: Option<Str>,
    pub procedure_code_1: Option<Str>,
    pub procedure_code_2: Option<Str>,
    pub procedure_code_3: Option<Str>,
    pub procedure_code_4: Option<Str>,
    pub procedure_code_5: Option<Str>,
    pub procedure_code_6: Option<Str>,
    pub procedure_code_7: Option<Str>,
    pub procedure_code_8: Option<Str>,
    pub procedure_code_9: Option<Str>,
    pub procedure_code_10: Option<Str>,
    pub procedure_code_11: Option<Str>,
    pub procedure_code_12: Option<Str>,
    pub procedure_code_13: Option<Str>,
    pub procedure_code_14: Option<Str>,
    pub procedure_code_15: Option<Str>,
    pub procedure_code_16: Option<Str>,
    pub procedure_code_17: Option<Str>,
    pub procedure_code_18: Option<Str>,
    pub procedure_code_19: Option<Str>,
    pub procedure_code_20: Option<Str>,
    pub procedure_code_21: Option<Str>,
    pub procedure_code_22: Option<Str>,
    pub procedure_code_23: Option<Str>,
    pub procedure_code_24: Option<Str>,
    pub procedure_code_25: Option<Str>,
    pub procedure_date_1: Option<Date>,
    pub procedure_date_2: Option<Date>,
    pub procedure_date_3: Option<Date>,
    pub procedure_date_4: Option<Date>,
    pub procedure_date_5: Option<Date>,
    pub procedure_date_6: Option<Date>,
    pub procedure_date_7: Option<Date>,
    pub procedure_date_8: Option<Date>,
    pub procedure_date_9: Option<Date>,
    pub procedure_date_10: Option<Date>,
    pub procedure_date_11: Option<Date>,
    pub procedure_date_12: Option<Date>,
    pub procedure_date_13: Option<Date>,
    pub procedure_date_14: Option<Date>,
    pub procedure_date_15: Option<Date>,
    pub procedure_date_16: Option<Date>,
    pub procedure_date_17: Option<Date>,
    pub procedure_date_18: Option<Date>,
    pub procedure_date_19: Option<Date>,
    pub procedure_date_20: Option<Date>,
    pub procedure_date_21: Option<Date>,
    pub procedure_date_22: Option<Date>,
    pub procedure_date_23: Option<Date>,
    pub procedure_date_24: Option<Date>,
    pub procedure_date_25: Option<Date>,
    pub data_source: Str,
    pub tuva_last_run: Ts,
}

type Stg = NormalizedInputStgMedicalClaim;

pub fn int_normalized_input_undetermined_claim_type(
    db: &'static Db,
    stg: &[Stg],
) -> Vec<IntNormalizedInputUndeterminedClaimType> {
    let med = rel(stg.to_vec());
    let asx: HashIdx<Str, _> = (&db.admit_source.admit_source_code).inv().collect();
    let atx: HashIdx<Str, _> = (&db.admit_type.admit_type_code).inv().collect();
    let ddx: HashIdx<Str, _> = (&db.discharge_disposition.discharge_disposition_code).inv().collect();
    let posx: HashIdx<Str, _> = (&db.place_of_service.place_of_service_code).inv().collect();
    let btx: HashIdx<Str, _> = (&db.bill_type.bill_type_code).inv().collect();
    let msx: HashIdx<Str, _> = (&db.ms_drg.ms_drg_code).inv().collect();
    let aprx: HashIdx<Str, _> = (&db.apr_drg.apr_drg_code).inv().collect();
    let rcx: HashIdx<Str, _> = (&db.revenue_center.revenue_center_code).inv().collect();
    let npx: HashIdx<Str, _> = (&db.provider.npi).inv().collect();
    let j = (&med)
        .filt(|m: Stg| m.claim_type == "undetermined")
        .and((&med).flat_map(|m: Stg| m.admit_source_code).select(&asx).select((&db.admit_source.admit_source_code).and(&db.admit_source.admit_source_description)).opt())
        .and((&med).flat_map(|m: Stg| m.admit_type_code).select(&atx).select((&db.admit_type.admit_type_code).and(&db.admit_type.admit_type_description)).opt())
        .and((&med).flat_map(|m: Stg| m.discharge_disposition_code).select(&ddx).select((&db.discharge_disposition.discharge_disposition_code).and(&db.discharge_disposition.discharge_disposition_description)).opt())
        .and((&med).flat_map(|m: Stg| m.place_of_service_code).select(&posx).select((&db.place_of_service.place_of_service_code).and(&db.place_of_service.place_of_service_description)).opt())
        .and((&med).flat_map(|m: Stg| m.bill_type_code).select(&btx).select((&db.bill_type.bill_type_code).and(&db.bill_type.bill_type_description)).opt())
        .and((&med).filt(|m: Stg| m.drg_code_type == "ms-drg").flat_map(|m: Stg| m.drg_code).select(&msx).select((&db.ms_drg.ms_drg_code).and(&db.ms_drg.ms_drg_description)).opt())
        .and((&med).filt(|m: Stg| m.drg_code_type == "apr-drg").flat_map(|m: Stg| m.drg_code).select(&aprx).select((&db.apr_drg.apr_drg_code).and(&db.apr_drg.apr_drg_description)).opt())
        .and((&med).flat_map(|m: Stg| m.revenue_center_code).select(&rcx).select((&db.revenue_center.revenue_center_code).and(&db.revenue_center.revenue_center_description)).opt())
        .and((&med).map(|m: Stg| m.rendering_npi).select(&npx).select(&db.provider.npi).opt())
        .and((&med).flat_map(|m: Stg| m.billing_npi).select(&npx).select(&db.provider.npi).opt())
        .and((&med).flat_map(|m: Stg| m.facility_npi).select(&npx).select(&db.provider.npi).opt());
    let run = ts(2026, 1, 1, 0, 0, 0);
    drain(&j)
        .into_iter()
        .map(|(_, (((((((((((m, asrc), atyp), dis), pos), tob), ms), apr), rev), rend), bill), fac))| {
            IntNormalizedInputUndeterminedClaimType {
                claim_id: m.claim_id,
                claim_line_number: m.claim_line_number,
                claim_type: m.claim_type,
                person_id: m.person_id,
                member_id: m.member_id,
                payer: m.payer,
                plan: m.plan,
                claim_start_date: m.claim_start_date,
                claim_end_date: m.claim_end_date,
                claim_line_start_date: m.claim_line_start_date,
                claim_line_end_date: m.claim_line_end_date,
                admission_date: m.admission_date,
                discharge_date: m.discharge_date,
                admit_source_code: asrc.map(|x| x.0),
                admit_source_description: asrc.map(|x| x.1),
                admit_type_code: atyp.map(|x| x.0),
                admit_type_description: atyp.map(|x| x.1),
                discharge_disposition_code: dis.map(|x| x.0),
                discharge_disposition_description: dis.map(|x| x.1),
                place_of_service_code: pos.map(|x| x.0),
                place_of_service_description: pos.map(|x| x.1),
                bill_type_code: tob.map(|x| x.0),
                bill_type_description: tob.map(|x| x.1),
                drg_code_type: m.drg_code_type,
                drg_code: ms.map(|x| x.0).or(apr.map(|x| x.0)),
                drg_description: ms.map(|x| x.1).or(apr.map(|x| x.1)),
                revenue_center_code: rev.map(|x| x.0),
                revenue_center_description: rev.map(|x| x.1),
                service_unit_quantity: m.service_unit_quantity,
                hcpcs_code: m.hcpcs_code,
                hcpcs_modifier_1: m.hcpcs_modifier_1,
                hcpcs_modifier_2: m.hcpcs_modifier_2,
                hcpcs_modifier_3: m.hcpcs_modifier_3,
                hcpcs_modifier_4: m.hcpcs_modifier_4,
                hcpcs_modifier_5: m.hcpcs_modifier_5,
                rendering_npi: m.rendering_npi,
                rendering_name: rend,
                billing_npi: m.billing_npi,
                billing_name: bill,
                facility_npi: m.facility_npi,
                facility_name: fac,
                paid_date: m.paid_date,
                paid_amount: m.paid_amount,
                allowed_amount: m.allowed_amount,
                charge_amount: m.charge_amount,
                coinsurance_amount: m.coinsurance_amount,
                copayment_amount: m.copayment_amount,
                deductible_amount: m.deductible_amount,
                total_cost_amount: m.total_cost_amount,
                diagnosis_code_type: m.diagnosis_code_type,
                diagnosis_code_1: m.diagnosis_code_1,
                diagnosis_code_2: m.diagnosis_code_2,
                diagnosis_code_3: m.diagnosis_code_3,
                diagnosis_code_4: m.diagnosis_code_4,
                diagnosis_code_5: m.diagnosis_code_5,
                diagnosis_code_6: m.diagnosis_code_6,
                diagnosis_code_7: m.diagnosis_code_7,
                diagnosis_code_8: m.diagnosis_code_8,
                diagnosis_code_9: m.diagnosis_code_9,
                diagnosis_code_10: m.diagnosis_code_10,
                diagnosis_code_11: m.diagnosis_code_11,
                diagnosis_code_12: m.diagnosis_code_12,
                diagnosis_code_13: m.diagnosis_code_13,
                diagnosis_code_14: m.diagnosis_code_14,
                diagnosis_code_15: m.diagnosis_code_15,
                diagnosis_code_16: m.diagnosis_code_16,
                diagnosis_code_17: m.diagnosis_code_17,
                diagnosis_code_18: m.diagnosis_code_18,
                diagnosis_code_19: m.diagnosis_code_19,
                diagnosis_code_20: m.diagnosis_code_20,
                diagnosis_code_21: m.diagnosis_code_21,
                diagnosis_code_22: m.diagnosis_code_22,
                diagnosis_code_23: m.diagnosis_code_23,
                diagnosis_code_24: m.diagnosis_code_24,
                diagnosis_code_25: m.diagnosis_code_25,
                diagnosis_poa_1: m.diagnosis_poa_1,
                diagnosis_poa_2: m.diagnosis_poa_2,
                diagnosis_poa_3: m.diagnosis_poa_3,
                diagnosis_poa_4: m.diagnosis_poa_4,
                diagnosis_poa_5: m.diagnosis_poa_5,
                diagnosis_poa_6: m.diagnosis_poa_6,
                diagnosis_poa_7: m.diagnosis_poa_7,
                diagnosis_poa_8: m.diagnosis_poa_8,
                diagnosis_poa_9: m.diagnosis_poa_9,
                diagnosis_poa_10: m.diagnosis_poa_10,
                diagnosis_poa_11: m.diagnosis_poa_11,
                diagnosis_poa_12: m.diagnosis_poa_12,
                diagnosis_poa_13: m.diagnosis_poa_13,
                diagnosis_poa_14: m.diagnosis_poa_14,
                diagnosis_poa_15: m.diagnosis_poa_15,
                diagnosis_poa_16: m.diagnosis_poa_16,
                diagnosis_poa_17: m.diagnosis_poa_17,
                diagnosis_poa_18: m.diagnosis_poa_18,
                diagnosis_poa_19: m.diagnosis_poa_19,
                diagnosis_poa_20: m.diagnosis_poa_20,
                diagnosis_poa_21: m.diagnosis_poa_21,
                diagnosis_poa_22: m.diagnosis_poa_22,
                diagnosis_poa_23: m.diagnosis_poa_23,
                diagnosis_poa_24: m.diagnosis_poa_24,
                diagnosis_poa_25: m.diagnosis_poa_25,
                procedure_code_type: m.procedure_code_type,
                procedure_code_1: m.procedure_code_1,
                procedure_code_2: m.procedure_code_2,
                procedure_code_3: m.procedure_code_3,
                procedure_code_4: m.procedure_code_4,
                procedure_code_5: m.procedure_code_5,
                procedure_code_6: m.procedure_code_6,
                procedure_code_7: m.procedure_code_7,
                procedure_code_8: m.procedure_code_8,
                procedure_code_9: m.procedure_code_9,
                procedure_code_10: m.procedure_code_10,
                procedure_code_11: m.procedure_code_11,
                procedure_code_12: m.procedure_code_12,
                procedure_code_13: m.procedure_code_13,
                procedure_code_14: m.procedure_code_14,
                procedure_code_15: m.procedure_code_15,
                procedure_code_16: m.procedure_code_16,
                procedure_code_17: m.procedure_code_17,
                procedure_code_18: m.procedure_code_18,
                procedure_code_19: m.procedure_code_19,
                procedure_code_20: m.procedure_code_20,
                procedure_code_21: m.procedure_code_21,
                procedure_code_22: m.procedure_code_22,
                procedure_code_23: m.procedure_code_23,
                procedure_code_24: m.procedure_code_24,
                procedure_code_25: m.procedure_code_25,
                procedure_date_1: m.procedure_date_1,
                procedure_date_2: m.procedure_date_2,
                procedure_date_3: m.procedure_date_3,
                procedure_date_4: m.procedure_date_4,
                procedure_date_5: m.procedure_date_5,
                procedure_date_6: m.procedure_date_6,
                procedure_date_7: m.procedure_date_7,
                procedure_date_8: m.procedure_date_8,
                procedure_date_9: m.procedure_date_9,
                procedure_date_10: m.procedure_date_10,
                procedure_date_11: m.procedure_date_11,
                procedure_date_12: m.procedure_date_12,
                procedure_date_13: m.procedure_date_13,
                procedure_date_14: m.procedure_date_14,
                procedure_date_15: m.procedure_date_15,
                procedure_date_16: m.procedure_date_16,
                procedure_date_17: m.procedure_date_17,
                procedure_date_18: m.procedure_date_18,
                procedure_date_19: m.procedure_date_19,
                procedure_date_20: m.procedure_date_20,
                procedure_date_21: m.procedure_date_21,
                procedure_date_22: m.procedure_date_22,
                procedure_date_23: m.procedure_date_23,
                procedure_date_24: m.procedure_date_24,
                procedure_date_25: m.procedure_date_25,
                data_source: m.data_source,
                tuva_last_run: run,
            }
        })
        .collect()
}

pub fn fmt(v: &IntNormalizedInputUndeterminedClaimType) -> String {
    row(vec![
        V::S(v.claim_id),
        V::I(v.claim_line_number),
        V::S(v.claim_type),
        V::S(v.person_id),
        V::S(v.member_id),
        V::S(v.payer),
        V::S(v.plan),
        V::D(v.claim_start_date),
        V::D(v.claim_end_date),
        odate(v.claim_line_start_date),
        odate(v.claim_line_end_date),
        odate(v.admission_date),
        odate(v.discharge_date),
        ostr(v.admit_source_code),
        ostr(v.admit_source_description),
        ostr(v.admit_type_code),
        ostr(v.admit_type_description),
        ostr(v.discharge_disposition_code),
        ostr(v.discharge_disposition_description),
        ostr(v.place_of_service_code),
        ostr(v.place_of_service_description),
        ostr(v.bill_type_code),
        ostr(v.bill_type_description),
        V::S(v.drg_code_type),
        ostr(v.drg_code),
        ostr(v.drg_description),
        ostr(v.revenue_center_code),
        ostr(v.revenue_center_description),
        oint(v.service_unit_quantity),
        ostr(v.hcpcs_code),
        ostr(v.hcpcs_modifier_1),
        ostr(v.hcpcs_modifier_2),
        ostr(v.hcpcs_modifier_3),
        ostr(v.hcpcs_modifier_4),
        ostr(v.hcpcs_modifier_5),
        V::S(v.rendering_npi),
        ostr(v.rendering_name),
        ostr(v.billing_npi),
        ostr(v.billing_name),
        ostr(v.facility_npi),
        ostr(v.facility_name),
        odate(v.paid_date),
        ofloat(v.paid_amount),
        ofloat(v.allowed_amount),
        V::F(v.charge_amount),
        ofloat(v.coinsurance_amount),
        ofloat(v.copayment_amount),
        ofloat(v.deductible_amount),
        ofloat(v.total_cost_amount),
        ostr(v.diagnosis_code_type),
        ostr(v.diagnosis_code_1),
        ostr(v.diagnosis_code_2),
        ostr(v.diagnosis_code_3),
        ostr(v.diagnosis_code_4),
        ostr(v.diagnosis_code_5),
        ostr(v.diagnosis_code_6),
        ostr(v.diagnosis_code_7),
        ostr(v.diagnosis_code_8),
        ostr(v.diagnosis_code_9),
        ostr(v.diagnosis_code_10),
        ostr(v.diagnosis_code_11),
        ostr(v.diagnosis_code_12),
        ostr(v.diagnosis_code_13),
        ostr(v.diagnosis_code_14),
        ostr(v.diagnosis_code_15),
        ostr(v.diagnosis_code_16),
        ostr(v.diagnosis_code_17),
        ostr(v.diagnosis_code_18),
        ostr(v.diagnosis_code_19),
        ostr(v.diagnosis_code_20),
        ostr(v.diagnosis_code_21),
        ostr(v.diagnosis_code_22),
        ostr(v.diagnosis_code_23),
        ostr(v.diagnosis_code_24),
        ostr(v.diagnosis_code_25),
        ostr(v.diagnosis_poa_1),
        ostr(v.diagnosis_poa_2),
        ostr(v.diagnosis_poa_3),
        ostr(v.diagnosis_poa_4),
        ostr(v.diagnosis_poa_5),
        ostr(v.diagnosis_poa_6),
        ostr(v.diagnosis_poa_7),
        ostr(v.diagnosis_poa_8),
        ostr(v.diagnosis_poa_9),
        ostr(v.diagnosis_poa_10),
        ostr(v.diagnosis_poa_11),
        ostr(v.diagnosis_poa_12),
        ostr(v.diagnosis_poa_13),
        ostr(v.diagnosis_poa_14),
        ostr(v.diagnosis_poa_15),
        ostr(v.diagnosis_poa_16),
        ostr(v.diagnosis_poa_17),
        ostr(v.diagnosis_poa_18),
        ostr(v.diagnosis_poa_19),
        ostr(v.diagnosis_poa_20),
        ostr(v.diagnosis_poa_21),
        ostr(v.diagnosis_poa_22),
        ostr(v.diagnosis_poa_23),
        ostr(v.diagnosis_poa_24),
        ostr(v.diagnosis_poa_25),
        ostr(v.procedure_code_type),
        ostr(v.procedure_code_1),
        ostr(v.procedure_code_2),
        ostr(v.procedure_code_3),
        ostr(v.procedure_code_4),
        ostr(v.procedure_code_5),
        ostr(v.procedure_code_6),
        ostr(v.procedure_code_7),
        ostr(v.procedure_code_8),
        ostr(v.procedure_code_9),
        ostr(v.procedure_code_10),
        ostr(v.procedure_code_11),
        ostr(v.procedure_code_12),
        ostr(v.procedure_code_13),
        ostr(v.procedure_code_14),
        ostr(v.procedure_code_15),
        ostr(v.procedure_code_16),
        ostr(v.procedure_code_17),
        ostr(v.procedure_code_18),
        ostr(v.procedure_code_19),
        ostr(v.procedure_code_20),
        ostr(v.procedure_code_21),
        ostr(v.procedure_code_22),
        ostr(v.procedure_code_23),
        ostr(v.procedure_code_24),
        ostr(v.procedure_code_25),
        odate(v.procedure_date_1),
        odate(v.procedure_date_2),
        odate(v.procedure_date_3),
        odate(v.procedure_date_4),
        odate(v.procedure_date_5),
        odate(v.procedure_date_6),
        odate(v.procedure_date_7),
        odate(v.procedure_date_8),
        odate(v.procedure_date_9),
        odate(v.procedure_date_10),
        odate(v.procedure_date_11),
        odate(v.procedure_date_12),
        odate(v.procedure_date_13),
        odate(v.procedure_date_14),
        odate(v.procedure_date_15),
        odate(v.procedure_date_16),
        odate(v.procedure_date_17),
        odate(v.procedure_date_18),
        odate(v.procedure_date_19),
        odate(v.procedure_date_20),
        odate(v.procedure_date_21),
        odate(v.procedure_date_22),
        odate(v.procedure_date_23),
        odate(v.procedure_date_24),
        odate(v.procedure_date_25),
        V::S(v.data_source),
        V::T(v.tuva_last_run),
    ])
}

pub fn q(db: &'static Db) -> String {
    let mc = crate::concepts::medical_claim::medical_claim(db);
    let il = crate::concepts::input_layer__medical_claim::input_layer__medical_claim(db, &mc);
    let stg = crate::concepts::normalized_input__stg_medical_claim::normalized_input__stg_medical_claim(db, &il);
    rows(int_normalized_input_undetermined_claim_type(db, &stg).iter().map(fmt))
}
