use crate::schema::*;
use harness::prelude::*;

#[derive(Clone, Copy)]
pub struct MedicalClaim {
    pub claim_id: Str,
    pub claim_line_number: i64,
    pub claim_type: Str,
    pub person_id: Str,
    pub member_id: Str,
    pub payer: Str,
    pub plan: Str,
    pub claim_start_date: Date,
    pub claim_end_date: Date,
    pub claim_line_start_date: Option<Date>,
    pub claim_line_end_date: Option<Date>,
    pub admission_date: Option<Date>,
    pub discharge_date: Option<Date>,
    pub admit_source_code: Option<Str>,
    pub admit_type_code: Option<Str>,
    pub discharge_disposition_code: Option<Str>,
    pub place_of_service_code: Option<Str>,
    pub bill_type_code: Option<Str>,
    pub drg_code_type: Str,
    pub drg_code: Option<Str>,
    pub revenue_center_code: Option<Str>,
    pub service_unit_quantity: Option<i64>,
    pub hcpcs_code: Option<Str>,
    pub hcpcs_modifier_1: Option<Str>,
    pub hcpcs_modifier_2: Option<Str>,
    pub hcpcs_modifier_3: Option<Str>,
    pub hcpcs_modifier_4: Option<Str>,
    pub hcpcs_modifier_5: Option<Str>,
    pub rendering_npi: Str,
    pub rendering_tin: Option<Str>,
    pub billing_npi: Option<Str>,
    pub billing_tin: Option<Str>,
    pub facility_npi: Option<Str>,
    pub paid_date: Option<Date>,
    pub paid_amount: Option<f64>,
    pub allowed_amount: Option<f64>,
    pub charge_amount: f64,
    pub coinsurance_amount: Option<f64>,
    pub copayment_amount: Option<f64>,
    pub deductible_amount: Option<f64>,
    pub total_cost_amount: Option<f64>,
    pub diagnosis_code_type: Option<Str>,
    pub diagnosis_code_1: Option<Str>,
    pub diagnosis_code_2: Option<Str>,
    pub diagnosis_code_3: Option<Str>,
    pub diagnosis_code_4: Option<Str>,
    pub diagnosis_code_5: Option<Str>,
    pub diagnosis_code_6: Option<Str>,
    pub diagnosis_code_7: Option<Str>,
    pub diagnosis_code_8: Option<Str>,
    pub diagnosis_code_9: Option<Str>,
    pub diagnosis_code_10: Option<Str>,
    pub diagnosis_code_11: Option<Str>,
    pub diagnosis_code_12: Option<Str>,
    pub diagnosis_code_13: Option<Str>,
    pub diagnosis_code_14: Option<Str>,
    pub diagnosis_code_15: Option<Str>,
    pub diagnosis_code_16: Option<Str>,
    pub diagnosis_code_17: Option<Str>,
    pub diagnosis_code_18: Option<Str>,
    pub diagnosis_code_19: Option<Str>,
    pub diagnosis_code_20: Option<Str>,
    pub diagnosis_code_21: Option<Str>,
    pub diagnosis_code_22: Option<Str>,
    pub diagnosis_code_23: Option<Str>,
    pub diagnosis_code_24: Option<Str>,
    pub diagnosis_code_25: Option<Str>,
    pub diagnosis_poa_1: Option<Str>,
    pub diagnosis_poa_2: Option<Str>,
    pub diagnosis_poa_3: Option<Str>,
    pub diagnosis_poa_4: Option<Str>,
    pub diagnosis_poa_5: Option<Str>,
    pub diagnosis_poa_6: Option<Str>,
    pub diagnosis_poa_7: Option<Str>,
    pub diagnosis_poa_8: Option<Str>,
    pub diagnosis_poa_9: Option<Str>,
    pub diagnosis_poa_10: Option<Str>,
    pub diagnosis_poa_11: Option<Str>,
    pub diagnosis_poa_12: Option<Str>,
    pub diagnosis_poa_13: Option<Str>,
    pub diagnosis_poa_14: Option<Str>,
    pub diagnosis_poa_15: Option<Str>,
    pub diagnosis_poa_16: Option<Str>,
    pub diagnosis_poa_17: Option<Str>,
    pub diagnosis_poa_18: Option<Str>,
    pub diagnosis_poa_19: Option<Str>,
    pub diagnosis_poa_20: Option<Str>,
    pub diagnosis_poa_21: Option<Str>,
    pub diagnosis_poa_22: Option<Str>,
    pub diagnosis_poa_23: Option<Str>,
    pub diagnosis_poa_24: Option<Str>,
    pub diagnosis_poa_25: Option<Str>,
    pub procedure_code_type: Option<Str>,
    pub procedure_code_1: Option<Str>,
    pub procedure_code_2: Option<Str>,
    pub procedure_code_3: Option<Str>,
    pub procedure_code_4: Option<Str>,
    pub procedure_code_5: Option<Str>,
    pub procedure_code_6: Option<Str>,
    pub procedure_code_7: Option<Str>,
    pub procedure_code_8: Option<Str>,
    pub procedure_code_9: Option<Str>,
    pub procedure_code_10: Option<Str>,
    pub procedure_code_11: Option<Str>,
    pub procedure_code_12: Option<Str>,
    pub procedure_code_13: Option<Str>,
    pub procedure_code_14: Option<Str>,
    pub procedure_code_15: Option<Str>,
    pub procedure_code_16: Option<Str>,
    pub procedure_code_17: Option<Str>,
    pub procedure_code_18: Option<Str>,
    pub procedure_code_19: Option<Str>,
    pub procedure_code_20: Option<Str>,
    pub procedure_code_21: Option<Str>,
    pub procedure_code_22: Option<Str>,
    pub procedure_code_23: Option<Str>,
    pub procedure_code_24: Option<Str>,
    pub procedure_code_25: Option<Str>,
    pub procedure_date_1: Option<Date>,
    pub procedure_date_2: Option<Date>,
    pub procedure_date_3: Option<Date>,
    pub procedure_date_4: Option<Date>,
    pub procedure_date_5: Option<Date>,
    pub procedure_date_6: Option<Date>,
    pub procedure_date_7: Option<Date>,
    pub procedure_date_8: Option<Date>,
    pub procedure_date_9: Option<Date>,
    pub procedure_date_10: Option<Date>,
    pub procedure_date_11: Option<Date>,
    pub procedure_date_12: Option<Date>,
    pub procedure_date_13: Option<Date>,
    pub procedure_date_14: Option<Date>,
    pub procedure_date_15: Option<Date>,
    pub procedure_date_16: Option<Date>,
    pub procedure_date_17: Option<Date>,
    pub procedure_date_18: Option<Date>,
    pub procedure_date_19: Option<Date>,
    pub procedure_date_20: Option<Date>,
    pub procedure_date_21: Option<Date>,
    pub procedure_date_22: Option<Date>,
    pub procedure_date_23: Option<Date>,
    pub procedure_date_24: Option<Date>,
    pub procedure_date_25: Option<Date>,
    pub in_network_flag: i64,
    pub x_temp_claim_id: Str,
    pub x_temp_payer: Str,
    pub x_tuva_test_extension: Str,
    pub ext_tuva_test_extension: Str,
    pub data_source: Str,
    pub file_date: Date,
    pub file_name: Str,
    pub ingest_datetime: Ts,
}

pub fn medical_claim(db: &'static Db) -> Vec<MedicalClaim> {
    let t = &db.medical_claim;
    let mut out = Vec::new();
    t.id.drive(|_, id| {
        out.push(MedicalClaim {
                claim_id: t.claim_id.get(id).unwrap(),
                claim_line_number: t.claim_line_number.get(id).unwrap(),
                claim_type: t.claim_type.get(id).unwrap(),
                person_id: t.person_id.get(id).unwrap(),
                member_id: t.member_id.get(id).unwrap(),
                payer: t.payer.get(id).unwrap(),
                plan: t.plan.get(id).unwrap(),
                claim_start_date: t.claim_start_date.get(id).unwrap(),
                claim_end_date: t.claim_end_date.get(id).unwrap(),
                claim_line_start_date: t.claim_line_start_date.get(id),
                claim_line_end_date: t.claim_line_end_date.get(id),
                admission_date: t.admission_date.get(id),
                discharge_date: t.discharge_date.get(id),
                admit_source_code: t.admit_source_code.get(id),
                admit_type_code: t.admit_type_code.get(id),
                discharge_disposition_code: t.discharge_disposition_code.get(id),
                place_of_service_code: t.place_of_service_code.get(id),
                bill_type_code: t.bill_type_code.get(id),
                drg_code_type: t.drg_code_type.get(id).unwrap(),
                drg_code: t.drg_code.get(id),
                revenue_center_code: t.revenue_center_code.get(id),
                service_unit_quantity: t.service_unit_quantity.get(id),
                hcpcs_code: t.hcpcs_code.get(id),
                hcpcs_modifier_1: t.hcpcs_modifier_1.get(id),
                hcpcs_modifier_2: t.hcpcs_modifier_2.get(id),
                hcpcs_modifier_3: t.hcpcs_modifier_3.get(id),
                hcpcs_modifier_4: t.hcpcs_modifier_4.get(id),
                hcpcs_modifier_5: t.hcpcs_modifier_5.get(id),
                rendering_npi: t.rendering_npi.get(id).unwrap(),
                rendering_tin: t.rendering_tin.get(id),
                billing_npi: t.billing_npi.get(id),
                billing_tin: t.billing_tin.get(id),
                facility_npi: t.facility_npi.get(id),
                paid_date: t.paid_date.get(id),
                paid_amount: t.paid_amount.get(id),
                allowed_amount: t.allowed_amount.get(id),
                charge_amount: t.charge_amount.get(id).unwrap(),
                coinsurance_amount: t.coinsurance_amount.get(id),
                copayment_amount: t.copayment_amount.get(id),
                deductible_amount: t.deductible_amount.get(id),
                total_cost_amount: t.total_cost_amount.get(id),
                diagnosis_code_type: t.diagnosis_code_type.get(id),
                diagnosis_code_1: t.diagnosis_code_1.get(id),
                diagnosis_code_2: t.diagnosis_code_2.get(id),
                diagnosis_code_3: t.diagnosis_code_3.get(id),
                diagnosis_code_4: t.diagnosis_code_4.get(id),
                diagnosis_code_5: t.diagnosis_code_5.get(id),
                diagnosis_code_6: t.diagnosis_code_6.get(id),
                diagnosis_code_7: t.diagnosis_code_7.get(id),
                diagnosis_code_8: t.diagnosis_code_8.get(id),
                diagnosis_code_9: t.diagnosis_code_9.get(id),
                diagnosis_code_10: t.diagnosis_code_10.get(id),
                diagnosis_code_11: t.diagnosis_code_11.get(id),
                diagnosis_code_12: t.diagnosis_code_12.get(id),
                diagnosis_code_13: t.diagnosis_code_13.get(id),
                diagnosis_code_14: t.diagnosis_code_14.get(id),
                diagnosis_code_15: t.diagnosis_code_15.get(id),
                diagnosis_code_16: t.diagnosis_code_16.get(id),
                diagnosis_code_17: t.diagnosis_code_17.get(id),
                diagnosis_code_18: t.diagnosis_code_18.get(id),
                diagnosis_code_19: t.diagnosis_code_19.get(id),
                diagnosis_code_20: t.diagnosis_code_20.get(id),
                diagnosis_code_21: t.diagnosis_code_21.get(id),
                diagnosis_code_22: t.diagnosis_code_22.get(id),
                diagnosis_code_23: t.diagnosis_code_23.get(id),
                diagnosis_code_24: t.diagnosis_code_24.get(id),
                diagnosis_code_25: t.diagnosis_code_25.get(id),
                diagnosis_poa_1: t.diagnosis_poa_1.get(id),
                diagnosis_poa_2: t.diagnosis_poa_2.get(id),
                diagnosis_poa_3: t.diagnosis_poa_3.get(id),
                diagnosis_poa_4: t.diagnosis_poa_4.get(id),
                diagnosis_poa_5: t.diagnosis_poa_5.get(id),
                diagnosis_poa_6: t.diagnosis_poa_6.get(id),
                diagnosis_poa_7: t.diagnosis_poa_7.get(id),
                diagnosis_poa_8: t.diagnosis_poa_8.get(id),
                diagnosis_poa_9: t.diagnosis_poa_9.get(id),
                diagnosis_poa_10: t.diagnosis_poa_10.get(id),
                diagnosis_poa_11: t.diagnosis_poa_11.get(id),
                diagnosis_poa_12: t.diagnosis_poa_12.get(id),
                diagnosis_poa_13: t.diagnosis_poa_13.get(id),
                diagnosis_poa_14: t.diagnosis_poa_14.get(id),
                diagnosis_poa_15: t.diagnosis_poa_15.get(id),
                diagnosis_poa_16: t.diagnosis_poa_16.get(id),
                diagnosis_poa_17: t.diagnosis_poa_17.get(id),
                diagnosis_poa_18: t.diagnosis_poa_18.get(id),
                diagnosis_poa_19: t.diagnosis_poa_19.get(id),
                diagnosis_poa_20: t.diagnosis_poa_20.get(id),
                diagnosis_poa_21: t.diagnosis_poa_21.get(id),
                diagnosis_poa_22: t.diagnosis_poa_22.get(id),
                diagnosis_poa_23: t.diagnosis_poa_23.get(id),
                diagnosis_poa_24: t.diagnosis_poa_24.get(id),
                diagnosis_poa_25: t.diagnosis_poa_25.get(id),
                procedure_code_type: t.procedure_code_type.get(id),
                procedure_code_1: t.procedure_code_1.get(id),
                procedure_code_2: t.procedure_code_2.get(id),
                procedure_code_3: t.procedure_code_3.get(id),
                procedure_code_4: t.procedure_code_4.get(id),
                procedure_code_5: t.procedure_code_5.get(id),
                procedure_code_6: t.procedure_code_6.get(id),
                procedure_code_7: t.procedure_code_7.get(id),
                procedure_code_8: t.procedure_code_8.get(id),
                procedure_code_9: t.procedure_code_9.get(id),
                procedure_code_10: t.procedure_code_10.get(id),
                procedure_code_11: t.procedure_code_11.get(id),
                procedure_code_12: t.procedure_code_12.get(id),
                procedure_code_13: t.procedure_code_13.get(id),
                procedure_code_14: t.procedure_code_14.get(id),
                procedure_code_15: t.procedure_code_15.get(id),
                procedure_code_16: t.procedure_code_16.get(id),
                procedure_code_17: t.procedure_code_17.get(id),
                procedure_code_18: t.procedure_code_18.get(id),
                procedure_code_19: t.procedure_code_19.get(id),
                procedure_code_20: t.procedure_code_20.get(id),
                procedure_code_21: t.procedure_code_21.get(id),
                procedure_code_22: t.procedure_code_22.get(id),
                procedure_code_23: t.procedure_code_23.get(id),
                procedure_code_24: t.procedure_code_24.get(id),
                procedure_code_25: t.procedure_code_25.get(id),
                procedure_date_1: t.procedure_date_1.get(id),
                procedure_date_2: t.procedure_date_2.get(id),
                procedure_date_3: t.procedure_date_3.get(id),
                procedure_date_4: t.procedure_date_4.get(id),
                procedure_date_5: t.procedure_date_5.get(id),
                procedure_date_6: t.procedure_date_6.get(id),
                procedure_date_7: t.procedure_date_7.get(id),
                procedure_date_8: t.procedure_date_8.get(id),
                procedure_date_9: t.procedure_date_9.get(id),
                procedure_date_10: t.procedure_date_10.get(id),
                procedure_date_11: t.procedure_date_11.get(id),
                procedure_date_12: t.procedure_date_12.get(id),
                procedure_date_13: t.procedure_date_13.get(id),
                procedure_date_14: t.procedure_date_14.get(id),
                procedure_date_15: t.procedure_date_15.get(id),
                procedure_date_16: t.procedure_date_16.get(id),
                procedure_date_17: t.procedure_date_17.get(id),
                procedure_date_18: t.procedure_date_18.get(id),
                procedure_date_19: t.procedure_date_19.get(id),
                procedure_date_20: t.procedure_date_20.get(id),
                procedure_date_21: t.procedure_date_21.get(id),
                procedure_date_22: t.procedure_date_22.get(id),
                procedure_date_23: t.procedure_date_23.get(id),
                procedure_date_24: t.procedure_date_24.get(id),
                procedure_date_25: t.procedure_date_25.get(id),
                in_network_flag: t.in_network_flag.get(id).unwrap(),
                x_temp_claim_id: t.claim_id.get(id).unwrap(),
                x_temp_payer: t.payer.get(id).unwrap(),
                x_tuva_test_extension: "medical_claim",
                ext_tuva_test_extension: "medical_claim",
                data_source: t.data_source.get(id).unwrap(),
                file_date: t.file_date.get(id).unwrap(),
                file_name: t.file_name.get(id).unwrap(),
                ingest_datetime: t.ingest_datetime.get(id).unwrap(),
        })
    });
    out
}

pub fn fmt(v: &MedicalClaim) -> String {
    row(vec![
        V::S(v.claim_id),
        V::I(v.claim_line_number),
        V::S(v.claim_type),
        V::S(v.person_id),
        V::S(v.member_id),
        V::S(v.payer),
        V::S(v.plan),
        V::D(v.claim_start_date),
        V::D(v.claim_end_date),
        odate(v.claim_line_start_date),
        odate(v.claim_line_end_date),
        odate(v.admission_date),
        odate(v.discharge_date),
        ostr(v.admit_source_code),
        ostr(v.admit_type_code),
        ostr(v.discharge_disposition_code),
        ostr(v.place_of_service_code),
        ostr(v.bill_type_code),
        V::S(v.drg_code_type),
        ostr(v.drg_code),
        ostr(v.revenue_center_code),
        oint(v.service_unit_quantity),
        ostr(v.hcpcs_code),
        ostr(v.hcpcs_modifier_1),
        ostr(v.hcpcs_modifier_2),
        ostr(v.hcpcs_modifier_3),
        ostr(v.hcpcs_modifier_4),
        ostr(v.hcpcs_modifier_5),
        V::S(v.rendering_npi),
        ostr(v.rendering_tin),
        ostr(v.billing_npi),
        ostr(v.billing_tin),
        ostr(v.facility_npi),
        odate(v.paid_date),
        ofloat(v.paid_amount),
        ofloat(v.allowed_amount),
        V::F(v.charge_amount),
        ofloat(v.coinsurance_amount),
        ofloat(v.copayment_amount),
        ofloat(v.deductible_amount),
        ofloat(v.total_cost_amount),
        ostr(v.diagnosis_code_type),
        ostr(v.diagnosis_code_1),
        ostr(v.diagnosis_code_2),
        ostr(v.diagnosis_code_3),
        ostr(v.diagnosis_code_4),
        ostr(v.diagnosis_code_5),
        ostr(v.diagnosis_code_6),
        ostr(v.diagnosis_code_7),
        ostr(v.diagnosis_code_8),
        ostr(v.diagnosis_code_9),
        ostr(v.diagnosis_code_10),
        ostr(v.diagnosis_code_11),
        ostr(v.diagnosis_code_12),
        ostr(v.diagnosis_code_13),
        ostr(v.diagnosis_code_14),
        ostr(v.diagnosis_code_15),
        ostr(v.diagnosis_code_16),
        ostr(v.diagnosis_code_17),
        ostr(v.diagnosis_code_18),
        ostr(v.diagnosis_code_19),
        ostr(v.diagnosis_code_20),
        ostr(v.diagnosis_code_21),
        ostr(v.diagnosis_code_22),
        ostr(v.diagnosis_code_23),
        ostr(v.diagnosis_code_24),
        ostr(v.diagnosis_code_25),
        ostr(v.diagnosis_poa_1),
        ostr(v.diagnosis_poa_2),
        ostr(v.diagnosis_poa_3),
        ostr(v.diagnosis_poa_4),
        ostr(v.diagnosis_poa_5),
        ostr(v.diagnosis_poa_6),
        ostr(v.diagnosis_poa_7),
        ostr(v.diagnosis_poa_8),
        ostr(v.diagnosis_poa_9),
        ostr(v.diagnosis_poa_10),
        ostr(v.diagnosis_poa_11),
        ostr(v.diagnosis_poa_12),
        ostr(v.diagnosis_poa_13),
        ostr(v.diagnosis_poa_14),
        ostr(v.diagnosis_poa_15),
        ostr(v.diagnosis_poa_16),
        ostr(v.diagnosis_poa_17),
        ostr(v.diagnosis_poa_18),
        ostr(v.diagnosis_poa_19),
        ostr(v.diagnosis_poa_20),
        ostr(v.diagnosis_poa_21),
        ostr(v.diagnosis_poa_22),
        ostr(v.diagnosis_poa_23),
        ostr(v.diagnosis_poa_24),
        ostr(v.diagnosis_poa_25),
        ostr(v.procedure_code_type),
        ostr(v.procedure_code_1),
        ostr(v.procedure_code_2),
        ostr(v.procedure_code_3),
        ostr(v.procedure_code_4),
        ostr(v.procedure_code_5),
        ostr(v.procedure_code_6),
        ostr(v.procedure_code_7),
        ostr(v.procedure_code_8),
        ostr(v.procedure_code_9),
        ostr(v.procedure_code_10),
        ostr(v.procedure_code_11),
        ostr(v.procedure_code_12),
        ostr(v.procedure_code_13),
        ostr(v.procedure_code_14),
        ostr(v.procedure_code_15),
        ostr(v.procedure_code_16),
        ostr(v.procedure_code_17),
        ostr(v.procedure_code_18),
        ostr(v.procedure_code_19),
        ostr(v.procedure_code_20),
        ostr(v.procedure_code_21),
        ostr(v.procedure_code_22),
        ostr(v.procedure_code_23),
        ostr(v.procedure_code_24),
        ostr(v.procedure_code_25),
        odate(v.procedure_date_1),
        odate(v.procedure_date_2),
        odate(v.procedure_date_3),
        odate(v.procedure_date_4),
        odate(v.procedure_date_5),
        odate(v.procedure_date_6),
        odate(v.procedure_date_7),
        odate(v.procedure_date_8),
        odate(v.procedure_date_9),
        odate(v.procedure_date_10),
        odate(v.procedure_date_11),
        odate(v.procedure_date_12),
        odate(v.procedure_date_13),
        odate(v.procedure_date_14),
        odate(v.procedure_date_15),
        odate(v.procedure_date_16),
        odate(v.procedure_date_17),
        odate(v.procedure_date_18),
        odate(v.procedure_date_19),
        odate(v.procedure_date_20),
        odate(v.procedure_date_21),
        odate(v.procedure_date_22),
        odate(v.procedure_date_23),
        odate(v.procedure_date_24),
        odate(v.procedure_date_25),
        V::I(v.in_network_flag),
        V::S(v.x_temp_claim_id),
        V::S(v.x_temp_payer),
        V::S(v.x_tuva_test_extension),
        V::S(v.ext_tuva_test_extension),
        V::S(v.data_source),
        V::D(v.file_date),
        V::S(v.file_name),
        V::T(v.ingest_datetime),
    ])
}

pub fn q(db: &'static Db) -> String {
    rows(medical_claim(db).iter().map(fmt))
}
