use crate::concepts::input_layer__medical_claim::InputLayerMedicalClaim;
use crate::schema::Db;
use harness::prelude::*;

#[derive(Clone, Copy)]
pub struct NormalizedInputStgMedicalClaim {
    pub claim_id: Str,
    pub claim_line_number: i64,
    pub claim_type: Str,
    pub person_id: Str,
    pub member_id: Str,
    pub payer: Str,
    pub plan: Str,
    pub claim_start_date: Date,
    pub claim_end_date: Date,
    pub claim_line_start_date: Option<Date>,
    pub claim_line_end_date: Option<Date>,
    pub admission_date: Option<Date>,
    pub discharge_date: Option<Date>,
    pub admit_source_code: Option<Str>,
    pub admit_type_code: Option<Str>,
    pub discharge_disposition_code: Option<Str>,
    pub place_of_service_code: Option<Str>,
    pub bill_type_code: Option<Str>,
    pub drg_code_type: Str,
    pub drg_code: Option<Str>,
    pub revenue_center_code: Option<Str>,
    pub service_unit_quantity: Option<i64>,
    pub hcpcs_code: Option<Str>,
    pub hcpcs_modifier_1: Option<Str>,
    pub hcpcs_modifier_2: Option<Str>,
    pub hcpcs_modifier_3: Option<Str>,
    pub hcpcs_modifier_4: Option<Str>,
    pub hcpcs_modifier_5: Option<Str>,
    pub rendering_npi: Str,
    pub rendering_tin: Option<Str>,
    pub billing_npi: Option<Str>,
    pub billing_tin: Option<Str>,
    pub facility_npi: Option<Str>,
    pub paid_date: Option<Date>,
    pub paid_amount: Option<f64>,
    pub allowed_amount: Option<f64>,
    pub charge_amount: f64,
    pub coinsurance_amount: Option<f64>,
    pub copayment_amount: Option<f64>,
    pub deductible_amount: Option<f64>,
    pub total_cost_amount: Option<f64>,
    pub diagnosis_code_type: Option<Str>,
    pub diagnosis_code_1: Option<Str>,
    pub diagnosis_code_2: Option<Str>,
    pub diagnosis_code_3: Option<Str>,
    pub diagnosis_code_4: Option<Str>,
    pub diagnosis_code_5: Option<Str>,
    pub diagnosis_code_6: Option<Str>,
    pub diagnosis_code_7: Option<Str>,
    pub diagnosis_code_8: Option<Str>,
    pub diagnosis_code_9: Option<Str>,
    pub diagnosis_code_10: Option<Str>,
    pub diagnosis_code_11: Option<Str>,
    pub diagnosis_code_12: Option<Str>,
    pub diagnosis_code_13: Option<Str>,
    pub diagnosis_code_14: Option<Str>,
    pub diagnosis_code_15: Option<Str>,
    pub diagnosis_code_16: Option<Str>,
    pub diagnosis_code_17: Option<Str>,
    pub diagnosis_code_18: Option<Str>,
    pub diagnosis_code_19: Option<Str>,
    pub diagnosis_code_20: Option<Str>,
    pub diagnosis_code_21: Option<Str>,
    pub diagnosis_code_22: Option<Str>,
    pub diagnosis_code_23: Option<Str>,
    pub diagnosis_code_24: Option<Str>,
    pub diagnosis_code_25: Option<Str>,
    pub diagnosis_poa_1: Option<Str>,
    pub diagnosis_poa_2: Option<Str>,
    pub diagnosis_poa_3: Option<Str>,
    pub diagnosis_poa_4: Option<Str>,
    pub diagnosis_poa_5: Option<Str>,
    pub diagnosis_poa_6: Option<Str>,
    pub diagnosis_poa_7: Option<Str>,
    pub diagnosis_poa_8: Option<Str>,
    pub diagnosis_poa_9: Option<Str>,
    pub diagnosis_poa_10: Option<Str>,
    pub diagnosis_poa_11: Option<Str>,
    pub diagnosis_poa_12: Option<Str>,
    pub diagnosis_poa_13: Option<Str>,
    pub diagnosis_poa_14: Option<Str>,
    pub diagnosis_poa_15: Option<Str>,
    pub diagnosis_poa_16: Option<Str>,
    pub diagnosis_poa_17: Option<Str>,
    pub diagnosis_poa_18: Option<Str>,
    pub diagnosis_poa_19: Option<Str>,
    pub diagnosis_poa_20: Option<Str>,
    pub diagnosis_poa_21: Option<Str>,
    pub diagnosis_poa_22: Option<Str>,
    pub diagnosis_poa_23: Option<Str>,
    pub diagnosis_poa_24: Option<Str>,
    pub diagnosis_poa_25: Option<Str>,
    pub procedure_code_type: Option<Str>,
    pub procedure_code_1: Option<Str>,
    pub procedure_code_2: Option<Str>,
    pub procedure_code_3: Option<Str>,
    pub procedure_code_4: Option<Str>,
    pub procedure_code_5: Option<Str>,
    pub procedure_code_6: Option<Str>,
    pub procedure_code_7: Option<Str>,
    pub procedure_code_8: Option<Str>,
    pub procedure_code_9: Option<Str>,
    pub procedure_code_10: Option<Str>,
    pub procedure_code_11: Option<Str>,
    pub procedure_code_12: Option<Str>,
    pub procedure_code_13: Option<Str>,
    pub procedure_code_14: Option<Str>,
    pub procedure_code_15: Option<Str>,
    pub procedure_code_16: Option<Str>,
    pub procedure_code_17: Option<Str>,
    pub procedure_code_18: Option<Str>,
    pub procedure_code_19: Option<Str>,
    pub procedure_code_20: Option<Str>,
    pub procedure_code_21: Option<Str>,
    pub procedure_code_22: Option<Str>,
    pub procedure_code_23: Option<Str>,
    pub procedure_code_24: Option<Str>,
    pub procedure_code_25: Option<Str>,
    pub procedure_date_1: Option<Date>,
    pub procedure_date_2: Option<Date>,
    pub procedure_date_3: Option<Date>,
    pub procedure_date_4: Option<Date>,
    pub procedure_date_5: Option<Date>,
    pub procedure_date_6: Option<Date>,
    pub procedure_date_7: Option<Date>,
    pub procedure_date_8: Option<Date>,
    pub procedure_date_9: Option<Date>,
    pub procedure_date_10: Option<Date>,
    pub procedure_date_11: Option<Date>,
    pub procedure_date_12: Option<Date>,
    pub procedure_date_13: Option<Date>,
    pub procedure_date_14: Option<Date>,
    pub procedure_date_15: Option<Date>,
    pub procedure_date_16: Option<Date>,
    pub procedure_date_17: Option<Date>,
    pub procedure_date_18: Option<Date>,
    pub procedure_date_19: Option<Date>,
    pub procedure_date_20: Option<Date>,
    pub procedure_date_21: Option<Date>,
    pub procedure_date_22: Option<Date>,
    pub procedure_date_23: Option<Date>,
    pub procedure_date_24: Option<Date>,
    pub procedure_date_25: Option<Date>,
    pub in_network_flag: i64,
    pub data_source: Str,
    pub file_name: Str,
    pub file_date: Date,
    pub ingest_datetime: Ts,
}

pub fn normalized_input__stg_medical_claim(_db: &'static Db, mc: &[InputLayerMedicalClaim]) -> Vec<NormalizedInputStgMedicalClaim> {
    mc.iter()
        .map(|m| NormalizedInputStgMedicalClaim {
            claim_id: m.claim_id,
            claim_line_number: m.claim_line_number,
            claim_type: m.claim_type,
            person_id: m.person_id,
            member_id: m.member_id,
            payer: m.payer,
            plan: m.plan,
            claim_start_date: m.claim_start_date,
            claim_end_date: m.claim_end_date,
            claim_line_start_date: m.claim_line_start_date,
            claim_line_end_date: m.claim_line_end_date,
            admission_date: m.admission_date,
            discharge_date: m.discharge_date,
            admit_source_code: m.admit_source_code,
            admit_type_code: m.admit_type_code,
            discharge_disposition_code: m.discharge_disposition_code,
            place_of_service_code: m.place_of_service_code,
            bill_type_code: m.bill_type_code,
            drg_code_type: m.drg_code_type,
            drg_code: m.drg_code,
            revenue_center_code: m.revenue_center_code,
            service_unit_quantity: m.service_unit_quantity,
            hcpcs_code: m.hcpcs_code,
            hcpcs_modifier_1: m.hcpcs_modifier_1,
            hcpcs_modifier_2: m.hcpcs_modifier_2,
            hcpcs_modifier_3: m.hcpcs_modifier_3,
            hcpcs_modifier_4: m.hcpcs_modifier_4,
            hcpcs_modifier_5: m.hcpcs_modifier_5,
            rendering_npi: m.rendering_npi,
            rendering_tin: m.rendering_tin,
            billing_npi: m.billing_npi,
            billing_tin: m.billing_tin,
            facility_npi: m.facility_npi,
            paid_date: m.paid_date,
            paid_amount: m.paid_amount,
            allowed_amount: m.allowed_amount,
            charge_amount: m.charge_amount,
            coinsurance_amount: m.coinsurance_amount,
            copayment_amount: m.copayment_amount,
            deductible_amount: m.deductible_amount,
            total_cost_amount: m.total_cost_amount,
            diagnosis_code_type: m.diagnosis_code_type,
            diagnosis_code_1: m.diagnosis_code_1,
            diagnosis_code_2: m.diagnosis_code_2,
            diagnosis_code_3: m.diagnosis_code_3,
            diagnosis_code_4: m.diagnosis_code_4,
            diagnosis_code_5: m.diagnosis_code_5,
            diagnosis_code_6: m.diagnosis_code_6,
            diagnosis_code_7: m.diagnosis_code_7,
            diagnosis_code_8: m.diagnosis_code_8,
            diagnosis_code_9: m.diagnosis_code_9,
            diagnosis_code_10: m.diagnosis_code_10,
            diagnosis_code_11: m.diagnosis_code_11,
            diagnosis_code_12: m.diagnosis_code_12,
            diagnosis_code_13: m.diagnosis_code_13,
            diagnosis_code_14: m.diagnosis_code_14,
            diagnosis_code_15: m.diagnosis_code_15,
            diagnosis_code_16: m.diagnosis_code_16,
            diagnosis_code_17: m.diagnosis_code_17,
            diagnosis_code_18: m.diagnosis_code_18,
            diagnosis_code_19: m.diagnosis_code_19,
            diagnosis_code_20: m.diagnosis_code_20,
            diagnosis_code_21: m.diagnosis_code_21,
            diagnosis_code_22: m.diagnosis_code_22,
            diagnosis_code_23: m.diagnosis_code_23,
            diagnosis_code_24: m.diagnosis_code_24,
            diagnosis_code_25: m.diagnosis_code_25,
            diagnosis_poa_1: m.diagnosis_poa_1,
            diagnosis_poa_2: m.diagnosis_poa_2,
            diagnosis_poa_3: m.diagnosis_poa_3,
            diagnosis_poa_4: m.diagnosis_poa_4,
            diagnosis_poa_5: m.diagnosis_poa_5,
            diagnosis_poa_6: m.diagnosis_poa_6,
            diagnosis_poa_7: m.diagnosis_poa_7,
            diagnosis_poa_8: m.diagnosis_poa_8,
            diagnosis_poa_9: m.diagnosis_poa_9,
            diagnosis_poa_10: m.diagnosis_poa_10,
            diagnosis_poa_11: m.diagnosis_poa_11,
            diagnosis_poa_12: m.diagnosis_poa_12,
            diagnosis_poa_13: m.diagnosis_poa_13,
            diagnosis_poa_14: m.diagnosis_poa_14,
            diagnosis_poa_15: m.diagnosis_poa_15,
            diagnosis_poa_16: m.diagnosis_poa_16,
            diagnosis_poa_17: m.diagnosis_poa_17,
            diagnosis_poa_18: m.diagnosis_poa_18,
            diagnosis_poa_19: m.diagnosis_poa_19,
            diagnosis_poa_20: m.diagnosis_poa_20,
            diagnosis_poa_21: m.diagnosis_poa_21,
            diagnosis_poa_22: m.diagnosis_poa_22,
            diagnosis_poa_23: m.diagnosis_poa_23,
            diagnosis_poa_24: m.diagnosis_poa_24,
            diagnosis_poa_25: m.diagnosis_poa_25,
            procedure_code_type: m.procedure_code_type,
            procedure_code_1: m.procedure_code_1,
            procedure_code_2: m.procedure_code_2,
            procedure_code_3: m.procedure_code_3,
            procedure_code_4: m.procedure_code_4,
            procedure_code_5: m.procedure_code_5,
            procedure_code_6: m.procedure_code_6,
            procedure_code_7: m.procedure_code_7,
            procedure_code_8: m.procedure_code_8,
            procedure_code_9: m.procedure_code_9,
            procedure_code_10: m.procedure_code_10,
            procedure_code_11: m.procedure_code_11,
            procedure_code_12: m.procedure_code_12,
            procedure_code_13: m.procedure_code_13,
            procedure_code_14: m.procedure_code_14,
            procedure_code_15: m.procedure_code_15,
            procedure_code_16: m.procedure_code_16,
            procedure_code_17: m.procedure_code_17,
            procedure_code_18: m.procedure_code_18,
            procedure_code_19: m.procedure_code_19,
            procedure_code_20: m.procedure_code_20,
            procedure_code_21: m.procedure_code_21,
            procedure_code_22: m.procedure_code_22,
            procedure_code_23: m.procedure_code_23,
            procedure_code_24: m.procedure_code_24,
            procedure_code_25: m.procedure_code_25,
            procedure_date_1: m.procedure_date_1,
            procedure_date_2: m.procedure_date_2,
            procedure_date_3: m.procedure_date_3,
            procedure_date_4: m.procedure_date_4,
            procedure_date_5: m.procedure_date_5,
            procedure_date_6: m.procedure_date_6,
            procedure_date_7: m.procedure_date_7,
            procedure_date_8: m.procedure_date_8,
            procedure_date_9: m.procedure_date_9,
            procedure_date_10: m.procedure_date_10,
            procedure_date_11: m.procedure_date_11,
            procedure_date_12: m.procedure_date_12,
            procedure_date_13: m.procedure_date_13,
            procedure_date_14: m.procedure_date_14,
            procedure_date_15: m.procedure_date_15,
            procedure_date_16: m.procedure_date_16,
            procedure_date_17: m.procedure_date_17,
            procedure_date_18: m.procedure_date_18,
            procedure_date_19: m.procedure_date_19,
            procedure_date_20: m.procedure_date_20,
            procedure_date_21: m.procedure_date_21,
            procedure_date_22: m.procedure_date_22,
            procedure_date_23: m.procedure_date_23,
            procedure_date_24: m.procedure_date_24,
            procedure_date_25: m.procedure_date_25,
            in_network_flag: m.in_network_flag,
            data_source: m.data_source,
            file_name: m.file_name,
            file_date: m.file_date,
            ingest_datetime: m.ingest_datetime,
        })
        .collect()
}

pub fn fmt(v: &NormalizedInputStgMedicalClaim) -> String {
    row(vec![
        V::S(v.claim_id),
        V::I(v.claim_line_number),
        V::S(v.claim_type),
        V::S(v.person_id),
        V::S(v.member_id),
        V::S(v.payer),
        V::S(v.plan),
        V::D(v.claim_start_date),
        V::D(v.claim_end_date),
        odate(v.claim_line_start_date),
        odate(v.claim_line_end_date),
        odate(v.admission_date),
        odate(v.discharge_date),
        ostr(v.admit_source_code),
        ostr(v.admit_type_code),
        ostr(v.discharge_disposition_code),
        ostr(v.place_of_service_code),
        ostr(v.bill_type_code),
        V::S(v.drg_code_type),
        ostr(v.drg_code),
        ostr(v.revenue_center_code),
        oint(v.service_unit_quantity),
        ostr(v.hcpcs_code),
        ostr(v.hcpcs_modifier_1),
        ostr(v.hcpcs_modifier_2),
        ostr(v.hcpcs_modifier_3),
        ostr(v.hcpcs_modifier_4),
        ostr(v.hcpcs_modifier_5),
        V::S(v.rendering_npi),
        ostr(v.rendering_tin),
        ostr(v.billing_npi),
        ostr(v.billing_tin),
        ostr(v.facility_npi),
        odate(v.paid_date),
        ofloat(v.paid_amount),
        ofloat(v.allowed_amount),
        V::F(v.charge_amount),
        ofloat(v.coinsurance_amount),
        ofloat(v.copayment_amount),
        ofloat(v.deductible_amount),
        ofloat(v.total_cost_amount),
        ostr(v.diagnosis_code_type),
        ostr(v.diagnosis_code_1),
        ostr(v.diagnosis_code_2),
        ostr(v.diagnosis_code_3),
        ostr(v.diagnosis_code_4),
        ostr(v.diagnosis_code_5),
        ostr(v.diagnosis_code_6),
        ostr(v.diagnosis_code_7),
        ostr(v.diagnosis_code_8),
        ostr(v.diagnosis_code_9),
        ostr(v.diagnosis_code_10),
        ostr(v.diagnosis_code_11),
        ostr(v.diagnosis_code_12),
        ostr(v.diagnosis_code_13),
        ostr(v.diagnosis_code_14),
        ostr(v.diagnosis_code_15),
        ostr(v.diagnosis_code_16),
        ostr(v.diagnosis_code_17),
        ostr(v.diagnosis_code_18),
        ostr(v.diagnosis_code_19),
        ostr(v.diagnosis_code_20),
        ostr(v.diagnosis_code_21),
        ostr(v.diagnosis_code_22),
        ostr(v.diagnosis_code_23),
        ostr(v.diagnosis_code_24),
        ostr(v.diagnosis_code_25),
        ostr(v.diagnosis_poa_1),
        ostr(v.diagnosis_poa_2),
        ostr(v.diagnosis_poa_3),
        ostr(v.diagnosis_poa_4),
        ostr(v.diagnosis_poa_5),
        ostr(v.diagnosis_poa_6),
        ostr(v.diagnosis_poa_7),
        ostr(v.diagnosis_poa_8),
        ostr(v.diagnosis_poa_9),
        ostr(v.diagnosis_poa_10),
        ostr(v.diagnosis_poa_11),
        ostr(v.diagnosis_poa_12),
        ostr(v.diagnosis_poa_13),
        ostr(v.diagnosis_poa_14),
        ostr(v.diagnosis_poa_15),
        ostr(v.diagnosis_poa_16),
        ostr(v.diagnosis_poa_17),
        ostr(v.diagnosis_poa_18),
        ostr(v.diagnosis_poa_19),
        ostr(v.diagnosis_poa_20),
        ostr(v.diagnosis_poa_21),
        ostr(v.diagnosis_poa_22),
        ostr(v.diagnosis_poa_23),
        ostr(v.diagnosis_poa_24),
        ostr(v.diagnosis_poa_25),
        ostr(v.procedure_code_type),
        ostr(v.procedure_code_1),
        ostr(v.procedure_code_2),
        ostr(v.procedure_code_3),
        ostr(v.procedure_code_4),
        ostr(v.procedure_code_5),
        ostr(v.procedure_code_6),
        ostr(v.procedure_code_7),
        ostr(v.procedure_code_8),
        ostr(v.procedure_code_9),
        ostr(v.procedure_code_10),
        ostr(v.procedure_code_11),
        ostr(v.procedure_code_12),
        ostr(v.procedure_code_13),
        ostr(v.procedure_code_14),
        ostr(v.procedure_code_15),
        ostr(v.procedure_code_16),
        ostr(v.procedure_code_17),
        ostr(v.procedure_code_18),
        ostr(v.procedure_code_19),
        ostr(v.procedure_code_20),
        ostr(v.procedure_code_21),
        ostr(v.procedure_code_22),
        ostr(v.procedure_code_23),
        ostr(v.procedure_code_24),
        ostr(v.procedure_code_25),
        odate(v.procedure_date_1),
        odate(v.procedure_date_2),
        odate(v.procedure_date_3),
        odate(v.procedure_date_4),
        odate(v.procedure_date_5),
        odate(v.procedure_date_6),
        odate(v.procedure_date_7),
        odate(v.procedure_date_8),
        odate(v.procedure_date_9),
        odate(v.procedure_date_10),
        odate(v.procedure_date_11),
        odate(v.procedure_date_12),
        odate(v.procedure_date_13),
        odate(v.procedure_date_14),
        odate(v.procedure_date_15),
        odate(v.procedure_date_16),
        odate(v.procedure_date_17),
        odate(v.procedure_date_18),
        odate(v.procedure_date_19),
        odate(v.procedure_date_20),
        odate(v.procedure_date_21),
        odate(v.procedure_date_22),
        odate(v.procedure_date_23),
        odate(v.procedure_date_24),
        odate(v.procedure_date_25),
        V::I(v.in_network_flag),
        V::S(v.data_source),
        V::S(v.file_name),
        V::D(v.file_date),
        V::T(v.ingest_datetime),
    ])
}

pub fn q(db: &'static Db) -> String {
    let mc = crate::concepts::medical_claim::medical_claim(db);
    let il = crate::concepts::input_layer__medical_claim::input_layer__medical_claim(db, &mc);
    rows(normalized_input__stg_medical_claim(db, &il).iter().map(fmt))
}
