cabal-version:      3.0
name:               prela
version:            0.1.0
synopsis:           Prela — Tarski algebra-of-relations query language, Haskell port
build-type:         Simple

library
    exposed-modules:  Prela
                    , Prela.Mode
                    , Prela.Storage
                    , Prela.Ops
                    , Prela.Predicate
                    , Prela.Stream
                    , Prela.Materialize
                    , Prela.Cache
                    , Prela.Schema
    hs-source-dirs:   src
    build-depends:    base >=4.14, containers, array, bytestring, regex-tdfa
                    , vector, mmap, template-haskell
    default-language: Haskell2010
    ghc-options:      -Wall

test-suite prela-test
    type:             exitcode-stdio-1.0
    main-is:          Spec.hs
    other-modules:    TinySchema
    hs-source-dirs:   test
    build-depends:    base >=4.14, prela, bytestring, directory, filepath
    default-language: Haskell2010
    ghc-options:      -Wall

executable prela-demo
    main-is:          Demo.hs
    hs-source-dirs:   app
    build-depends:    base >=4.14, prela, bytestring
    default-language: Haskell2010
    ghc-options:      -Wall
