// Reference example of the method-chain form. Kept as a registered query so
// `cargo asm` always has a known symbol to inspect.

use crate::engine::*;
use crate::job_schema::*;
use crate::queries::helpers::{min_row, Row};

pub const ENTRIES: &[super::Entry] = &[
    ("6a/method", "marvel-cinematic-universe || Iron Man 3 || Downey Jr., Robert", || min_row(q6a_methods())),
];

// q6a — movie : (year > 2010) ∧ (keyword == "marvel-...")
//             → (keyword == "marvel-...") × title
//             × (cast → person → name ~ "Downey…")
//
// Operator legend (engine.rs::QueryExt + the schema's generated nav traits;
// everything roots on IntoQuery, so paren-free leaf HANDLES — `keyword`,
// `movie`, `Entity::field` — mix freely with plan nodes):
//   .get(b)    composition (a set is an identity relation, so set∘Query is
//            the same Compose — no keyset projection)
//   .text()  / .person() / .name() … — navigation methods: per-field
//            compose, generated by `schema!` (`keyword.text()` ≡
//            `keyword.get(Keyword::text)`; `cast.person().name()`
//            walks Movie → Cast → Person → name)
//   .and(b)    product (×)
//   .and     ∧ — alias for the product; conjunct trees are consumed via
//            the flat short-circuit `member` (restriction = `.when`)
//   .or      ∨ — probe-only membership union (drive with `.union`)
//   .minus   value-bearing difference (key-based member test)
//   .when    restriction (Julia `:`) — keep rows whose value is a member
//   .eq / .ne / .gt / .lt / .ge / .le / .is_in / .rx / .nrx  predicates
pub fn q6a_methods() -> impl Drive<R: Row> {
    let kw_marvel = || keyword.text()
                              .eq("marvel-cinematic-universe");
    let q = movie
        .when(production_year.gt(2010)
         .and(kw_marvel()))
        .get(kw_marvel()
         .and(title)
         .and(cast.person().name().rx(r"Downey.*Robert")));
    q
}
