// Reference example of the method-chain form. Kept as a registered query so
// `cargo asm` always has a known symbol to inspect.

use crate::engine::*;
use crate::job_schema::*;
use crate::queries::helpers::min_row;

pub const ENTRIES: &[super::Entry] = &[
    ("6a/method", "marvel-cinematic-universe || Iron Man 3 || Downey Jr., Robert", q6a_methods),
];

// q6a — movie : (year > 2010) ∧ (keyword == "marvel-...")
//             → (keyword == "marvel-...") × title
//             × (cast → person → name ~ "Downey…")
//
// Operator legend (engine.rs::QueryExt + the schema's generated nav traits):
//   .o(b)    composition (a set is an identity relation, so set∘Query is
//            the same Compose — no keyset projection)
//   .text()  / .person() / .name() … — navigation methods: per-field
//            compose, generated by `schema!` (`keyword().text()` ≡
//            `keyword().o(Keyword::text())`; `cast().person().name()`
//            walks Movie → Cast → Person → name)
//   .x(b)    product (×)
//   .and     ∧ — alias for the product; conjunct trees are consumed via
//            the flat short-circuit `member` (restriction = `.in_s`)
//   .or      ∨ — probe-only membership union (drive with `.union`)
//   .minus   value-bearing difference (key-based member test)
//   .in_s    restriction (Julia `:`) — keep rows whose value is a member
//   .eq / .ne / .gt / .lt / .ge / .le / .is_in / .rx / .nrx  predicates
pub fn q6a_methods() -> String {
    let kw_marvel = || keyword().text()
                                .eq("marvel-cinematic-universe");
    let q = movie().in_s(
        production_year().gt(2010)
            .and(kw_marvel()),
    ).o(
        kw_marvel()
            .x(title())
            .x(cast().person().name().rx(r"Downey.*Robert")),
    );
    min_row(q)
}
