// Binary-cache loaders shared by the JOB (data.rs) and TPC-H (tpch_data.rs)
// datasets. The caches are produced by Julia's cache.jl (regenerated by
// `cargo run --bin regen`):
//
//   bits  — [u64 n][n × (i64,i64)]         ID×ID or ID×Int pairs
//   str   — [u64 n][n × i64 keys][(n+1) × u32 offsets][bytes]
//
// Strings are returned as &'static str — the mmap is leaked, so the bytes
// live for the program. No per-string allocation.

use memmap2::Mmap;
use std::fs::File;
use std::path::{Path, PathBuf};

fn cache_dir() -> PathBuf {
    PathBuf::from("../cache")
}

fn mmap_static(path: &Path) -> &'static [u8] {
    let f = File::open(path).unwrap_or_else(|e| panic!("open {path:?}: {e}"));
    let mmap = unsafe { Mmap::map(&f).unwrap() };
    let leaked: &'static Mmap = Box::leak(Box::new(mmap));
    &**leaked
}

pub fn load_bits(name: &str) -> Vec<(i64, i64)> {
    let bytes = mmap_static(&cache_dir().join(format!("{name}.bin")));
    let n = u64::from_le_bytes(bytes[..8].try_into().unwrap()) as usize;
    let ptr = unsafe { bytes.as_ptr().add(8) as *const [i64; 2] };
    let pairs = unsafe { std::slice::from_raw_parts(ptr, n) };
    pairs.iter().map(|p| (p[0], p[1])).collect()
}

pub fn load_strs(name: &str) -> Vec<(i64, &'static str)> {
    let bytes = mmap_static(&cache_dir().join(format!("{name}.bin")));
    let n = u64::from_le_bytes(bytes[..8].try_into().unwrap()) as usize;
    let keys_off = 8;
    let offsets_off = keys_off + n * 8;
    let bytes_off = offsets_off + (n + 1) * 4;
    let keys: &'static [i64] = unsafe {
        std::slice::from_raw_parts(bytes.as_ptr().add(keys_off) as *const i64, n)
    };
    let offsets: &'static [u32] = unsafe {
        std::slice::from_raw_parts(bytes.as_ptr().add(offsets_off) as *const u32, n + 1)
    };
    let data: &'static [u8] = &bytes[bytes_off..];
    (0..n).map(|i| {
        let lo = offsets[i] as usize;
        let hi = offsets[i + 1] as usize;
        let s: &'static str = unsafe { std::str::from_utf8_unchecked(&data[lo..hi]) };
        (keys[i], s)
    }).collect()
}

/// Max key (source id) across a loaded column — used to size entity universes.
pub fn max_key<V>(pairs: &[(i64, V)]) -> usize {
    pairs.iter().map(|&(k, _)| k).max().unwrap_or(0) as usize
}

/// Max value across a loaded ID×ID column — for universes referenced by value.
pub fn max_val(pairs: &[(i64, i64)]) -> usize {
    pairs.iter().map(|&(_, v)| v).max().unwrap_or(0) as usize
}
