// GENERATED by sqlstorm/tools/build_cache.py — do not edit by hand.
//
// The SQLStorm StackOverflow schema as prela entities. A column that is
// NULL anywhere in the data is a `Set` (CSR, zero-or-one entry per key):
// absence IS the null, so `.with(col)` is IS NOT NULL, `.minus(col)` is
// IS NULL, and `.select(col)` drops null rows by itself. Columns with no
// nulls stay dense `Col`s. Timestamps are epoch MICROSECONDS (see
// harness::time). `origid` is the original SQL `Id`.

#![allow(dead_code)]

use prela::engine::{Id, IntoQuery};
use prela::loader::{Col, Key, Loader, Set, Str};
use std::path::Path;

#[derive(IntoQuery)]
pub struct PostHistoryType {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub name: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct LinkType {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub name: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct PostType {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub name: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct CloseReasonType {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub name: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct VoteType {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub name: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct User {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub reputation: Col<Self, i64>,
    pub creation_date: Col<Self, i64>,
    pub display_name: Col<Self, Str>,
    pub last_access_date: Col<Self, i64>,
    pub website_url: Set<Self, Str>,
    pub location: Set<Self, Str>,
    pub about_me: Set<Self, Str>,
    pub views: Col<Self, i64>,
    pub up_votes: Col<Self, i64>,
    pub down_votes: Col<Self, i64>,
    pub profile_image_url: Set<Self, Str>,
    pub account_id: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct Badge {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub user: Col<Self, Id<User>>,
    pub user_id: Col<Self, i64>,
    pub name: Col<Self, Str>,
    pub date: Col<Self, i64>,
    pub class: Col<Self, i64>,
    pub tag_based: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct Post {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub post_type: Col<Self, Id<PostType>>,
    pub post_type_id: Col<Self, i64>,
    pub accepted_answer: Set<Self, Id<Post>>,
    pub accepted_answer_id: Set<Self, i64>,
    pub parent: Set<Self, Id<Post>>,
    pub parent_id: Set<Self, i64>,
    pub creation_date: Col<Self, i64>,
    pub score: Col<Self, i64>,
    pub view_count: Set<Self, i64>,
    pub body: Col<Self, Str>,
    pub owner_user: Set<Self, Id<User>>,
    pub owner_user_id: Set<Self, i64>,
    pub owner_display_name: Set<Self, Str>,
    pub last_editor_user: Set<Self, Id<User>>,
    pub last_editor_user_id: Set<Self, i64>,
    pub last_editor_display_name: Set<Self, Str>,
    pub last_edit_date: Set<Self, i64>,
    pub last_activity_date: Col<Self, i64>,
    pub title: Set<Self, Str>,
    pub tags_str: Set<Self, Str>,
    pub answer_count: Set<Self, i64>,
    pub comment_count: Col<Self, i64>,
    pub favorite_count: Set<Self, i64>,
    pub closed_date: Set<Self, i64>,
    pub community_owned_date: Set<Self, i64>,
    pub content_license: Col<Self, Str>,
    pub tags: Set<Self, Id<Tag>>,
}

#[derive(IntoQuery)]
pub struct Comment {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub post: Col<Self, Id<Post>>,
    pub post_id: Col<Self, i64>,
    pub score: Col<Self, i64>,
    pub text: Col<Self, Str>,
    pub creation_date: Col<Self, i64>,
    pub user_display_name: Set<Self, Str>,
    pub user: Set<Self, Id<User>>,
    pub user_id: Set<Self, i64>,
    pub content_license: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct PostHistory {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub post_history_type: Col<Self, Id<PostHistoryType>>,
    pub post_history_type_id: Col<Self, i64>,
    pub post: Col<Self, Id<Post>>,
    pub post_id: Col<Self, i64>,
    pub revision_guid: Col<Self, Str>,
    pub creation_date: Col<Self, i64>,
    pub user: Set<Self, Id<User>>,
    pub user_id: Set<Self, i64>,
    pub user_display_name: Set<Self, Str>,
    pub comment: Set<Self, Str>,
    pub text: Set<Self, Str>,
    pub content_license: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct PostLink {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub creation_date: Col<Self, i64>,
    pub post: Col<Self, Id<Post>>,
    pub post_id: Col<Self, i64>,
    pub related_post: Col<Self, Id<Post>>,
    pub related_post_id: Col<Self, i64>,
    pub link_type: Col<Self, Id<LinkType>>,
    pub link_type_id: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct Tag {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub tag_name: Col<Self, Str>,
    pub count: Col<Self, i64>,
    pub excerpt_post: Set<Self, Id<Post>>,
    pub excerpt_post_id: Set<Self, i64>,
    pub wiki_post: Set<Self, Id<Post>>,
    pub wiki_post_id: Set<Self, i64>,
    pub is_moderator_only: Set<Self, i64>,
    pub is_required: Set<Self, i64>,
}

#[derive(IntoQuery)]
pub struct Vote {
    #[primary_key]
    pub id: Key<Self>,
    pub origid: Col<Self, i64>,
    pub post: Set<Self, Id<Post>>,
    pub post_id: Col<Self, i64>,
    pub vote_type: Col<Self, Id<VoteType>>,
    pub vote_type_id: Col<Self, i64>,
    pub user: Set<Self, Id<User>>,
    pub user_id: Set<Self, i64>,
    pub creation_date: Col<Self, i64>,
    pub bounty_amount: Set<Self, i64>,
}

pub struct So {
    pub post_history_type: PostHistoryType,
    pub link_type: LinkType,
    pub post_type: PostType,
    pub close_reason_type: CloseReasonType,
    pub vote_type: VoteType,
    pub user: User,
    pub badge: Badge,
    pub post: Post,
    pub comment: Comment,
    pub post_history: PostHistory,
    pub post_link: PostLink,
    pub tag: Tag,
    pub vote: Vote,
}

fn build(l: &mut Loader) -> So {
    So {
        post_history_type: PostHistoryType {
            id: l.key("PostHistoryType_origid"),
            origid: l.i64s("PostHistoryType_origid"),
            name: l.strs("PostHistoryType_name"),
        },
        link_type: LinkType {
            id: l.key("LinkType_origid"),
            origid: l.i64s("LinkType_origid"),
            name: l.strs("LinkType_name"),
        },
        post_type: PostType {
            id: l.key("PostType_origid"),
            origid: l.i64s("PostType_origid"),
            name: l.strs("PostType_name"),
        },
        close_reason_type: CloseReasonType {
            id: l.key("CloseReasonType_origid"),
            origid: l.i64s("CloseReasonType_origid"),
            name: l.strs("CloseReasonType_name"),
        },
        vote_type: VoteType {
            id: l.key("VoteType_origid"),
            origid: l.i64s("VoteType_origid"),
            name: l.strs("VoteType_name"),
        },
        user: User {
            id: l.key("User_origid"),
            origid: l.i64s("User_origid"),
            reputation: l.i64s("User_reputation"),
            creation_date: l.i64s("User_creation_date"),
            display_name: l.strs("User_display_name"),
            last_access_date: l.i64s("User_last_access_date"),
            website_url: l.multi_strs("User_website_url"),
            location: l.multi_strs("User_location"),
            about_me: l.multi_strs("User_about_me"),
            views: l.i64s("User_views"),
            up_votes: l.i64s("User_up_votes"),
            down_votes: l.i64s("User_down_votes"),
            profile_image_url: l.multi_strs("User_profile_image_url"),
            account_id: l.i64s("User_account_id"),
        },
        badge: Badge {
            id: l.key("Badge_origid"),
            origid: l.i64s("Badge_origid"),
            user: l.ids("Badge_user"),
            user_id: l.i64s("Badge_user_id"),
            name: l.strs("Badge_name"),
            date: l.i64s("Badge_date"),
            class: l.i64s("Badge_class"),
            tag_based: l.i64s("Badge_tag_based"),
        },
        post: Post {
            id: l.key("Post_origid"),
            origid: l.i64s("Post_origid"),
            post_type: l.ids("Post_post_type"),
            post_type_id: l.i64s("Post_post_type_id"),
            accepted_answer: l.multi_ids("Post_accepted_answer"),
            accepted_answer_id: l.multi_i64("Post_accepted_answer_id"),
            parent: l.multi_ids("Post_parent"),
            parent_id: l.multi_i64("Post_parent_id"),
            creation_date: l.i64s("Post_creation_date"),
            score: l.i64s("Post_score"),
            view_count: l.multi_i64("Post_view_count"),
            body: l.strs("Post_body"),
            owner_user: l.multi_ids("Post_owner_user"),
            owner_user_id: l.multi_i64("Post_owner_user_id"),
            owner_display_name: l.multi_strs("Post_owner_display_name"),
            last_editor_user: l.multi_ids("Post_last_editor_user"),
            last_editor_user_id: l.multi_i64("Post_last_editor_user_id"),
            last_editor_display_name: l.multi_strs("Post_last_editor_display_name"),
            last_edit_date: l.multi_i64("Post_last_edit_date"),
            last_activity_date: l.i64s("Post_last_activity_date"),
            title: l.multi_strs("Post_title"),
            tags_str: l.multi_strs("Post_tags_str"),
            answer_count: l.multi_i64("Post_answer_count"),
            comment_count: l.i64s("Post_comment_count"),
            favorite_count: l.multi_i64("Post_favorite_count"),
            closed_date: l.multi_i64("Post_closed_date"),
            community_owned_date: l.multi_i64("Post_community_owned_date"),
            content_license: l.strs("Post_content_license"),
            tags: l.multi_ids("Post_tags"),
        },
        comment: Comment {
            id: l.key("Comment_origid"),
            origid: l.i64s("Comment_origid"),
            post: l.ids("Comment_post"),
            post_id: l.i64s("Comment_post_id"),
            score: l.i64s("Comment_score"),
            text: l.strs("Comment_text"),
            creation_date: l.i64s("Comment_creation_date"),
            user_display_name: l.multi_strs("Comment_user_display_name"),
            user: l.multi_ids("Comment_user"),
            user_id: l.multi_i64("Comment_user_id"),
            content_license: l.strs("Comment_content_license"),
        },
        post_history: PostHistory {
            id: l.key("PostHistory_origid"),
            origid: l.i64s("PostHistory_origid"),
            post_history_type: l.ids("PostHistory_post_history_type"),
            post_history_type_id: l.i64s("PostHistory_post_history_type_id"),
            post: l.ids("PostHistory_post"),
            post_id: l.i64s("PostHistory_post_id"),
            revision_guid: l.strs("PostHistory_revision_guid"),
            creation_date: l.i64s("PostHistory_creation_date"),
            user: l.multi_ids("PostHistory_user"),
            user_id: l.multi_i64("PostHistory_user_id"),
            user_display_name: l.multi_strs("PostHistory_user_display_name"),
            comment: l.multi_strs("PostHistory_comment"),
            text: l.multi_strs("PostHistory_text"),
            content_license: l.multi_strs("PostHistory_content_license"),
        },
        post_link: PostLink {
            id: l.key("PostLink_origid"),
            origid: l.i64s("PostLink_origid"),
            creation_date: l.i64s("PostLink_creation_date"),
            post: l.ids("PostLink_post"),
            post_id: l.i64s("PostLink_post_id"),
            related_post: l.ids("PostLink_related_post"),
            related_post_id: l.i64s("PostLink_related_post_id"),
            link_type: l.ids("PostLink_link_type"),
            link_type_id: l.i64s("PostLink_link_type_id"),
        },
        tag: Tag {
            id: l.key("Tag_origid"),
            origid: l.i64s("Tag_origid"),
            tag_name: l.strs("Tag_tag_name"),
            count: l.i64s("Tag_count"),
            excerpt_post: l.multi_ids("Tag_excerpt_post"),
            excerpt_post_id: l.multi_i64("Tag_excerpt_post_id"),
            wiki_post: l.multi_ids("Tag_wiki_post"),
            wiki_post_id: l.multi_i64("Tag_wiki_post_id"),
            is_moderator_only: l.multi_i64("Tag_is_moderator_only"),
            is_required: l.multi_i64("Tag_is_required"),
        },
        vote: Vote {
            id: l.key("Vote_origid"),
            origid: l.i64s("Vote_origid"),
            post: l.multi_ids("Vote_post"),
            post_id: l.i64s("Vote_post_id"),
            vote_type: l.ids("Vote_vote_type"),
            vote_type_id: l.i64s("Vote_vote_type_id"),
            user: l.multi_ids("Vote_user"),
            user_id: l.multi_i64("Vote_user_id"),
            creation_date: l.i64s("Vote_creation_date"),
            bounty_amount: l.multi_i64("Vote_bounty_amount"),
        },
    }
}

pub fn load(dir: &Path) -> So {
    build(&mut Loader::new(dir))
}

pub fn manifest() -> Vec<(String, u32)> {
    let mut l = Loader::probing();
    let _ = build(&mut l);
    l.manifest()
}
