#![allow(dead_code)]

use harness::time::{Date, Ts};
use prela::engine::{Id, IntoQuery};
use prela::loader::{Col, Key, Loader, Set, Str};
use std::path::Path;

#[derive(IntoQuery)]
pub struct IntCombinedProfessional {
    #[primary_key]
    pub id: Key<Self>,
    pub claim_id: Col<Self, Str>,
    pub claim_line_number: Col<Self, i64>,
    pub data_source: Col<Self, Str>,
    pub claim_line_id: Set<Self, Str>,
    pub service_category_1: Col<Self, Str>,
    pub service_category_2: Col<Self, Str>,
    pub service_category_3: Col<Self, Str>,
    pub tuva_last_run: Col<Self, Ts>,
    pub source_model_name: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct ServiceCategoryOfficeBasedRadiology {
    #[primary_key]
    pub id: Key<Self>,
    pub claim_id: Col<Self, Str>,
    pub claim_line_number: Col<Self, i64>,
    pub data_source: Col<Self, Str>,
    pub claim_line_id: Col<Self, Str>,
    pub service_category_1: Col<Self, Str>,
    pub service_category_2: Col<Self, Str>,
    pub service_category_3: Col<Self, Str>,
    pub source_model_name: Col<Self, Str>,
    pub tuva_last_run: Col<Self, Ts>,
}

#[derive(IntoQuery)]
pub struct ServiceCategoryStgOutpatientInstitutional {
    #[primary_key]
    pub id: Key<Self>,
    pub claim_id: Col<Self, Str>,
    pub data_source: Col<Self, Str>,
    pub service_type: Col<Self, Str>,
    pub tuva_last_run: Col<Self, Ts>,
}

#[derive(IntoQuery)]
pub struct ServiceCategoryStgProfessional {
    #[primary_key]
    pub id: Key<Self>,
    pub claim_id: Col<Self, Str>,
    pub claim_line_number: Col<Self, i64>,
    pub data_source: Col<Self, Str>,
    pub claim_line_id: Col<Self, Str>,
    pub service_type: Col<Self, Str>,
    pub tuva_last_run: Col<Self, Ts>,
}

#[derive(IntoQuery)]
pub struct ServiceCategoryGrouper {
    #[primary_key]
    pub id: Key<Self>,
    pub claim_id: Col<Self, Str>,
    pub claim_line_number: Col<Self, i64>,
    pub data_source: Col<Self, Str>,
    pub claim_type: Col<Self, Str>,
    pub service_category_1: Col<Self, Str>,
    pub service_category_2: Col<Self, Str>,
    pub service_category_3: Col<Self, Str>,
    pub original_service_cat_2: Set<Self, Str>,
    pub original_service_cat_3: Set<Self, Str>,
    pub duplicate_row_number: Col<Self, i64>,
    pub ccs_category: Set<Self, Str>,
    pub ccs_category_description: Set<Self, Str>,
    pub drg_code: Set<Self, Str>,
    pub drg_description: Set<Self, Str>,
    pub place_of_service_code: Set<Self, Str>,
    pub place_of_service_description: Set<Self, Str>,
    pub revenue_center_code: Set<Self, Str>,
    pub revenue_center_description: Set<Self, Str>,
    pub hcpcs_code: Set<Self, Str>,
    pub default_ccsr_category_ip: Set<Self, Str>,
    pub default_ccsr_category_op: Set<Self, Str>,
    pub default_ccsr_category_description_ip: Set<Self, Str>,
    pub default_ccsr_category_description_op: Set<Self, Str>,
    pub primary_taxonomy_code: Set<Self, Str>,
    pub primary_specialty_description: Set<Self, Str>,
    pub modality: Set<Self, Str>,
    pub bill_type_code: Set<Self, Str>,
    pub bill_type_description: Set<Self, Str>,
    pub source_model_name: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct IntClaimLevelDiagnosis {
    #[primary_key]
    pub id: Key<Self>,
    pub claim_id: Col<Self, Str>,
    pub data_source: Col<Self, Str>,
    pub diagnosis_code_type: Col<Self, Str>,
    pub diagnosis_code_1: Set<Self, Str>,
    pub diagnosis_code_2: Set<Self, Str>,
    pub diagnosis_code_3: Set<Self, Str>,
    pub diagnosis_code_4: Set<Self, Str>,
    pub diagnosis_code_5: Set<Self, Str>,
    pub diagnosis_code_6: Set<Self, Str>,
    pub diagnosis_code_7: Set<Self, Str>,
    pub diagnosis_code_8: Set<Self, Str>,
    pub diagnosis_code_9: Set<Self, Str>,
    pub diagnosis_code_10: Set<Self, Str>,
    pub diagnosis_code_11: Set<Self, Str>,
    pub diagnosis_code_12: Set<Self, Str>,
    pub diagnosis_code_13: Set<Self, Str>,
    pub diagnosis_code_14: Set<Self, Str>,
    pub diagnosis_code_15: Set<Self, Str>,
    pub diagnosis_code_16: Set<Self, Str>,
    pub diagnosis_code_17: Set<Self, Str>,
    pub diagnosis_code_18: Set<Self, Str>,
    pub diagnosis_code_19: Set<Self, Str>,
    pub diagnosis_code_20: Set<Self, Str>,
    pub diagnosis_code_21: Set<Self, Str>,
    pub diagnosis_code_22: Set<Self, Str>,
    pub diagnosis_code_23: Set<Self, Str>,
    pub diagnosis_code_24: Set<Self, Str>,
    pub diagnosis_code_25: Set<Self, Str>,
    pub tuva_last_run: Col<Self, Ts>,
}

#[derive(IntoQuery)]
pub struct MedicareProviderAndSupplierTaxonomyCrosswalk {
    #[primary_key]
    pub id: Key<Self>,
    pub medicare_specialty_code: Col<Self, Str>,
    pub medicare_provider_supplier_type_description: Col<Self, Str>,
    pub provider_taxonomy_code: Set<Self, Str>,
    pub provider_taxonomy_description: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct Provider {
    #[primary_key]
    pub id: Key<Self>,
    pub npi: Col<Self, Str>,
    pub entity_type_code: Set<Self, Str>,
    pub entity_type_description: Set<Self, Str>,
    pub primary_taxonomy_code: Set<Self, Str>,
    pub primary_specialty_description: Set<Self, Str>,
    pub provider_first_name: Set<Self, Str>,
    pub provider_last_name: Set<Self, Str>,
    pub provider_credential: Set<Self, Str>,
    pub provider_organization_name: Set<Self, Str>,
    pub provider_other_organization_name: Set<Self, Str>,
    pub provider_other_organization_name_type_code: Set<Self, Str>,
    pub provider_other_organization_name_type_description: Set<Self, Str>,
    pub parent_organization_name: Set<Self, Str>,
    pub practice_address_line_1: Set<Self, Str>,
    pub practice_address_line_2: Set<Self, Str>,
    pub practice_city: Set<Self, Str>,
    pub practice_state: Set<Self, Str>,
    pub practice_zip_code: Set<Self, Str>,
    pub mailing_telephone_number: Set<Self, Str>,
    pub location_telephone_number: Set<Self, Str>,
    pub official_telephone_number: Set<Self, Str>,
    pub last_updated: Set<Self, Date>,
    pub deactivation_date: Set<Self, Date>,
    pub deactivation_flag: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct Eligibility {
    #[primary_key]
    pub id: Key<Self>,
    pub person_id: Col<Self, Str>,
    pub member_id: Col<Self, Str>,
    pub subscriber_id: Set<Self, Str>,
    pub sex: Col<Self, Str>,
    pub race: Col<Self, Str>,
    pub birth_date: Col<Self, Date>,
    pub death_date: Set<Self, Date>,
    pub death_flag: Col<Self, i64>,
    pub enrollment_start_date: Col<Self, Date>,
    pub enrollment_end_date: Col<Self, Date>,
    pub payer: Col<Self, Str>,
    pub payer_type: Col<Self, Str>,
    pub plan: Col<Self, Str>,
    pub original_reason_entitlement_code: Col<Self, Str>,
    pub dual_status_code: Set<Self, Str>,
    pub medicare_status_code: Col<Self, Str>,
    pub group_id: Col<Self, Str>,
    pub group_name: Col<Self, Str>,
    pub name_suffix: Set<Self, Str>,
    pub first_name: Set<Self, Str>,
    pub middle_name: Set<Self, Str>,
    pub last_name: Set<Self, Str>,
    pub social_security_number: Set<Self, Str>,
    pub subscriber_relation: Set<Self, Str>,
    pub address: Set<Self, Str>,
    pub city: Set<Self, Str>,
    pub state: Col<Self, Str>,
    pub zip_code: Set<Self, Str>,
    pub phone: Set<Self, Str>,
    pub email: Set<Self, Str>,
    pub ethnicity: Set<Self, Str>,
    pub data_source: Col<Self, Str>,
    pub file_name: Col<Self, Str>,
    pub file_date: Col<Self, Date>,
    pub ingest_datetime: Col<Self, Ts>,
    pub enrollment_status: Set<Self, Str>,
    pub hospice_flag: Col<Self, i64>,
    pub institutional_snp_flag: Col<Self, i64>,
    pub medicaid_indicator: Set<Self, i64>,
    pub long_term_institutional_flag: Col<Self, i64>,
    pub part_d_raf_type: Set<Self, Str>,
    pub low_income_subsidy_indicator: Set<Self, i64>,
    pub metal_level: Set<Self, Str>,
    pub csr_indicator: Set<Self, i64>,
    pub enrollment_duration_months: Set<Self, i64>,
    pub esrd_status: Set<Self, i64>,
    pub transplant_duration_months: Set<Self, i64>,
}

#[derive(IntoQuery)]
pub struct MedicalClaim {
    #[primary_key]
    pub id: Key<Self>,
    pub claim_id: Col<Self, Str>,
    pub claim_line_number: Col<Self, i64>,
    pub claim_type: Col<Self, Str>,
    pub person_id: Col<Self, Str>,
    pub member_id: Col<Self, Str>,
    pub payer: Col<Self, Str>,
    pub plan: Col<Self, Str>,
    pub claim_start_date: Col<Self, Date>,
    pub claim_end_date: Col<Self, Date>,
    pub claim_line_start_date: Set<Self, Date>,
    pub claim_line_end_date: Set<Self, Date>,
    pub admission_date: Set<Self, Date>,
    pub discharge_date: Set<Self, Date>,
    pub admit_source_code: Set<Self, Str>,
    pub admit_type_code: Set<Self, Str>,
    pub discharge_disposition_code: Set<Self, Str>,
    pub place_of_service_code: Set<Self, Str>,
    pub bill_type_code: Set<Self, Str>,
    pub drg_code_type: Col<Self, Str>,
    pub drg_code: Set<Self, Str>,
    pub revenue_center_code: Set<Self, Str>,
    pub service_unit_quantity: Set<Self, i64>,
    pub hcpcs_code: Set<Self, Str>,
    pub hcpcs_modifier_1: Set<Self, Str>,
    pub hcpcs_modifier_2: Set<Self, Str>,
    pub hcpcs_modifier_3: Set<Self, Str>,
    pub hcpcs_modifier_4: Set<Self, Str>,
    pub hcpcs_modifier_5: Set<Self, Str>,
    pub rendering_npi: Col<Self, Str>,
    pub rendering_tin: Set<Self, Str>,
    pub billing_npi: Set<Self, Str>,
    pub billing_tin: Set<Self, Str>,
    pub facility_npi: Set<Self, Str>,
    pub paid_date: Set<Self, Date>,
    pub paid_amount: Set<Self, f64>,
    pub allowed_amount: Set<Self, f64>,
    pub charge_amount: Col<Self, f64>,
    pub coinsurance_amount: Set<Self, f64>,
    pub copayment_amount: Set<Self, f64>,
    pub deductible_amount: Set<Self, f64>,
    pub total_cost_amount: Set<Self, f64>,
    pub diagnosis_code_type: Set<Self, Str>,
    pub diagnosis_code_1: Set<Self, Str>,
    pub diagnosis_code_2: Set<Self, Str>,
    pub diagnosis_code_3: Set<Self, Str>,
    pub diagnosis_code_4: Set<Self, Str>,
    pub diagnosis_code_5: Set<Self, Str>,
    pub diagnosis_code_6: Set<Self, Str>,
    pub diagnosis_code_7: Set<Self, Str>,
    pub diagnosis_code_8: Set<Self, Str>,
    pub diagnosis_code_9: Set<Self, Str>,
    pub diagnosis_code_10: Set<Self, Str>,
    pub diagnosis_code_11: Set<Self, Str>,
    pub diagnosis_code_12: Set<Self, Str>,
    pub diagnosis_code_13: Set<Self, Str>,
    pub diagnosis_code_14: Set<Self, Str>,
    pub diagnosis_code_15: Set<Self, Str>,
    pub diagnosis_code_16: Set<Self, Str>,
    pub diagnosis_code_17: Set<Self, Str>,
    pub diagnosis_code_18: Set<Self, Str>,
    pub diagnosis_code_19: Set<Self, Str>,
    pub diagnosis_code_20: Set<Self, Str>,
    pub diagnosis_code_21: Set<Self, Str>,
    pub diagnosis_code_22: Set<Self, Str>,
    pub diagnosis_code_23: Set<Self, Str>,
    pub diagnosis_code_24: Set<Self, Str>,
    pub diagnosis_code_25: Set<Self, Str>,
    pub diagnosis_poa_1: Set<Self, Str>,
    pub diagnosis_poa_2: Set<Self, Str>,
    pub diagnosis_poa_3: Set<Self, Str>,
    pub diagnosis_poa_4: Set<Self, Str>,
    pub diagnosis_poa_5: Set<Self, Str>,
    pub diagnosis_poa_6: Set<Self, Str>,
    pub diagnosis_poa_7: Set<Self, Str>,
    pub diagnosis_poa_8: Set<Self, Str>,
    pub diagnosis_poa_9: Set<Self, Str>,
    pub diagnosis_poa_10: Set<Self, Str>,
    pub diagnosis_poa_11: Set<Self, Str>,
    pub diagnosis_poa_12: Set<Self, Str>,
    pub diagnosis_poa_13: Set<Self, Str>,
    pub diagnosis_poa_14: Set<Self, Str>,
    pub diagnosis_poa_15: Set<Self, Str>,
    pub diagnosis_poa_16: Set<Self, Str>,
    pub diagnosis_poa_17: Set<Self, Str>,
    pub diagnosis_poa_18: Set<Self, Str>,
    pub diagnosis_poa_19: Set<Self, Str>,
    pub diagnosis_poa_20: Set<Self, Str>,
    pub diagnosis_poa_21: Set<Self, Str>,
    pub diagnosis_poa_22: Set<Self, Str>,
    pub diagnosis_poa_23: Set<Self, Str>,
    pub diagnosis_poa_24: Set<Self, Str>,
    pub diagnosis_poa_25: Set<Self, Str>,
    pub procedure_code_type: Set<Self, Str>,
    pub procedure_code_1: Set<Self, Str>,
    pub procedure_code_2: Set<Self, Str>,
    pub procedure_code_3: Set<Self, Str>,
    pub procedure_code_4: Set<Self, Str>,
    pub procedure_code_5: Set<Self, Str>,
    pub procedure_code_6: Set<Self, Str>,
    pub procedure_code_7: Set<Self, Str>,
    pub procedure_code_8: Set<Self, Str>,
    pub procedure_code_9: Set<Self, Str>,
    pub procedure_code_10: Set<Self, Str>,
    pub procedure_code_11: Set<Self, Str>,
    pub procedure_code_12: Set<Self, Str>,
    pub procedure_code_13: Set<Self, Str>,
    pub procedure_code_14: Set<Self, Str>,
    pub procedure_code_15: Set<Self, Str>,
    pub procedure_code_16: Set<Self, Str>,
    pub procedure_code_17: Set<Self, Str>,
    pub procedure_code_18: Set<Self, Str>,
    pub procedure_code_19: Set<Self, Str>,
    pub procedure_code_20: Set<Self, Str>,
    pub procedure_code_21: Set<Self, Str>,
    pub procedure_code_22: Set<Self, Str>,
    pub procedure_code_23: Set<Self, Str>,
    pub procedure_code_24: Set<Self, Str>,
    pub procedure_code_25: Set<Self, Str>,
    pub procedure_date_1: Set<Self, Date>,
    pub procedure_date_2: Set<Self, Date>,
    pub procedure_date_3: Set<Self, Date>,
    pub procedure_date_4: Set<Self, Date>,
    pub procedure_date_5: Set<Self, Date>,
    pub procedure_date_6: Set<Self, Date>,
    pub procedure_date_7: Set<Self, Date>,
    pub procedure_date_8: Set<Self, Date>,
    pub procedure_date_9: Set<Self, Date>,
    pub procedure_date_10: Set<Self, Date>,
    pub procedure_date_11: Set<Self, Date>,
    pub procedure_date_12: Set<Self, Date>,
    pub procedure_date_13: Set<Self, Date>,
    pub procedure_date_14: Set<Self, Date>,
    pub procedure_date_15: Set<Self, Date>,
    pub procedure_date_16: Set<Self, Date>,
    pub procedure_date_17: Set<Self, Date>,
    pub procedure_date_18: Set<Self, Date>,
    pub procedure_date_19: Set<Self, Date>,
    pub procedure_date_20: Set<Self, Date>,
    pub procedure_date_21: Set<Self, Date>,
    pub procedure_date_22: Set<Self, Date>,
    pub procedure_date_23: Set<Self, Date>,
    pub procedure_date_24: Set<Self, Date>,
    pub procedure_date_25: Set<Self, Date>,
    pub in_network_flag: Col<Self, i64>,
    pub data_source: Col<Self, Str>,
    pub file_name: Col<Self, Str>,
    pub file_date: Col<Self, Date>,
    pub ingest_datetime: Col<Self, Ts>,
}

#[derive(IntoQuery)]
pub struct AdmitSource {
    #[primary_key]
    pub id: Key<Self>,
    pub admit_source_code: Col<Self, Str>,
    pub admit_source_description: Col<Self, Str>,
    pub newborn_description: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct AdmitType {
    #[primary_key]
    pub id: Key<Self>,
    pub admit_type_code: Col<Self, Str>,
    pub admit_type_description: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct AnsiFipsState {
    #[primary_key]
    pub id: Key<Self>,
    pub ansi_fips_state_code: Col<Self, Str>,
    pub ansi_fips_state_abbreviation: Col<Self, Str>,
    pub ansi_fips_state_name: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct AprDrg {
    #[primary_key]
    pub id: Key<Self>,
    pub apr_drg_code: Col<Self, Str>,
    pub medical_surgical: Set<Self, Str>,
    pub mdc_code: Set<Self, Str>,
    pub apr_drg_description: Col<Self, Str>,
    pub deprecated: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct BillType {
    #[primary_key]
    pub id: Key<Self>,
    pub bill_type_code: Col<Self, Str>,
    pub bill_type_description: Col<Self, Str>,
    pub deprecated: Col<Self, i64>,
    pub deprecated_date: Set<Self, Date>,
}

#[derive(IntoQuery)]
pub struct DischargeDisposition {
    #[primary_key]
    pub id: Key<Self>,
    pub discharge_disposition_code: Col<Self, Str>,
    pub discharge_disposition_description: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct Icd10Cm {
    #[primary_key]
    pub id: Key<Self>,
    pub icd_10_cm: Col<Self, Str>,
    pub billable_code_flag: Col<Self, Str>,
    pub short_description: Col<Self, Str>,
    pub long_description: Col<Self, Str>,
    pub deprecated: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct Icd10Pcs {
    #[primary_key]
    pub id: Key<Self>,
    pub icd_10_pcs: Col<Self, Str>,
    pub description: Col<Self, Str>,
    pub deprecated: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct Icd9Cm {
    #[primary_key]
    pub id: Key<Self>,
    pub icd_9_cm: Col<Self, Str>,
    pub long_description: Col<Self, Str>,
    pub short_description: Col<Self, Str>,
    pub deprecated: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct Icd9Pcs {
    #[primary_key]
    pub id: Key<Self>,
    pub icd_9_pcs: Col<Self, Str>,
    pub long_description: Col<Self, Str>,
    pub short_description: Col<Self, Str>,
    pub deprecated: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct MsDrg {
    #[primary_key]
    pub id: Key<Self>,
    pub ms_drg_code: Col<Self, Str>,
    pub mdc_code: Set<Self, Str>,
    pub medical_surgical: Set<Self, Str>,
    pub ms_drg_description: Col<Self, Str>,
    pub deprecated: Col<Self, i64>,
    pub deprecated_date: Set<Self, Date>,
}

#[derive(IntoQuery)]
pub struct Nitos {
    #[primary_key]
    pub id: Key<Self>,
    pub hcpcs_code: Col<Self, Str>,
    pub nitos_code: Col<Self, Str>,
    pub nitos_description: Col<Self, Str>,
    pub invasive_non_invasive_flag: Col<Self, Str>,
    pub modality: Col<Self, Str>,
    pub body_region: Col<Self, Str>,
    pub focus_area: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct PlaceOfService {
    #[primary_key]
    pub id: Key<Self>,
    pub place_of_service_code: Col<Self, Str>,
    pub place_of_service_description: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct RevenueCenter {
    #[primary_key]
    pub id: Key<Self>,
    pub revenue_center_code: Col<Self, Str>,
    pub revenue_center_description: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct PrimaryCareHcpcsCodes {
    #[primary_key]
    pub id: Key<Self>,
    pub hcpcs_code: Col<Self, Str>,
    pub description: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct ProviderSpecialtyAssignmentCodes {
    #[primary_key]
    pub id: Key<Self>,
    pub specialty_code: Col<Self, Str>,
    pub description: Col<Self, Str>,
    pub primary_care_physician_step1: Set<Self, Str>,
    pub specialist_physician_step_2: Set<Self, Str>,
    pub physician: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct CcsServicesProcedures {
    #[primary_key]
    pub id: Key<Self>,
    pub hcpcs_code: Col<Self, Str>,
    pub ccs_category: Col<Self, Str>,
    pub ccs_category_description: Col<Self, Str>,
    pub release_year: Col<Self, i64>,
    pub start_valid_date: Col<Self, Date>,
    pub end_valid_date: Col<Self, Date>,
    pub code_range: Col<Self, Str>,
    pub source_file: Col<Self, Str>,
}

pub struct Db {
    pub int_combined_professional: IntCombinedProfessional,
    pub service_category_office_based_radiology: ServiceCategoryOfficeBasedRadiology,
    pub service_category_stg_outpatient_institutional: ServiceCategoryStgOutpatientInstitutional,
    pub service_category_stg_professional: ServiceCategoryStgProfessional,
    pub service_category_grouper: ServiceCategoryGrouper,
    pub int_claim_level_diagnosis: IntClaimLevelDiagnosis,
    pub medicare_provider_and_supplier_taxonomy_crosswalk: MedicareProviderAndSupplierTaxonomyCrosswalk,
    pub provider: Provider,
    pub eligibility: Eligibility,
    pub medical_claim: MedicalClaim,
    pub admit_source: AdmitSource,
    pub admit_type: AdmitType,
    pub ansi_fips_state: AnsiFipsState,
    pub apr_drg: AprDrg,
    pub bill_type: BillType,
    pub discharge_disposition: DischargeDisposition,
    pub icd10_cm: Icd10Cm,
    pub icd10_pcs: Icd10Pcs,
    pub icd9_cm: Icd9Cm,
    pub icd9_pcs: Icd9Pcs,
    pub ms_drg: MsDrg,
    pub nitos: Nitos,
    pub place_of_service: PlaceOfService,
    pub revenue_center: RevenueCenter,
    pub primary_care_hcpcs_codes: PrimaryCareHcpcsCodes,
    pub provider_specialty_assignment_codes: ProviderSpecialtyAssignmentCodes,
    pub ccs_services_procedures: CcsServicesProcedures,
}

fn build(l: &mut Loader) -> Db {
    Db {
        int_combined_professional: IntCombinedProfessional {
            id: l.key("IntCombinedProfessional_row"),
            claim_id: l.strs("IntCombinedProfessional_claim_id"),
            claim_line_number: l.i64s("IntCombinedProfessional_claim_line_number"),
            data_source: l.strs("IntCombinedProfessional_data_source"),
            claim_line_id: l.multi_strs("IntCombinedProfessional_claim_line_id"),
            service_category_1: l.strs("IntCombinedProfessional_service_category_1"),
            service_category_2: l.strs("IntCombinedProfessional_service_category_2"),
            service_category_3: l.strs("IntCombinedProfessional_service_category_3"),
            tuva_last_run: l.i64s("IntCombinedProfessional_tuva_last_run"),
            source_model_name: l.strs("IntCombinedProfessional_source_model_name"),
        },
        service_category_office_based_radiology: ServiceCategoryOfficeBasedRadiology {
            id: l.key("ServiceCategoryOfficeBasedRadiology_row"),
            claim_id: l.strs("ServiceCategoryOfficeBasedRadiology_claim_id"),
            claim_line_number: l.i64s("ServiceCategoryOfficeBasedRadiology_claim_line_number"),
            data_source: l.strs("ServiceCategoryOfficeBasedRadiology_data_source"),
            claim_line_id: l.strs("ServiceCategoryOfficeBasedRadiology_claim_line_id"),
            service_category_1: l.strs("ServiceCategoryOfficeBasedRadiology_service_category_1"),
            service_category_2: l.strs("ServiceCategoryOfficeBasedRadiology_service_category_2"),
            service_category_3: l.strs("ServiceCategoryOfficeBasedRadiology_service_category_3"),
            source_model_name: l.strs("ServiceCategoryOfficeBasedRadiology_source_model_name"),
            tuva_last_run: l.i64s("ServiceCategoryOfficeBasedRadiology_tuva_last_run"),
        },
        service_category_stg_outpatient_institutional: ServiceCategoryStgOutpatientInstitutional {
            id: l.key("ServiceCategoryStgOutpatientInstitutional_row"),
            claim_id: l.strs("ServiceCategoryStgOutpatientInstitutional_claim_id"),
            data_source: l.strs("ServiceCategoryStgOutpatientInstitutional_data_source"),
            service_type: l.strs("ServiceCategoryStgOutpatientInstitutional_service_type"),
            tuva_last_run: l.i64s("ServiceCategoryStgOutpatientInstitutional_tuva_last_run"),
        },
        service_category_stg_professional: ServiceCategoryStgProfessional {
            id: l.key("ServiceCategoryStgProfessional_row"),
            claim_id: l.strs("ServiceCategoryStgProfessional_claim_id"),
            claim_line_number: l.i64s("ServiceCategoryStgProfessional_claim_line_number"),
            data_source: l.strs("ServiceCategoryStgProfessional_data_source"),
            claim_line_id: l.strs("ServiceCategoryStgProfessional_claim_line_id"),
            service_type: l.strs("ServiceCategoryStgProfessional_service_type"),
            tuva_last_run: l.i64s("ServiceCategoryStgProfessional_tuva_last_run"),
        },
        service_category_grouper: ServiceCategoryGrouper {
            id: l.key("ServiceCategoryGrouper_row"),
            claim_id: l.strs("ServiceCategoryGrouper_claim_id"),
            claim_line_number: l.i64s("ServiceCategoryGrouper_claim_line_number"),
            data_source: l.strs("ServiceCategoryGrouper_data_source"),
            claim_type: l.strs("ServiceCategoryGrouper_claim_type"),
            service_category_1: l.strs("ServiceCategoryGrouper_service_category_1"),
            service_category_2: l.strs("ServiceCategoryGrouper_service_category_2"),
            service_category_3: l.strs("ServiceCategoryGrouper_service_category_3"),
            original_service_cat_2: l.multi_strs("ServiceCategoryGrouper_original_service_cat_2"),
            original_service_cat_3: l.multi_strs("ServiceCategoryGrouper_original_service_cat_3"),
            duplicate_row_number: l.i64s("ServiceCategoryGrouper_duplicate_row_number"),
            ccs_category: l.multi_strs("ServiceCategoryGrouper_ccs_category"),
            ccs_category_description: l.multi_strs("ServiceCategoryGrouper_ccs_category_description"),
            drg_code: l.multi_strs("ServiceCategoryGrouper_drg_code"),
            drg_description: l.multi_strs("ServiceCategoryGrouper_drg_description"),
            place_of_service_code: l.multi_strs("ServiceCategoryGrouper_place_of_service_code"),
            place_of_service_description: l.multi_strs("ServiceCategoryGrouper_place_of_service_description"),
            revenue_center_code: l.multi_strs("ServiceCategoryGrouper_revenue_center_code"),
            revenue_center_description: l.multi_strs("ServiceCategoryGrouper_revenue_center_description"),
            hcpcs_code: l.multi_strs("ServiceCategoryGrouper_hcpcs_code"),
            default_ccsr_category_ip: l.multi_strs("ServiceCategoryGrouper_default_ccsr_category_ip"),
            default_ccsr_category_op: l.multi_strs("ServiceCategoryGrouper_default_ccsr_category_op"),
            default_ccsr_category_description_ip: l.multi_strs("ServiceCategoryGrouper_default_ccsr_category_description_ip"),
            default_ccsr_category_description_op: l.multi_strs("ServiceCategoryGrouper_default_ccsr_category_description_op"),
            primary_taxonomy_code: l.multi_strs("ServiceCategoryGrouper_primary_taxonomy_code"),
            primary_specialty_description: l.multi_strs("ServiceCategoryGrouper_primary_specialty_description"),
            modality: l.multi_strs("ServiceCategoryGrouper_modality"),
            bill_type_code: l.multi_strs("ServiceCategoryGrouper_bill_type_code"),
            bill_type_description: l.multi_strs("ServiceCategoryGrouper_bill_type_description"),
            source_model_name: l.multi_strs("ServiceCategoryGrouper_source_model_name"),
        },
        int_claim_level_diagnosis: IntClaimLevelDiagnosis {
            id: l.key("IntClaimLevelDiagnosis_row"),
            claim_id: l.strs("IntClaimLevelDiagnosis_claim_id"),
            data_source: l.strs("IntClaimLevelDiagnosis_data_source"),
            diagnosis_code_type: l.strs("IntClaimLevelDiagnosis_diagnosis_code_type"),
            diagnosis_code_1: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_1"),
            diagnosis_code_2: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_2"),
            diagnosis_code_3: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_3"),
            diagnosis_code_4: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_4"),
            diagnosis_code_5: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_5"),
            diagnosis_code_6: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_6"),
            diagnosis_code_7: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_7"),
            diagnosis_code_8: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_8"),
            diagnosis_code_9: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_9"),
            diagnosis_code_10: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_10"),
            diagnosis_code_11: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_11"),
            diagnosis_code_12: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_12"),
            diagnosis_code_13: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_13"),
            diagnosis_code_14: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_14"),
            diagnosis_code_15: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_15"),
            diagnosis_code_16: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_16"),
            diagnosis_code_17: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_17"),
            diagnosis_code_18: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_18"),
            diagnosis_code_19: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_19"),
            diagnosis_code_20: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_20"),
            diagnosis_code_21: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_21"),
            diagnosis_code_22: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_22"),
            diagnosis_code_23: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_23"),
            diagnosis_code_24: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_24"),
            diagnosis_code_25: l.multi_strs("IntClaimLevelDiagnosis_diagnosis_code_25"),
            tuva_last_run: l.i64s("IntClaimLevelDiagnosis_tuva_last_run"),
        },
        medicare_provider_and_supplier_taxonomy_crosswalk: MedicareProviderAndSupplierTaxonomyCrosswalk {
            id: l.key("MedicareProviderAndSupplierTaxonomyCrosswalk_row"),
            medicare_specialty_code: l.strs("MedicareProviderAndSupplierTaxonomyCrosswalk_medicare_specialty_code"),
            medicare_provider_supplier_type_description: l.strs("MedicareProviderAndSupplierTaxonomyCrosswalk_medicare_provider_supplier_type_description"),
            provider_taxonomy_code: l.multi_strs("MedicareProviderAndSupplierTaxonomyCrosswalk_provider_taxonomy_code"),
            provider_taxonomy_description: l.multi_strs("MedicareProviderAndSupplierTaxonomyCrosswalk_provider_taxonomy_description"),
        },
        provider: Provider {
            id: l.key("Provider_row"),
            npi: l.strs("Provider_npi"),
            entity_type_code: l.multi_strs("Provider_entity_type_code"),
            entity_type_description: l.multi_strs("Provider_entity_type_description"),
            primary_taxonomy_code: l.multi_strs("Provider_primary_taxonomy_code"),
            primary_specialty_description: l.multi_strs("Provider_primary_specialty_description"),
            provider_first_name: l.multi_strs("Provider_provider_first_name"),
            provider_last_name: l.multi_strs("Provider_provider_last_name"),
            provider_credential: l.multi_strs("Provider_provider_credential"),
            provider_organization_name: l.multi_strs("Provider_provider_organization_name"),
            provider_other_organization_name: l.multi_strs("Provider_provider_other_organization_name"),
            provider_other_organization_name_type_code: l.multi_strs("Provider_provider_other_organization_name_type_code"),
            provider_other_organization_name_type_description: l.multi_strs("Provider_provider_other_organization_name_type_description"),
            parent_organization_name: l.multi_strs("Provider_parent_organization_name"),
            practice_address_line_1: l.multi_strs("Provider_practice_address_line_1"),
            practice_address_line_2: l.multi_strs("Provider_practice_address_line_2"),
            practice_city: l.multi_strs("Provider_practice_city"),
            practice_state: l.multi_strs("Provider_practice_state"),
            practice_zip_code: l.multi_strs("Provider_practice_zip_code"),
            mailing_telephone_number: l.multi_strs("Provider_mailing_telephone_number"),
            location_telephone_number: l.multi_strs("Provider_location_telephone_number"),
            official_telephone_number: l.multi_strs("Provider_official_telephone_number"),
            last_updated: l.multi_i64("Provider_last_updated"),
            deactivation_date: l.multi_i64("Provider_deactivation_date"),
            deactivation_flag: l.strs("Provider_deactivation_flag"),
        },
        eligibility: Eligibility {
            id: l.key("Eligibility_row"),
            person_id: l.strs("Eligibility_person_id"),
            member_id: l.strs("Eligibility_member_id"),
            subscriber_id: l.multi_strs("Eligibility_subscriber_id"),
            sex: l.strs("Eligibility_sex"),
            race: l.strs("Eligibility_race"),
            birth_date: l.i64s("Eligibility_birth_date"),
            death_date: l.multi_i64("Eligibility_death_date"),
            death_flag: l.i64s("Eligibility_death_flag"),
            enrollment_start_date: l.i64s("Eligibility_enrollment_start_date"),
            enrollment_end_date: l.i64s("Eligibility_enrollment_end_date"),
            payer: l.strs("Eligibility_payer"),
            payer_type: l.strs("Eligibility_payer_type"),
            plan: l.strs("Eligibility_plan"),
            original_reason_entitlement_code: l.strs("Eligibility_original_reason_entitlement_code"),
            dual_status_code: l.multi_strs("Eligibility_dual_status_code"),
            medicare_status_code: l.strs("Eligibility_medicare_status_code"),
            group_id: l.strs("Eligibility_group_id"),
            group_name: l.strs("Eligibility_group_name"),
            name_suffix: l.multi_strs("Eligibility_name_suffix"),
            first_name: l.multi_strs("Eligibility_first_name"),
            middle_name: l.multi_strs("Eligibility_middle_name"),
            last_name: l.multi_strs("Eligibility_last_name"),
            social_security_number: l.multi_strs("Eligibility_social_security_number"),
            subscriber_relation: l.multi_strs("Eligibility_subscriber_relation"),
            address: l.multi_strs("Eligibility_address"),
            city: l.multi_strs("Eligibility_city"),
            state: l.strs("Eligibility_state"),
            zip_code: l.multi_strs("Eligibility_zip_code"),
            phone: l.multi_strs("Eligibility_phone"),
            email: l.multi_strs("Eligibility_email"),
            ethnicity: l.multi_strs("Eligibility_ethnicity"),
            data_source: l.strs("Eligibility_data_source"),
            file_name: l.strs("Eligibility_file_name"),
            file_date: l.i64s("Eligibility_file_date"),
            ingest_datetime: l.i64s("Eligibility_ingest_datetime"),
            enrollment_status: l.multi_strs("Eligibility_enrollment_status"),
            hospice_flag: l.i64s("Eligibility_hospice_flag"),
            institutional_snp_flag: l.i64s("Eligibility_institutional_snp_flag"),
            medicaid_indicator: l.multi_i64("Eligibility_medicaid_indicator"),
            long_term_institutional_flag: l.i64s("Eligibility_long_term_institutional_flag"),
            part_d_raf_type: l.multi_strs("Eligibility_part_d_raf_type"),
            low_income_subsidy_indicator: l.multi_i64("Eligibility_low_income_subsidy_indicator"),
            metal_level: l.multi_strs("Eligibility_metal_level"),
            csr_indicator: l.multi_i64("Eligibility_csr_indicator"),
            enrollment_duration_months: l.multi_i64("Eligibility_enrollment_duration_months"),
            esrd_status: l.multi_i64("Eligibility_esrd_status"),
            transplant_duration_months: l.multi_i64("Eligibility_transplant_duration_months"),
        },
        medical_claim: MedicalClaim {
            id: l.key("MedicalClaim_row"),
            claim_id: l.strs("MedicalClaim_claim_id"),
            claim_line_number: l.i64s("MedicalClaim_claim_line_number"),
            claim_type: l.strs("MedicalClaim_claim_type"),
            person_id: l.strs("MedicalClaim_person_id"),
            member_id: l.strs("MedicalClaim_member_id"),
            payer: l.strs("MedicalClaim_payer"),
            plan: l.strs("MedicalClaim_plan"),
            claim_start_date: l.i64s("MedicalClaim_claim_start_date"),
            claim_end_date: l.i64s("MedicalClaim_claim_end_date"),
            claim_line_start_date: l.multi_i64("MedicalClaim_claim_line_start_date"),
            claim_line_end_date: l.multi_i64("MedicalClaim_claim_line_end_date"),
            admission_date: l.multi_i64("MedicalClaim_admission_date"),
            discharge_date: l.multi_i64("MedicalClaim_discharge_date"),
            admit_source_code: l.multi_strs("MedicalClaim_admit_source_code"),
            admit_type_code: l.multi_strs("MedicalClaim_admit_type_code"),
            discharge_disposition_code: l.multi_strs("MedicalClaim_discharge_disposition_code"),
            place_of_service_code: l.multi_strs("MedicalClaim_place_of_service_code"),
            bill_type_code: l.multi_strs("MedicalClaim_bill_type_code"),
            drg_code_type: l.strs("MedicalClaim_drg_code_type"),
            drg_code: l.multi_strs("MedicalClaim_drg_code"),
            revenue_center_code: l.multi_strs("MedicalClaim_revenue_center_code"),
            service_unit_quantity: l.multi_i64("MedicalClaim_service_unit_quantity"),
            hcpcs_code: l.multi_strs("MedicalClaim_hcpcs_code"),
            hcpcs_modifier_1: l.multi_strs("MedicalClaim_hcpcs_modifier_1"),
            hcpcs_modifier_2: l.multi_strs("MedicalClaim_hcpcs_modifier_2"),
            hcpcs_modifier_3: l.multi_strs("MedicalClaim_hcpcs_modifier_3"),
            hcpcs_modifier_4: l.multi_strs("MedicalClaim_hcpcs_modifier_4"),
            hcpcs_modifier_5: l.multi_strs("MedicalClaim_hcpcs_modifier_5"),
            rendering_npi: l.strs("MedicalClaim_rendering_npi"),
            rendering_tin: l.multi_strs("MedicalClaim_rendering_tin"),
            billing_npi: l.multi_strs("MedicalClaim_billing_npi"),
            billing_tin: l.multi_strs("MedicalClaim_billing_tin"),
            facility_npi: l.multi_strs("MedicalClaim_facility_npi"),
            paid_date: l.multi_i64("MedicalClaim_paid_date"),
            paid_amount: harness::cols::multi_f64(l, "MedicalClaim_paid_amount"),
            allowed_amount: harness::cols::multi_f64(l, "MedicalClaim_allowed_amount"),
            charge_amount: l.f64s("MedicalClaim_charge_amount"),
            coinsurance_amount: harness::cols::multi_f64(l, "MedicalClaim_coinsurance_amount"),
            copayment_amount: harness::cols::multi_f64(l, "MedicalClaim_copayment_amount"),
            deductible_amount: harness::cols::multi_f64(l, "MedicalClaim_deductible_amount"),
            total_cost_amount: harness::cols::multi_f64(l, "MedicalClaim_total_cost_amount"),
            diagnosis_code_type: l.multi_strs("MedicalClaim_diagnosis_code_type"),
            diagnosis_code_1: l.multi_strs("MedicalClaim_diagnosis_code_1"),
            diagnosis_code_2: l.multi_strs("MedicalClaim_diagnosis_code_2"),
            diagnosis_code_3: l.multi_strs("MedicalClaim_diagnosis_code_3"),
            diagnosis_code_4: l.multi_strs("MedicalClaim_diagnosis_code_4"),
            diagnosis_code_5: l.multi_strs("MedicalClaim_diagnosis_code_5"),
            diagnosis_code_6: l.multi_strs("MedicalClaim_diagnosis_code_6"),
            diagnosis_code_7: l.multi_strs("MedicalClaim_diagnosis_code_7"),
            diagnosis_code_8: l.multi_strs("MedicalClaim_diagnosis_code_8"),
            diagnosis_code_9: l.multi_strs("MedicalClaim_diagnosis_code_9"),
            diagnosis_code_10: l.multi_strs("MedicalClaim_diagnosis_code_10"),
            diagnosis_code_11: l.multi_strs("MedicalClaim_diagnosis_code_11"),
            diagnosis_code_12: l.multi_strs("MedicalClaim_diagnosis_code_12"),
            diagnosis_code_13: l.multi_strs("MedicalClaim_diagnosis_code_13"),
            diagnosis_code_14: l.multi_strs("MedicalClaim_diagnosis_code_14"),
            diagnosis_code_15: l.multi_strs("MedicalClaim_diagnosis_code_15"),
            diagnosis_code_16: l.multi_strs("MedicalClaim_diagnosis_code_16"),
            diagnosis_code_17: l.multi_strs("MedicalClaim_diagnosis_code_17"),
            diagnosis_code_18: l.multi_strs("MedicalClaim_diagnosis_code_18"),
            diagnosis_code_19: l.multi_strs("MedicalClaim_diagnosis_code_19"),
            diagnosis_code_20: l.multi_strs("MedicalClaim_diagnosis_code_20"),
            diagnosis_code_21: l.multi_strs("MedicalClaim_diagnosis_code_21"),
            diagnosis_code_22: l.multi_strs("MedicalClaim_diagnosis_code_22"),
            diagnosis_code_23: l.multi_strs("MedicalClaim_diagnosis_code_23"),
            diagnosis_code_24: l.multi_strs("MedicalClaim_diagnosis_code_24"),
            diagnosis_code_25: l.multi_strs("MedicalClaim_diagnosis_code_25"),
            diagnosis_poa_1: l.multi_strs("MedicalClaim_diagnosis_poa_1"),
            diagnosis_poa_2: l.multi_strs("MedicalClaim_diagnosis_poa_2"),
            diagnosis_poa_3: l.multi_strs("MedicalClaim_diagnosis_poa_3"),
            diagnosis_poa_4: l.multi_strs("MedicalClaim_diagnosis_poa_4"),
            diagnosis_poa_5: l.multi_strs("MedicalClaim_diagnosis_poa_5"),
            diagnosis_poa_6: l.multi_strs("MedicalClaim_diagnosis_poa_6"),
            diagnosis_poa_7: l.multi_strs("MedicalClaim_diagnosis_poa_7"),
            diagnosis_poa_8: l.multi_strs("MedicalClaim_diagnosis_poa_8"),
            diagnosis_poa_9: l.multi_strs("MedicalClaim_diagnosis_poa_9"),
            diagnosis_poa_10: l.multi_strs("MedicalClaim_diagnosis_poa_10"),
            diagnosis_poa_11: l.multi_strs("MedicalClaim_diagnosis_poa_11"),
            diagnosis_poa_12: l.multi_strs("MedicalClaim_diagnosis_poa_12"),
            diagnosis_poa_13: l.multi_strs("MedicalClaim_diagnosis_poa_13"),
            diagnosis_poa_14: l.multi_strs("MedicalClaim_diagnosis_poa_14"),
            diagnosis_poa_15: l.multi_strs("MedicalClaim_diagnosis_poa_15"),
            diagnosis_poa_16: l.multi_strs("MedicalClaim_diagnosis_poa_16"),
            diagnosis_poa_17: l.multi_strs("MedicalClaim_diagnosis_poa_17"),
            diagnosis_poa_18: l.multi_strs("MedicalClaim_diagnosis_poa_18"),
            diagnosis_poa_19: l.multi_strs("MedicalClaim_diagnosis_poa_19"),
            diagnosis_poa_20: l.multi_strs("MedicalClaim_diagnosis_poa_20"),
            diagnosis_poa_21: l.multi_strs("MedicalClaim_diagnosis_poa_21"),
            diagnosis_poa_22: l.multi_strs("MedicalClaim_diagnosis_poa_22"),
            diagnosis_poa_23: l.multi_strs("MedicalClaim_diagnosis_poa_23"),
            diagnosis_poa_24: l.multi_strs("MedicalClaim_diagnosis_poa_24"),
            diagnosis_poa_25: l.multi_strs("MedicalClaim_diagnosis_poa_25"),
            procedure_code_type: l.multi_strs("MedicalClaim_procedure_code_type"),
            procedure_code_1: l.multi_strs("MedicalClaim_procedure_code_1"),
            procedure_code_2: l.multi_strs("MedicalClaim_procedure_code_2"),
            procedure_code_3: l.multi_strs("MedicalClaim_procedure_code_3"),
            procedure_code_4: l.multi_strs("MedicalClaim_procedure_code_4"),
            procedure_code_5: l.multi_strs("MedicalClaim_procedure_code_5"),
            procedure_code_6: l.multi_strs("MedicalClaim_procedure_code_6"),
            procedure_code_7: l.multi_strs("MedicalClaim_procedure_code_7"),
            procedure_code_8: l.multi_strs("MedicalClaim_procedure_code_8"),
            procedure_code_9: l.multi_strs("MedicalClaim_procedure_code_9"),
            procedure_code_10: l.multi_strs("MedicalClaim_procedure_code_10"),
            procedure_code_11: l.multi_strs("MedicalClaim_procedure_code_11"),
            procedure_code_12: l.multi_strs("MedicalClaim_procedure_code_12"),
            procedure_code_13: l.multi_strs("MedicalClaim_procedure_code_13"),
            procedure_code_14: l.multi_strs("MedicalClaim_procedure_code_14"),
            procedure_code_15: l.multi_strs("MedicalClaim_procedure_code_15"),
            procedure_code_16: l.multi_strs("MedicalClaim_procedure_code_16"),
            procedure_code_17: l.multi_strs("MedicalClaim_procedure_code_17"),
            procedure_code_18: l.multi_strs("MedicalClaim_procedure_code_18"),
            procedure_code_19: l.multi_strs("MedicalClaim_procedure_code_19"),
            procedure_code_20: l.multi_strs("MedicalClaim_procedure_code_20"),
            procedure_code_21: l.multi_strs("MedicalClaim_procedure_code_21"),
            procedure_code_22: l.multi_strs("MedicalClaim_procedure_code_22"),
            procedure_code_23: l.multi_strs("MedicalClaim_procedure_code_23"),
            procedure_code_24: l.multi_strs("MedicalClaim_procedure_code_24"),
            procedure_code_25: l.multi_strs("MedicalClaim_procedure_code_25"),
            procedure_date_1: l.multi_i64("MedicalClaim_procedure_date_1"),
            procedure_date_2: l.multi_i64("MedicalClaim_procedure_date_2"),
            procedure_date_3: l.multi_i64("MedicalClaim_procedure_date_3"),
            procedure_date_4: l.multi_i64("MedicalClaim_procedure_date_4"),
            procedure_date_5: l.multi_i64("MedicalClaim_procedure_date_5"),
            procedure_date_6: l.multi_i64("MedicalClaim_procedure_date_6"),
            procedure_date_7: l.multi_i64("MedicalClaim_procedure_date_7"),
            procedure_date_8: l.multi_i64("MedicalClaim_procedure_date_8"),
            procedure_date_9: l.multi_i64("MedicalClaim_procedure_date_9"),
            procedure_date_10: l.multi_i64("MedicalClaim_procedure_date_10"),
            procedure_date_11: l.multi_i64("MedicalClaim_procedure_date_11"),
            procedure_date_12: l.multi_i64("MedicalClaim_procedure_date_12"),
            procedure_date_13: l.multi_i64("MedicalClaim_procedure_date_13"),
            procedure_date_14: l.multi_i64("MedicalClaim_procedure_date_14"),
            procedure_date_15: l.multi_i64("MedicalClaim_procedure_date_15"),
            procedure_date_16: l.multi_i64("MedicalClaim_procedure_date_16"),
            procedure_date_17: l.multi_i64("MedicalClaim_procedure_date_17"),
            procedure_date_18: l.multi_i64("MedicalClaim_procedure_date_18"),
            procedure_date_19: l.multi_i64("MedicalClaim_procedure_date_19"),
            procedure_date_20: l.multi_i64("MedicalClaim_procedure_date_20"),
            procedure_date_21: l.multi_i64("MedicalClaim_procedure_date_21"),
            procedure_date_22: l.multi_i64("MedicalClaim_procedure_date_22"),
            procedure_date_23: l.multi_i64("MedicalClaim_procedure_date_23"),
            procedure_date_24: l.multi_i64("MedicalClaim_procedure_date_24"),
            procedure_date_25: l.multi_i64("MedicalClaim_procedure_date_25"),
            in_network_flag: l.i64s("MedicalClaim_in_network_flag"),
            data_source: l.strs("MedicalClaim_data_source"),
            file_name: l.strs("MedicalClaim_file_name"),
            file_date: l.i64s("MedicalClaim_file_date"),
            ingest_datetime: l.i64s("MedicalClaim_ingest_datetime"),
        },
        admit_source: AdmitSource {
            id: l.key("AdmitSource_row"),
            admit_source_code: l.strs("AdmitSource_admit_source_code"),
            admit_source_description: l.strs("AdmitSource_admit_source_description"),
            newborn_description: l.multi_strs("AdmitSource_newborn_description"),
        },
        admit_type: AdmitType {
            id: l.key("AdmitType_row"),
            admit_type_code: l.strs("AdmitType_admit_type_code"),
            admit_type_description: l.strs("AdmitType_admit_type_description"),
        },
        ansi_fips_state: AnsiFipsState {
            id: l.key("AnsiFipsState_row"),
            ansi_fips_state_code: l.strs("AnsiFipsState_ansi_fips_state_code"),
            ansi_fips_state_abbreviation: l.strs("AnsiFipsState_ansi_fips_state_abbreviation"),
            ansi_fips_state_name: l.strs("AnsiFipsState_ansi_fips_state_name"),
        },
        apr_drg: AprDrg {
            id: l.key("AprDrg_row"),
            apr_drg_code: l.strs("AprDrg_apr_drg_code"),
            medical_surgical: l.multi_strs("AprDrg_medical_surgical"),
            mdc_code: l.multi_strs("AprDrg_mdc_code"),
            apr_drg_description: l.strs("AprDrg_apr_drg_description"),
            deprecated: l.i64s("AprDrg_deprecated"),
        },
        bill_type: BillType {
            id: l.key("BillType_row"),
            bill_type_code: l.strs("BillType_bill_type_code"),
            bill_type_description: l.strs("BillType_bill_type_description"),
            deprecated: l.i64s("BillType_deprecated"),
            deprecated_date: l.multi_i64("BillType_deprecated_date"),
        },
        discharge_disposition: DischargeDisposition {
            id: l.key("DischargeDisposition_row"),
            discharge_disposition_code: l.strs("DischargeDisposition_discharge_disposition_code"),
            discharge_disposition_description: l.strs("DischargeDisposition_discharge_disposition_description"),
        },
        icd10_cm: Icd10Cm {
            id: l.key("Icd10Cm_row"),
            icd_10_cm: l.strs("Icd10Cm_icd_10_cm"),
            billable_code_flag: l.strs("Icd10Cm_billable_code_flag"),
            short_description: l.strs("Icd10Cm_short_description"),
            long_description: l.strs("Icd10Cm_long_description"),
            deprecated: l.i64s("Icd10Cm_deprecated"),
        },
        icd10_pcs: Icd10Pcs {
            id: l.key("Icd10Pcs_row"),
            icd_10_pcs: l.strs("Icd10Pcs_icd_10_pcs"),
            description: l.strs("Icd10Pcs_description"),
            deprecated: l.i64s("Icd10Pcs_deprecated"),
        },
        icd9_cm: Icd9Cm {
            id: l.key("Icd9Cm_row"),
            icd_9_cm: l.strs("Icd9Cm_icd_9_cm"),
            long_description: l.strs("Icd9Cm_long_description"),
            short_description: l.strs("Icd9Cm_short_description"),
            deprecated: l.i64s("Icd9Cm_deprecated"),
        },
        icd9_pcs: Icd9Pcs {
            id: l.key("Icd9Pcs_row"),
            icd_9_pcs: l.strs("Icd9Pcs_icd_9_pcs"),
            long_description: l.strs("Icd9Pcs_long_description"),
            short_description: l.strs("Icd9Pcs_short_description"),
            deprecated: l.i64s("Icd9Pcs_deprecated"),
        },
        ms_drg: MsDrg {
            id: l.key("MsDrg_row"),
            ms_drg_code: l.strs("MsDrg_ms_drg_code"),
            mdc_code: l.multi_strs("MsDrg_mdc_code"),
            medical_surgical: l.multi_strs("MsDrg_medical_surgical"),
            ms_drg_description: l.strs("MsDrg_ms_drg_description"),
            deprecated: l.i64s("MsDrg_deprecated"),
            deprecated_date: l.multi_i64("MsDrg_deprecated_date"),
        },
        nitos: Nitos {
            id: l.key("Nitos_row"),
            hcpcs_code: l.strs("Nitos_hcpcs_code"),
            nitos_code: l.strs("Nitos_nitos_code"),
            nitos_description: l.strs("Nitos_nitos_description"),
            invasive_non_invasive_flag: l.strs("Nitos_invasive_non_invasive_flag"),
            modality: l.strs("Nitos_modality"),
            body_region: l.strs("Nitos_body_region"),
            focus_area: l.strs("Nitos_focus_area"),
        },
        place_of_service: PlaceOfService {
            id: l.key("PlaceOfService_row"),
            place_of_service_code: l.strs("PlaceOfService_place_of_service_code"),
            place_of_service_description: l.strs("PlaceOfService_place_of_service_description"),
        },
        revenue_center: RevenueCenter {
            id: l.key("RevenueCenter_row"),
            revenue_center_code: l.strs("RevenueCenter_revenue_center_code"),
            revenue_center_description: l.strs("RevenueCenter_revenue_center_description"),
        },
        primary_care_hcpcs_codes: PrimaryCareHcpcsCodes {
            id: l.key("PrimaryCareHcpcsCodes_row"),
            hcpcs_code: l.strs("PrimaryCareHcpcsCodes_hcpcs_code"),
            description: l.strs("PrimaryCareHcpcsCodes_description"),
        },
        provider_specialty_assignment_codes: ProviderSpecialtyAssignmentCodes {
            id: l.key("ProviderSpecialtyAssignmentCodes_row"),
            specialty_code: l.strs("ProviderSpecialtyAssignmentCodes_specialty_code"),
            description: l.strs("ProviderSpecialtyAssignmentCodes_description"),
            primary_care_physician_step1: l.multi_strs("ProviderSpecialtyAssignmentCodes_primary_care_physician_step1"),
            specialist_physician_step_2: l.multi_strs("ProviderSpecialtyAssignmentCodes_specialist_physician_step_2"),
            physician: l.i64s("ProviderSpecialtyAssignmentCodes_physician"),
        },
        ccs_services_procedures: CcsServicesProcedures {
            id: l.key("CcsServicesProcedures_row"),
            hcpcs_code: l.strs("CcsServicesProcedures_hcpcs_code"),
            ccs_category: l.strs("CcsServicesProcedures_ccs_category"),
            ccs_category_description: l.strs("CcsServicesProcedures_ccs_category_description"),
            release_year: l.i64s("CcsServicesProcedures_release_year"),
            start_valid_date: l.i64s("CcsServicesProcedures_start_valid_date"),
            end_valid_date: l.i64s("CcsServicesProcedures_end_valid_date"),
            code_range: l.strs("CcsServicesProcedures_code_range"),
            source_file: l.strs("CcsServicesProcedures_source_file"),
        },
    }
}

pub fn load(dir: &Path) -> Db {
    build(&mut Loader::new(dir))
}

