// Reference example of the method-chain form. Kept as a registered query so
// `cargo asm` always has a known symbol to inspect.

use crate::engine::*;
use crate::job_schema::*;
use crate::job_queries::helpers::{min_row, Row};

pub const ENTRIES: &[super::Entry] = &[
    ("6a/method", "marvel-cinematic-universe || Iron Man 3 || Downey Jr., Robert", || min_row(q6a_methods())),
];

// q6a — movies from after 2010 tagged with the "marvel-cinematic-universe"
// keyword, projected to that keyword, the title, and the cast member whose
// name matches "Downey.*Robert".
//
// Method legend (engine.rs::QueryExt + the schema's generated nav traits;
// everything roots on IntoQuery, so paren-free leaf HANDLES — `keyword`,
// `movie`, `Entity::field` — mix freely with plan nodes):
//   .select(b)    composition (a set is an identity relation, so composing a
//            set with a query is the same Compose — no keyset projection)
//   .text()  / .person() / .name() … — navigation methods: per-field
//            compose, generated by `schema!` (`keyword.text()` is
//            equivalent to `keyword.select(Keyword::text)`;
//            `cast.person().name()` walks Movie, then Cast, then Person,
//            then name)
//   .and(b)    product
//   .and     also aliases the product for building conjunct trees, which are
//            consumed via the flat short-circuit `member` (restriction =
//            `.with`)
//   .or      probe-only membership union (drive with `.union`)
//   .minus   value-bearing difference (key-based member test)
//   .with    restriction — keep rows whose value is a member
//   .eq / .ne / .gt / .lt / .ge / .le / .is_in / .rx / .nrx  predicates
pub fn q6a_methods() -> impl Drive<R: Row> {
    let kw_marvel = || keyword.eq("marvel-cinematic-universe");
    let q = movie
        .with(production_year.gt(2010)
         .and(kw_marvel()))
        .select(kw_marvel()
         .and(title)
         .and(cast.person().rx(r"Downey.*Robert")));
    q
}
