use mimic::schema::{self, Db};

static ENTRIES: &[harness::run::Entry<Db>] = &[
    ("apsiii", mimic::queries::apsiii::q),
    ("first_day_sofa", mimic::queries::first_day_sofa::q),
    ("kdigo_stages", mimic::queries::kdigo_stages::q),
    ("lods", mimic::queries::lods::q),
    ("meld", mimic::queries::meld::q),
    ("oasis", mimic::queries::oasis::q),
    ("sapsii", mimic::queries::sapsii::q),
    ("sepsis3", mimic::queries::sepsis3::q),
    ("sirs", mimic::queries::sirs::q),
    ("sofa", mimic::queries::sofa::q),
    ("c_age", mimic::concepts::age::q),
    ("c_antibiotic", mimic::concepts::antibiotic::q),
    ("c_bg", mimic::concepts::bg::q),
    ("c_blood_differential", mimic::concepts::blood_differential::q),
    ("c_chemistry", mimic::concepts::chemistry::q),
    ("c_coagulation", mimic::concepts::coagulation::q),
    ("c_complete_blood_count", mimic::concepts::complete_blood_count::q),
    ("c_crrt", mimic::concepts::crrt::q),
    ("c_dobutamine", mimic::concepts::dobutamine::q),
    ("c_dopamine", mimic::concepts::dopamine::q),
    ("c_enzyme", mimic::concepts::enzyme::q),
    ("c_epinephrine", mimic::concepts::epinephrine::q),
    ("c_first_day_bg_art", mimic::concepts::first_day_bg_art::q),
    ("c_first_day_gcs", mimic::concepts::first_day_gcs::q),
    ("c_first_day_lab", mimic::concepts::first_day_lab::q),
    ("c_first_day_rrt", mimic::concepts::first_day_rrt::q),
    ("c_first_day_urine_output", mimic::concepts::first_day_urine_output::q),
    ("c_first_day_vitalsign", mimic::concepts::first_day_vitalsign::q),
    ("c_gcs", mimic::concepts::gcs::q),
    ("c_icustay_hourly", mimic::concepts::icustay_hourly::q),
    ("c_icustay_times", mimic::concepts::icustay_times::q),
    ("c_kdigo_creatinine", mimic::concepts::kdigo_creatinine::q),
    ("c_kdigo_uo", mimic::concepts::kdigo_uo::q),
    ("c_norepinephrine", mimic::concepts::norepinephrine::q),
    ("c_oxygen_delivery", mimic::concepts::oxygen_delivery::q),
    ("c_rrt", mimic::concepts::rrt::q),
    ("c_suspicion_of_infection", mimic::concepts::suspicion_of_infection::q),
    ("c_urine_output", mimic::concepts::urine_output::q),
    ("c_urine_output_rate", mimic::concepts::urine_output_rate::q),
    ("c_ventilation", mimic::concepts::ventilation::q),
    ("c_ventilator_setting", mimic::concepts::ventilator_setting::q),
    ("c_vitalsign", mimic::concepts::vitalsign::q),
    ("c_weight_durations", mimic::concepts::weight_durations::q),
];

fn main() {
    harness::run("mimic", schema::load, ENTRIES)
}
