#![allow(dead_code)]

use harness::time::{Date, Ts};
use prela::engine::{Id, IntoQuery};
use prela::loader::{Col, Key, Loader, Set, Str};
use std::path::Path;

#[derive(IntoQuery)]
pub struct Patient {
    #[primary_key]
    pub id: Key<Self>,
    pub subject_id: Col<Self, i64>,
    pub gender: Col<Self, Str>,
    pub anchor_age: Col<Self, i64>,
    pub anchor_year: Col<Self, i64>,
    pub anchor_year_group: Col<Self, Str>,
    pub dod: Set<Self, Date>,
}

#[derive(IntoQuery)]
pub struct Admission {
    #[primary_key]
    pub id: Key<Self>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm_id: Col<Self, i64>,
    pub admittime: Col<Self, Ts>,
    pub dischtime: Col<Self, Ts>,
    pub deathtime: Set<Self, Ts>,
    pub admission_type: Col<Self, Str>,
    pub admit_provider_id: Col<Self, Str>,
    pub admission_location: Col<Self, Str>,
    pub discharge_location: Set<Self, Str>,
    pub insurance: Col<Self, Str>,
    pub language: Col<Self, Str>,
    pub marital_status: Set<Self, Str>,
    pub race: Col<Self, Str>,
    pub edregtime: Set<Self, Ts>,
    pub edouttime: Set<Self, Ts>,
    pub hospital_expire_flag: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct IcuStay {
    #[primary_key]
    pub id: Key<Self>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm: Col<Self, Id<Admission>>,
    pub hadm_id: Col<Self, i64>,
    pub stay_id: Col<Self, i64>,
    pub first_careunit: Col<Self, Str>,
    pub last_careunit: Col<Self, Str>,
    pub intime: Col<Self, Ts>,
    pub outtime: Col<Self, Ts>,
    pub los: Col<Self, f64>,
}

#[derive(IntoQuery)]
pub struct DiagnosesIcd {
    #[primary_key]
    pub id: Key<Self>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm: Col<Self, Id<Admission>>,
    pub hadm_id: Col<Self, i64>,
    pub seq_num: Col<Self, i64>,
    pub icd_code: Col<Self, Str>,
    pub icd_version: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct LabEvent {
    #[primary_key]
    pub id: Key<Self>,
    pub labevent_id: Col<Self, i64>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm: Set<Self, Id<Admission>>,
    pub hadm_id: Set<Self, i64>,
    pub specimen_id: Col<Self, i64>,
    pub itemid: Col<Self, i64>,
    pub order_provider_id: Set<Self, Str>,
    pub charttime: Col<Self, Ts>,
    pub storetime: Set<Self, Ts>,
    pub value: Set<Self, Str>,
    pub valuenum: Set<Self, f64>,
    pub valueuom: Set<Self, Str>,
    pub ref_range_lower: Set<Self, f64>,
    pub ref_range_upper: Set<Self, f64>,
    pub flag: Set<Self, Str>,
    pub priority: Set<Self, Str>,
    pub comments: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct MicrobiologyEvent {
    #[primary_key]
    pub id: Key<Self>,
    pub microevent_id: Col<Self, i64>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm: Set<Self, Id<Admission>>,
    pub hadm_id: Set<Self, i64>,
    pub micro_specimen_id: Col<Self, i64>,
    pub order_provider_id: Set<Self, Str>,
    pub chartdate: Col<Self, Ts>,
    pub charttime: Set<Self, Ts>,
    pub spec_itemid: Col<Self, i64>,
    pub spec_type_desc: Col<Self, Str>,
    pub test_seq: Col<Self, i64>,
    pub storedate: Set<Self, Ts>,
    pub storetime: Set<Self, Ts>,
    pub test_itemid: Col<Self, i64>,
    pub test_name: Col<Self, Str>,
    pub org_itemid: Set<Self, i64>,
    pub org_name: Set<Self, Str>,
    pub isolate_num: Set<Self, i64>,
    pub quantity: Set<Self, Str>,
    pub ab_itemid: Set<Self, i64>,
    pub ab_name: Set<Self, Str>,
    pub dilution_text: Set<Self, Str>,
    pub dilution_comparison: Set<Self, Str>,
    pub dilution_value: Set<Self, f64>,
    pub interpretation: Set<Self, Str>,
    pub comments: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct Prescription {
    #[primary_key]
    pub id: Key<Self>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm: Col<Self, Id<Admission>>,
    pub hadm_id: Col<Self, i64>,
    pub pharmacy_id: Col<Self, i64>,
    pub poe_id: Set<Self, Str>,
    pub poe_seq: Set<Self, i64>,
    pub order_provider_id: Set<Self, Str>,
    pub starttime: Col<Self, Ts>,
    pub stoptime: Set<Self, Ts>,
    pub drug_type: Col<Self, Str>,
    pub drug: Col<Self, Str>,
    pub formulary_drug_cd: Set<Self, Str>,
    pub gsn: Set<Self, Str>,
    pub ndc: Set<Self, Str>,
    pub prod_strength: Set<Self, Str>,
    pub form_rx: Set<Self, Str>,
    pub dose_val_rx: Set<Self, Str>,
    pub dose_unit_rx: Set<Self, Str>,
    pub form_val_disp: Set<Self, Str>,
    pub form_unit_disp: Set<Self, Str>,
    pub doses_per_24_hrs: Set<Self, f64>,
    pub route: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct Service {
    #[primary_key]
    pub id: Key<Self>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm: Col<Self, Id<Admission>>,
    pub hadm_id: Col<Self, i64>,
    pub transfertime: Col<Self, Ts>,
    pub prev_service: Set<Self, Str>,
    pub curr_service: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct ChartEvent {
    #[primary_key]
    pub id: Key<Self>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm: Col<Self, Id<Admission>>,
    pub hadm_id: Col<Self, i64>,
    pub stay: Col<Self, Id<IcuStay>>,
    pub stay_id: Col<Self, i64>,
    pub caregiver_id: Set<Self, i64>,
    pub charttime: Col<Self, Ts>,
    pub storetime: Set<Self, Ts>,
    pub itemid: Col<Self, i64>,
    pub value: Col<Self, Str>,
    pub valuenum: Set<Self, f64>,
    pub valueuom: Set<Self, Str>,
    pub warning: Set<Self, i64>,
}

#[derive(IntoQuery)]
pub struct InputEvent {
    #[primary_key]
    pub id: Key<Self>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm: Col<Self, Id<Admission>>,
    pub hadm_id: Col<Self, i64>,
    pub stay: Col<Self, Id<IcuStay>>,
    pub stay_id: Col<Self, i64>,
    pub caregiver_id: Col<Self, i64>,
    pub starttime: Col<Self, Ts>,
    pub endtime: Col<Self, Ts>,
    pub storetime: Col<Self, Ts>,
    pub itemid: Col<Self, i64>,
    pub amount: Col<Self, f64>,
    pub amountuom: Col<Self, Str>,
    pub rate: Set<Self, f64>,
    pub rateuom: Set<Self, Str>,
    pub orderid: Col<Self, i64>,
    pub linkorderid: Col<Self, i64>,
    pub ordercategoryname: Col<Self, Str>,
    pub secondaryordercategoryname: Set<Self, Str>,
    pub ordercomponenttypedescription: Col<Self, Str>,
    pub ordercategorydescription: Col<Self, Str>,
    pub patientweight: Col<Self, f64>,
    pub totalamount: Set<Self, f64>,
    pub totalamountuom: Set<Self, Str>,
    pub isopenbag: Col<Self, i64>,
    pub continueinnextdept: Col<Self, i64>,
    pub statusdescription: Col<Self, Str>,
    pub originalamount: Col<Self, f64>,
    pub originalrate: Col<Self, f64>,
}

#[derive(IntoQuery)]
pub struct OutputEvent {
    #[primary_key]
    pub id: Key<Self>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm: Col<Self, Id<Admission>>,
    pub hadm_id: Col<Self, i64>,
    pub stay: Col<Self, Id<IcuStay>>,
    pub stay_id: Col<Self, i64>,
    pub caregiver_id: Col<Self, i64>,
    pub charttime: Col<Self, Ts>,
    pub storetime: Col<Self, Ts>,
    pub itemid: Col<Self, i64>,
    pub value: Col<Self, f64>,
    pub valueuom: Col<Self, Str>,
}

#[derive(IntoQuery)]
pub struct ProcedureEvent {
    #[primary_key]
    pub id: Key<Self>,
    pub subject: Col<Self, Id<Patient>>,
    pub subject_id: Col<Self, i64>,
    pub hadm: Col<Self, Id<Admission>>,
    pub hadm_id: Col<Self, i64>,
    pub stay: Col<Self, Id<IcuStay>>,
    pub stay_id: Col<Self, i64>,
    pub caregiver_id: Set<Self, i64>,
    pub starttime: Col<Self, Ts>,
    pub endtime: Col<Self, Ts>,
    pub storetime: Col<Self, Ts>,
    pub itemid: Col<Self, i64>,
    pub value: Col<Self, f64>,
    pub valueuom: Col<Self, Str>,
    pub location: Set<Self, Str>,
    pub locationcategory: Set<Self, Str>,
    pub orderid: Col<Self, i64>,
    pub linkorderid: Col<Self, i64>,
    pub ordercategoryname: Col<Self, Str>,
    pub ordercategorydescription: Col<Self, Str>,
    pub patientweight: Col<Self, f64>,
    pub isopenbag: Col<Self, i64>,
    pub continueinnextdept: Col<Self, i64>,
    pub statusdescription: Col<Self, Str>,
    pub originalamount: Col<Self, f64>,
    pub originalrate: Col<Self, f64>,
}

pub struct Db {
    pub patient: Patient,
    pub admission: Admission,
    pub icu_stay: IcuStay,
    pub diagnoses_icd: DiagnosesIcd,
    pub lab_event: LabEvent,
    pub microbiology_event: MicrobiologyEvent,
    pub prescription: Prescription,
    pub service: Service,
    pub chart_event: ChartEvent,
    pub input_event: InputEvent,
    pub output_event: OutputEvent,
    pub procedure_event: ProcedureEvent,
}

fn build(l: &mut Loader) -> Db {
    Db {
        patient: Patient {
            id: l.key("Patient_row"),
            subject_id: l.i64s("Patient_subject_id"),
            gender: l.strs("Patient_gender"),
            anchor_age: l.i64s("Patient_anchor_age"),
            anchor_year: l.i64s("Patient_anchor_year"),
            anchor_year_group: l.strs("Patient_anchor_year_group"),
            dod: l.multi_i64("Patient_dod"),
        },
        admission: Admission {
            id: l.key("Admission_row"),
            subject: l.ids("Admission_subject"),
            subject_id: l.i64s("Admission_subject_id"),
            hadm_id: l.i64s("Admission_hadm_id"),
            admittime: l.i64s("Admission_admittime"),
            dischtime: l.i64s("Admission_dischtime"),
            deathtime: l.multi_i64("Admission_deathtime"),
            admission_type: l.strs("Admission_admission_type"),
            admit_provider_id: l.strs("Admission_admit_provider_id"),
            admission_location: l.strs("Admission_admission_location"),
            discharge_location: l.multi_strs("Admission_discharge_location"),
            insurance: l.strs("Admission_insurance"),
            language: l.strs("Admission_language"),
            marital_status: l.multi_strs("Admission_marital_status"),
            race: l.strs("Admission_race"),
            edregtime: l.multi_i64("Admission_edregtime"),
            edouttime: l.multi_i64("Admission_edouttime"),
            hospital_expire_flag: l.i64s("Admission_hospital_expire_flag"),
        },
        icu_stay: IcuStay {
            id: l.key("IcuStay_row"),
            subject: l.ids("IcuStay_subject"),
            subject_id: l.i64s("IcuStay_subject_id"),
            hadm: l.ids("IcuStay_hadm"),
            hadm_id: l.i64s("IcuStay_hadm_id"),
            stay_id: l.i64s("IcuStay_stay_id"),
            first_careunit: l.strs("IcuStay_first_careunit"),
            last_careunit: l.strs("IcuStay_last_careunit"),
            intime: l.i64s("IcuStay_intime"),
            outtime: l.i64s("IcuStay_outtime"),
            los: l.f64s("IcuStay_los"),
        },
        diagnoses_icd: DiagnosesIcd {
            id: l.key("DiagnosesIcd_row"),
            subject: l.ids("DiagnosesIcd_subject"),
            subject_id: l.i64s("DiagnosesIcd_subject_id"),
            hadm: l.ids("DiagnosesIcd_hadm"),
            hadm_id: l.i64s("DiagnosesIcd_hadm_id"),
            seq_num: l.i64s("DiagnosesIcd_seq_num"),
            icd_code: l.strs("DiagnosesIcd_icd_code"),
            icd_version: l.i64s("DiagnosesIcd_icd_version"),
        },
        lab_event: LabEvent {
            id: l.key("LabEvent_row"),
            labevent_id: l.i64s("LabEvent_labevent_id"),
            subject: l.ids("LabEvent_subject"),
            subject_id: l.i64s("LabEvent_subject_id"),
            hadm: l.multi_ids("LabEvent_hadm"),
            hadm_id: l.multi_i64("LabEvent_hadm_id"),
            specimen_id: l.i64s("LabEvent_specimen_id"),
            itemid: l.i64s("LabEvent_itemid"),
            order_provider_id: l.multi_strs("LabEvent_order_provider_id"),
            charttime: l.i64s("LabEvent_charttime"),
            storetime: l.multi_i64("LabEvent_storetime"),
            value: l.multi_strs("LabEvent_value"),
            valuenum: harness::cols::multi_f64(l, "LabEvent_valuenum"),
            valueuom: l.multi_strs("LabEvent_valueuom"),
            ref_range_lower: harness::cols::multi_f64(l, "LabEvent_ref_range_lower"),
            ref_range_upper: harness::cols::multi_f64(l, "LabEvent_ref_range_upper"),
            flag: l.multi_strs("LabEvent_flag"),
            priority: l.multi_strs("LabEvent_priority"),
            comments: l.multi_strs("LabEvent_comments"),
        },
        microbiology_event: MicrobiologyEvent {
            id: l.key("MicrobiologyEvent_row"),
            microevent_id: l.i64s("MicrobiologyEvent_microevent_id"),
            subject: l.ids("MicrobiologyEvent_subject"),
            subject_id: l.i64s("MicrobiologyEvent_subject_id"),
            hadm: l.multi_ids("MicrobiologyEvent_hadm"),
            hadm_id: l.multi_i64("MicrobiologyEvent_hadm_id"),
            micro_specimen_id: l.i64s("MicrobiologyEvent_micro_specimen_id"),
            order_provider_id: l.multi_strs("MicrobiologyEvent_order_provider_id"),
            chartdate: l.i64s("MicrobiologyEvent_chartdate"),
            charttime: l.multi_i64("MicrobiologyEvent_charttime"),
            spec_itemid: l.i64s("MicrobiologyEvent_spec_itemid"),
            spec_type_desc: l.strs("MicrobiologyEvent_spec_type_desc"),
            test_seq: l.i64s("MicrobiologyEvent_test_seq"),
            storedate: l.multi_i64("MicrobiologyEvent_storedate"),
            storetime: l.multi_i64("MicrobiologyEvent_storetime"),
            test_itemid: l.i64s("MicrobiologyEvent_test_itemid"),
            test_name: l.strs("MicrobiologyEvent_test_name"),
            org_itemid: l.multi_i64("MicrobiologyEvent_org_itemid"),
            org_name: l.multi_strs("MicrobiologyEvent_org_name"),
            isolate_num: l.multi_i64("MicrobiologyEvent_isolate_num"),
            quantity: l.multi_strs("MicrobiologyEvent_quantity"),
            ab_itemid: l.multi_i64("MicrobiologyEvent_ab_itemid"),
            ab_name: l.multi_strs("MicrobiologyEvent_ab_name"),
            dilution_text: l.multi_strs("MicrobiologyEvent_dilution_text"),
            dilution_comparison: l.multi_strs("MicrobiologyEvent_dilution_comparison"),
            dilution_value: harness::cols::multi_f64(l, "MicrobiologyEvent_dilution_value"),
            interpretation: l.multi_strs("MicrobiologyEvent_interpretation"),
            comments: l.multi_strs("MicrobiologyEvent_comments"),
        },
        prescription: Prescription {
            id: l.key("Prescription_row"),
            subject: l.ids("Prescription_subject"),
            subject_id: l.i64s("Prescription_subject_id"),
            hadm: l.ids("Prescription_hadm"),
            hadm_id: l.i64s("Prescription_hadm_id"),
            pharmacy_id: l.i64s("Prescription_pharmacy_id"),
            poe_id: l.multi_strs("Prescription_poe_id"),
            poe_seq: l.multi_i64("Prescription_poe_seq"),
            order_provider_id: l.multi_strs("Prescription_order_provider_id"),
            starttime: l.i64s("Prescription_starttime"),
            stoptime: l.multi_i64("Prescription_stoptime"),
            drug_type: l.strs("Prescription_drug_type"),
            drug: l.strs("Prescription_drug"),
            formulary_drug_cd: l.multi_strs("Prescription_formulary_drug_cd"),
            gsn: l.multi_strs("Prescription_gsn"),
            ndc: l.multi_strs("Prescription_ndc"),
            prod_strength: l.multi_strs("Prescription_prod_strength"),
            form_rx: l.multi_strs("Prescription_form_rx"),
            dose_val_rx: l.multi_strs("Prescription_dose_val_rx"),
            dose_unit_rx: l.multi_strs("Prescription_dose_unit_rx"),
            form_val_disp: l.multi_strs("Prescription_form_val_disp"),
            form_unit_disp: l.multi_strs("Prescription_form_unit_disp"),
            doses_per_24_hrs: harness::cols::multi_f64(l, "Prescription_doses_per_24_hrs"),
            route: l.multi_strs("Prescription_route"),
        },
        service: Service {
            id: l.key("Service_row"),
            subject: l.ids("Service_subject"),
            subject_id: l.i64s("Service_subject_id"),
            hadm: l.ids("Service_hadm"),
            hadm_id: l.i64s("Service_hadm_id"),
            transfertime: l.i64s("Service_transfertime"),
            prev_service: l.multi_strs("Service_prev_service"),
            curr_service: l.strs("Service_curr_service"),
        },
        chart_event: ChartEvent {
            id: l.key("ChartEvent_row"),
            subject: l.ids("ChartEvent_subject"),
            subject_id: l.i64s("ChartEvent_subject_id"),
            hadm: l.ids("ChartEvent_hadm"),
            hadm_id: l.i64s("ChartEvent_hadm_id"),
            stay: l.ids("ChartEvent_stay"),
            stay_id: l.i64s("ChartEvent_stay_id"),
            caregiver_id: l.multi_i64("ChartEvent_caregiver_id"),
            charttime: l.i64s("ChartEvent_charttime"),
            storetime: l.multi_i64("ChartEvent_storetime"),
            itemid: l.i64s("ChartEvent_itemid"),
            value: l.strs("ChartEvent_value"),
            valuenum: harness::cols::multi_f64(l, "ChartEvent_valuenum"),
            valueuom: l.multi_strs("ChartEvent_valueuom"),
            warning: l.multi_i64("ChartEvent_warning"),
        },
        input_event: InputEvent {
            id: l.key("InputEvent_row"),
            subject: l.ids("InputEvent_subject"),
            subject_id: l.i64s("InputEvent_subject_id"),
            hadm: l.ids("InputEvent_hadm"),
            hadm_id: l.i64s("InputEvent_hadm_id"),
            stay: l.ids("InputEvent_stay"),
            stay_id: l.i64s("InputEvent_stay_id"),
            caregiver_id: l.i64s("InputEvent_caregiver_id"),
            starttime: l.i64s("InputEvent_starttime"),
            endtime: l.i64s("InputEvent_endtime"),
            storetime: l.i64s("InputEvent_storetime"),
            itemid: l.i64s("InputEvent_itemid"),
            amount: l.f64s("InputEvent_amount"),
            amountuom: l.strs("InputEvent_amountuom"),
            rate: harness::cols::multi_f64(l, "InputEvent_rate"),
            rateuom: l.multi_strs("InputEvent_rateuom"),
            orderid: l.i64s("InputEvent_orderid"),
            linkorderid: l.i64s("InputEvent_linkorderid"),
            ordercategoryname: l.strs("InputEvent_ordercategoryname"),
            secondaryordercategoryname: l.multi_strs("InputEvent_secondaryordercategoryname"),
            ordercomponenttypedescription: l.strs("InputEvent_ordercomponenttypedescription"),
            ordercategorydescription: l.strs("InputEvent_ordercategorydescription"),
            patientweight: l.f64s("InputEvent_patientweight"),
            totalamount: harness::cols::multi_f64(l, "InputEvent_totalamount"),
            totalamountuom: l.multi_strs("InputEvent_totalamountuom"),
            isopenbag: l.i64s("InputEvent_isopenbag"),
            continueinnextdept: l.i64s("InputEvent_continueinnextdept"),
            statusdescription: l.strs("InputEvent_statusdescription"),
            originalamount: l.f64s("InputEvent_originalamount"),
            originalrate: l.f64s("InputEvent_originalrate"),
        },
        output_event: OutputEvent {
            id: l.key("OutputEvent_row"),
            subject: l.ids("OutputEvent_subject"),
            subject_id: l.i64s("OutputEvent_subject_id"),
            hadm: l.ids("OutputEvent_hadm"),
            hadm_id: l.i64s("OutputEvent_hadm_id"),
            stay: l.ids("OutputEvent_stay"),
            stay_id: l.i64s("OutputEvent_stay_id"),
            caregiver_id: l.i64s("OutputEvent_caregiver_id"),
            charttime: l.i64s("OutputEvent_charttime"),
            storetime: l.i64s("OutputEvent_storetime"),
            itemid: l.i64s("OutputEvent_itemid"),
            value: l.f64s("OutputEvent_value"),
            valueuom: l.strs("OutputEvent_valueuom"),
        },
        procedure_event: ProcedureEvent {
            id: l.key("ProcedureEvent_row"),
            subject: l.ids("ProcedureEvent_subject"),
            subject_id: l.i64s("ProcedureEvent_subject_id"),
            hadm: l.ids("ProcedureEvent_hadm"),
            hadm_id: l.i64s("ProcedureEvent_hadm_id"),
            stay: l.ids("ProcedureEvent_stay"),
            stay_id: l.i64s("ProcedureEvent_stay_id"),
            caregiver_id: l.multi_i64("ProcedureEvent_caregiver_id"),
            starttime: l.i64s("ProcedureEvent_starttime"),
            endtime: l.i64s("ProcedureEvent_endtime"),
            storetime: l.i64s("ProcedureEvent_storetime"),
            itemid: l.i64s("ProcedureEvent_itemid"),
            value: l.f64s("ProcedureEvent_value"),
            valueuom: l.strs("ProcedureEvent_valueuom"),
            location: l.multi_strs("ProcedureEvent_location"),
            locationcategory: l.multi_strs("ProcedureEvent_locationcategory"),
            orderid: l.i64s("ProcedureEvent_orderid"),
            linkorderid: l.i64s("ProcedureEvent_linkorderid"),
            ordercategoryname: l.strs("ProcedureEvent_ordercategoryname"),
            ordercategorydescription: l.strs("ProcedureEvent_ordercategorydescription"),
            patientweight: l.f64s("ProcedureEvent_patientweight"),
            isopenbag: l.i64s("ProcedureEvent_isopenbag"),
            continueinnextdept: l.i64s("ProcedureEvent_continueinnextdept"),
            statusdescription: l.strs("ProcedureEvent_statusdescription"),
            originalamount: l.f64s("ProcedureEvent_originalamount"),
            originalrate: l.f64s("ProcedureEvent_originalrate"),
        },
    }
}

pub fn load(dir: &Path) -> Db {
    build(&mut Loader::new(dir))
}

