#![allow(dead_code)]

use harness::time::{Date, Ts};
use prela::engine::{Id, IntoQuery};
use prela::loader::{Col, Key, Loader, Set, Str};
use std::path::Path;

#[derive(IntoQuery)]
pub struct Person {
    #[primary_key]
    pub id: Key<Self>,
    pub person_id: Col<Self, i64>,
    pub gender_concept: Col<Self, Id<Concept>>,
    pub gender_concept_id: Col<Self, i64>,
    pub year_of_birth: Col<Self, i64>,
    pub month_of_birth: Col<Self, i64>,
    pub day_of_birth: Col<Self, i64>,
    pub birth_datetime: Col<Self, Ts>,
    pub race_concept: Set<Self, Id<Concept>>,
    pub race_concept_id: Col<Self, i64>,
    pub ethnicity_concept: Set<Self, Id<Concept>>,
    pub ethnicity_concept_id: Col<Self, i64>,
    pub location_id: Set<Self, Str>,
    pub provider_id: Set<Self, Str>,
    pub care_site_id: Set<Self, Str>,
    pub person_source_value: Col<Self, Str>,
    pub gender_source_value: Col<Self, Str>,
    pub gender_source_concept: Col<Self, Id<Concept>>,
    pub gender_source_concept_id: Col<Self, i64>,
    pub race_source_value: Col<Self, Str>,
    pub race_source_concept: Col<Self, Id<Concept>>,
    pub race_source_concept_id: Col<Self, i64>,
    pub ethnicity_source_value: Col<Self, Str>,
    pub ethnicity_source_concept: Col<Self, Id<Concept>>,
    pub ethnicity_source_concept_id: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct Concept {
    #[primary_key]
    pub id: Key<Self>,
    pub concept_id: Col<Self, i64>,
    pub concept_name: Col<Self, Str>,
    pub domain_id: Col<Self, Str>,
    pub vocabulary_id: Col<Self, Str>,
    pub concept_class_id: Col<Self, Str>,
    pub standard_concept: Set<Self, Str>,
    pub concept_code: Col<Self, Str>,
    pub valid_start_date: Col<Self, Date>,
    pub valid_end_date: Col<Self, Date>,
    pub invalid_reason: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct VisitOccurrence {
    #[primary_key]
    pub id: Key<Self>,
    pub visit_occurrence_id: Col<Self, i64>,
    pub person: Col<Self, Id<Person>>,
    pub person_id: Col<Self, i64>,
    pub visit_concept: Col<Self, Id<Concept>>,
    pub visit_concept_id: Col<Self, i64>,
    pub visit_start_date: Col<Self, Date>,
    pub visit_start_datetime: Col<Self, Ts>,
    pub visit_end_date: Col<Self, Date>,
    pub visit_end_datetime: Col<Self, Ts>,
    pub visit_type_concept: Set<Self, Id<Concept>>,
    pub visit_type_concept_id: Col<Self, i64>,
    pub provider_id: Set<Self, Str>,
    pub care_site_id: Set<Self, Str>,
    pub visit_source_value: Col<Self, Str>,
    pub visit_source_concept: Col<Self, Id<Concept>>,
    pub visit_source_concept_id: Col<Self, i64>,
    pub admitting_source_concept: Col<Self, Id<Concept>>,
    pub admitting_source_concept_id: Col<Self, i64>,
    pub admitting_source_value: Set<Self, Str>,
    pub discharge_to_concept: Col<Self, Id<Concept>>,
    pub discharge_to_concept_id: Col<Self, i64>,
    pub discharge_to_source_value: Set<Self, Str>,
    pub preceding_visit_occurrence_id: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct ObservationPeriod {
    #[primary_key]
    pub id: Key<Self>,
    pub observation_period_id: Col<Self, i64>,
    pub person: Set<Self, Id<Person>>,
    pub person_id: Col<Self, i64>,
    pub observation_period_start_date: Col<Self, Date>,
    pub observation_period_end_date: Col<Self, Date>,
    pub period_type_concept: Set<Self, Id<Concept>>,
    pub period_type_concept_id: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct ConceptAncestor {
    #[primary_key]
    pub id: Key<Self>,
    pub ancestor_concept: Set<Self, Id<Concept>>,
    pub ancestor_concept_id: Col<Self, i64>,
    pub descendant_concept: Col<Self, Id<Concept>>,
    pub descendant_concept_id: Col<Self, i64>,
    pub min_levels_of_separation: Col<Self, i64>,
    pub max_levels_of_separation: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct ConditionOccurrence {
    #[primary_key]
    pub id: Key<Self>,
    pub condition_occurrence_id: Col<Self, i64>,
    pub person: Col<Self, Id<Person>>,
    pub person_id: Col<Self, i64>,
    pub condition_concept: Col<Self, Id<Concept>>,
    pub condition_concept_id: Col<Self, i64>,
    pub condition_start_date: Col<Self, Date>,
    pub condition_start_datetime: Col<Self, Ts>,
    pub condition_end_date: Set<Self, Date>,
    pub condition_end_datetime: Set<Self, Ts>,
    pub condition_type_concept: Set<Self, Id<Concept>>,
    pub condition_type_concept_id: Col<Self, i64>,
    pub stop_reason: Set<Self, Str>,
    pub provider_id: Set<Self, Str>,
    pub visit_occurrence: Set<Self, Id<VisitOccurrence>>,
    pub visit_occurrence_id: Set<Self, i64>,
    pub visit_detail_id: Col<Self, i64>,
    pub condition_source_value: Col<Self, Str>,
    pub condition_source_concept: Set<Self, Id<Concept>>,
    pub condition_source_concept_id: Col<Self, i64>,
    pub condition_status_source_value: Set<Self, Str>,
    pub condition_status_concept: Col<Self, Id<Concept>>,
    pub condition_status_concept_id: Col<Self, i64>,
}

#[derive(IntoQuery)]
pub struct DrugExposure {
    #[primary_key]
    pub id: Key<Self>,
    pub drug_exposure_id: Col<Self, i64>,
    pub person: Col<Self, Id<Person>>,
    pub person_id: Col<Self, i64>,
    pub drug_concept: Col<Self, Id<Concept>>,
    pub drug_concept_id: Col<Self, i64>,
    pub drug_exposure_start_date: Col<Self, Date>,
    pub drug_exposure_start_datetime: Col<Self, Ts>,
    pub drug_exposure_end_date: Col<Self, Date>,
    pub drug_exposure_end_datetime: Col<Self, Ts>,
    pub verbatim_end_date: Set<Self, Date>,
    pub drug_type_concept: Set<Self, Id<Concept>>,
    pub drug_type_concept_id: Col<Self, i64>,
    pub stop_reason: Set<Self, Str>,
    pub refills: Col<Self, i64>,
    pub quantity: Col<Self, i64>,
    pub days_supply: Col<Self, i64>,
    pub sig: Set<Self, Str>,
    pub route_concept: Col<Self, Id<Concept>>,
    pub route_concept_id: Col<Self, i64>,
    pub lot_number: Col<Self, i64>,
    pub provider_id: Col<Self, i64>,
    pub visit_occurrence: Set<Self, Id<VisitOccurrence>>,
    pub visit_occurrence_id: Set<Self, i64>,
    pub visit_detail_id: Col<Self, i64>,
    pub drug_source_value: Col<Self, Str>,
    pub drug_source_concept: Set<Self, Id<Concept>>,
    pub drug_source_concept_id: Col<Self, i64>,
    pub route_source_value: Set<Self, Str>,
    pub dose_unit_source_value: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct ProcedureOccurrence {
    #[primary_key]
    pub id: Key<Self>,
    pub procedure_occurrence_id: Col<Self, i64>,
    pub person: Col<Self, Id<Person>>,
    pub person_id: Col<Self, i64>,
    pub procedure_concept: Col<Self, Id<Concept>>,
    pub procedure_concept_id: Col<Self, i64>,
    pub procedure_date: Col<Self, Date>,
    pub procedure_datetime: Col<Self, Ts>,
    pub procedure_type_concept: Set<Self, Id<Concept>>,
    pub procedure_type_concept_id: Col<Self, i64>,
    pub modifier_concept: Col<Self, Id<Concept>>,
    pub modifier_concept_id: Col<Self, i64>,
    pub quantity: Set<Self, Str>,
    pub provider_id: Set<Self, Str>,
    pub visit_occurrence: Set<Self, Id<VisitOccurrence>>,
    pub visit_occurrence_id: Set<Self, i64>,
    pub visit_detail_id: Col<Self, i64>,
    pub procedure_source_value: Col<Self, i64>,
    pub procedure_source_concept: Col<Self, Id<Concept>>,
    pub procedure_source_concept_id: Col<Self, i64>,
    pub modifier_source_value: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct Observation {
    #[primary_key]
    pub id: Key<Self>,
    pub observation_id: Col<Self, i64>,
    pub person: Col<Self, Id<Person>>,
    pub person_id: Col<Self, i64>,
    pub observation_concept: Col<Self, Id<Concept>>,
    pub observation_concept_id: Col<Self, i64>,
    pub observation_date: Col<Self, Date>,
    pub observation_datetime: Col<Self, Ts>,
    pub observation_type_concept: Set<Self, Id<Concept>>,
    pub observation_type_concept_id: Col<Self, i64>,
    pub value_as_number: Set<Self, Str>,
    pub value_as_string: Set<Self, Str>,
    pub value_as_concept: Col<Self, Id<Concept>>,
    pub value_as_concept_id: Col<Self, i64>,
    pub qualifier_concept: Col<Self, Id<Concept>>,
    pub qualifier_concept_id: Col<Self, i64>,
    pub unit_concept: Col<Self, Id<Concept>>,
    pub unit_concept_id: Col<Self, i64>,
    pub provider_id: Col<Self, i64>,
    pub visit_occurrence: Set<Self, Id<VisitOccurrence>>,
    pub visit_occurrence_id: Col<Self, i64>,
    pub visit_detail_id: Col<Self, i64>,
    pub observation_source_value: Col<Self, i64>,
    pub observation_source_concept: Col<Self, Id<Concept>>,
    pub observation_source_concept_id: Col<Self, i64>,
    pub unit_source_value: Set<Self, Str>,
    pub qualifier_source_value: Set<Self, Str>,
}

#[derive(IntoQuery)]
pub struct Measurement {
    #[primary_key]
    pub id: Key<Self>,
    pub measurement_id: Col<Self, i64>,
    pub person: Col<Self, Id<Person>>,
    pub person_id: Col<Self, i64>,
    pub measurement_concept: Col<Self, Id<Concept>>,
    pub measurement_concept_id: Col<Self, i64>,
    pub measurement_date: Col<Self, Date>,
    pub measurement_datetime: Col<Self, Ts>,
    pub measurement_time: Col<Self, Date>,
    pub measurement_type_concept: Set<Self, Id<Concept>>,
    pub measurement_type_concept_id: Col<Self, i64>,
    pub operator_concept: Col<Self, Id<Concept>>,
    pub operator_concept_id: Col<Self, i64>,
    pub value_as_number: Set<Self, Str>,
    pub value_as_concept: Col<Self, Id<Concept>>,
    pub value_as_concept_id: Col<Self, i64>,
    pub unit_concept: Col<Self, Id<Concept>>,
    pub unit_concept_id: Col<Self, i64>,
    pub range_low: Set<Self, Str>,
    pub range_high: Set<Self, Str>,
    pub provider_id: Col<Self, i64>,
    pub visit_occurrence: Set<Self, Id<VisitOccurrence>>,
    pub visit_occurrence_id: Col<Self, i64>,
    pub visit_detail_id: Col<Self, i64>,
    pub measurement_source_value: Col<Self, Str>,
    pub measurement_source_concept: Col<Self, Id<Concept>>,
    pub measurement_source_concept_id: Col<Self, i64>,
    pub unit_source_value: Set<Self, Str>,
    pub value_source_value: Set<Self, Str>,
}

pub struct Db {
    pub person: Person,
    pub concept: Concept,
    pub visit_occurrence: VisitOccurrence,
    pub observation_period: ObservationPeriod,
    pub concept_ancestor: ConceptAncestor,
    pub condition_occurrence: ConditionOccurrence,
    pub drug_exposure: DrugExposure,
    pub procedure_occurrence: ProcedureOccurrence,
    pub observation: Observation,
    pub measurement: Measurement,
}

fn build(l: &mut Loader) -> Db {
    Db {
        person: Person {
            id: l.key("Person_row"),
            person_id: l.i64s("Person_person_id"),
            gender_concept: l.ids("Person_gender_concept"),
            gender_concept_id: l.i64s("Person_gender_concept_id"),
            year_of_birth: l.i64s("Person_year_of_birth"),
            month_of_birth: l.i64s("Person_month_of_birth"),
            day_of_birth: l.i64s("Person_day_of_birth"),
            birth_datetime: l.i64s("Person_birth_datetime"),
            race_concept: l.multi_ids("Person_race_concept"),
            race_concept_id: l.i64s("Person_race_concept_id"),
            ethnicity_concept: l.multi_ids("Person_ethnicity_concept"),
            ethnicity_concept_id: l.i64s("Person_ethnicity_concept_id"),
            location_id: l.multi_strs("Person_location_id"),
            provider_id: l.multi_strs("Person_provider_id"),
            care_site_id: l.multi_strs("Person_care_site_id"),
            person_source_value: l.strs("Person_person_source_value"),
            gender_source_value: l.strs("Person_gender_source_value"),
            gender_source_concept: l.ids("Person_gender_source_concept"),
            gender_source_concept_id: l.i64s("Person_gender_source_concept_id"),
            race_source_value: l.strs("Person_race_source_value"),
            race_source_concept: l.ids("Person_race_source_concept"),
            race_source_concept_id: l.i64s("Person_race_source_concept_id"),
            ethnicity_source_value: l.strs("Person_ethnicity_source_value"),
            ethnicity_source_concept: l.ids("Person_ethnicity_source_concept"),
            ethnicity_source_concept_id: l.i64s("Person_ethnicity_source_concept_id"),
        },
        concept: Concept {
            id: l.key("Concept_row"),
            concept_id: l.i64s("Concept_concept_id"),
            concept_name: l.strs("Concept_concept_name"),
            domain_id: l.strs("Concept_domain_id"),
            vocabulary_id: l.strs("Concept_vocabulary_id"),
            concept_class_id: l.strs("Concept_concept_class_id"),
            standard_concept: l.multi_strs("Concept_standard_concept"),
            concept_code: l.strs("Concept_concept_code"),
            valid_start_date: l.i64s("Concept_valid_start_date"),
            valid_end_date: l.i64s("Concept_valid_end_date"),
            invalid_reason: l.multi_strs("Concept_invalid_reason"),
        },
        visit_occurrence: VisitOccurrence {
            id: l.key("VisitOccurrence_row"),
            visit_occurrence_id: l.i64s("VisitOccurrence_visit_occurrence_id"),
            person: l.ids("VisitOccurrence_person"),
            person_id: l.i64s("VisitOccurrence_person_id"),
            visit_concept: l.ids("VisitOccurrence_visit_concept"),
            visit_concept_id: l.i64s("VisitOccurrence_visit_concept_id"),
            visit_start_date: l.i64s("VisitOccurrence_visit_start_date"),
            visit_start_datetime: l.i64s("VisitOccurrence_visit_start_datetime"),
            visit_end_date: l.i64s("VisitOccurrence_visit_end_date"),
            visit_end_datetime: l.i64s("VisitOccurrence_visit_end_datetime"),
            visit_type_concept: l.multi_ids("VisitOccurrence_visit_type_concept"),
            visit_type_concept_id: l.i64s("VisitOccurrence_visit_type_concept_id"),
            provider_id: l.multi_strs("VisitOccurrence_provider_id"),
            care_site_id: l.multi_strs("VisitOccurrence_care_site_id"),
            visit_source_value: l.strs("VisitOccurrence_visit_source_value"),
            visit_source_concept: l.ids("VisitOccurrence_visit_source_concept"),
            visit_source_concept_id: l.i64s("VisitOccurrence_visit_source_concept_id"),
            admitting_source_concept: l.ids("VisitOccurrence_admitting_source_concept"),
            admitting_source_concept_id: l.i64s("VisitOccurrence_admitting_source_concept_id"),
            admitting_source_value: l.multi_strs("VisitOccurrence_admitting_source_value"),
            discharge_to_concept: l.ids("VisitOccurrence_discharge_to_concept"),
            discharge_to_concept_id: l.i64s("VisitOccurrence_discharge_to_concept_id"),
            discharge_to_source_value: l.multi_strs("VisitOccurrence_discharge_to_source_value"),
            preceding_visit_occurrence_id: l.i64s("VisitOccurrence_preceding_visit_occurrence_id"),
        },
        observation_period: ObservationPeriod {
            id: l.key("ObservationPeriod_row"),
            observation_period_id: l.i64s("ObservationPeriod_observation_period_id"),
            person: l.multi_ids("ObservationPeriod_person"),
            person_id: l.i64s("ObservationPeriod_person_id"),
            observation_period_start_date: l.i64s("ObservationPeriod_observation_period_start_date"),
            observation_period_end_date: l.i64s("ObservationPeriod_observation_period_end_date"),
            period_type_concept: l.multi_ids("ObservationPeriod_period_type_concept"),
            period_type_concept_id: l.i64s("ObservationPeriod_period_type_concept_id"),
        },
        concept_ancestor: ConceptAncestor {
            id: l.key("ConceptAncestor_row"),
            ancestor_concept: l.multi_ids("ConceptAncestor_ancestor_concept"),
            ancestor_concept_id: l.i64s("ConceptAncestor_ancestor_concept_id"),
            descendant_concept: l.ids("ConceptAncestor_descendant_concept"),
            descendant_concept_id: l.i64s("ConceptAncestor_descendant_concept_id"),
            min_levels_of_separation: l.i64s("ConceptAncestor_min_levels_of_separation"),
            max_levels_of_separation: l.i64s("ConceptAncestor_max_levels_of_separation"),
        },
        condition_occurrence: ConditionOccurrence {
            id: l.key("ConditionOccurrence_row"),
            condition_occurrence_id: l.i64s("ConditionOccurrence_condition_occurrence_id"),
            person: l.ids("ConditionOccurrence_person"),
            person_id: l.i64s("ConditionOccurrence_person_id"),
            condition_concept: l.ids("ConditionOccurrence_condition_concept"),
            condition_concept_id: l.i64s("ConditionOccurrence_condition_concept_id"),
            condition_start_date: l.i64s("ConditionOccurrence_condition_start_date"),
            condition_start_datetime: l.i64s("ConditionOccurrence_condition_start_datetime"),
            condition_end_date: l.multi_i64("ConditionOccurrence_condition_end_date"),
            condition_end_datetime: l.multi_i64("ConditionOccurrence_condition_end_datetime"),
            condition_type_concept: l.multi_ids("ConditionOccurrence_condition_type_concept"),
            condition_type_concept_id: l.i64s("ConditionOccurrence_condition_type_concept_id"),
            stop_reason: l.multi_strs("ConditionOccurrence_stop_reason"),
            provider_id: l.multi_strs("ConditionOccurrence_provider_id"),
            visit_occurrence: l.multi_ids("ConditionOccurrence_visit_occurrence"),
            visit_occurrence_id: l.multi_i64("ConditionOccurrence_visit_occurrence_id"),
            visit_detail_id: l.i64s("ConditionOccurrence_visit_detail_id"),
            condition_source_value: l.strs("ConditionOccurrence_condition_source_value"),
            condition_source_concept: l.multi_ids("ConditionOccurrence_condition_source_concept"),
            condition_source_concept_id: l.i64s("ConditionOccurrence_condition_source_concept_id"),
            condition_status_source_value: l.multi_strs("ConditionOccurrence_condition_status_source_value"),
            condition_status_concept: l.ids("ConditionOccurrence_condition_status_concept"),
            condition_status_concept_id: l.i64s("ConditionOccurrence_condition_status_concept_id"),
        },
        drug_exposure: DrugExposure {
            id: l.key("DrugExposure_row"),
            drug_exposure_id: l.i64s("DrugExposure_drug_exposure_id"),
            person: l.ids("DrugExposure_person"),
            person_id: l.i64s("DrugExposure_person_id"),
            drug_concept: l.ids("DrugExposure_drug_concept"),
            drug_concept_id: l.i64s("DrugExposure_drug_concept_id"),
            drug_exposure_start_date: l.i64s("DrugExposure_drug_exposure_start_date"),
            drug_exposure_start_datetime: l.i64s("DrugExposure_drug_exposure_start_datetime"),
            drug_exposure_end_date: l.i64s("DrugExposure_drug_exposure_end_date"),
            drug_exposure_end_datetime: l.i64s("DrugExposure_drug_exposure_end_datetime"),
            verbatim_end_date: l.multi_i64("DrugExposure_verbatim_end_date"),
            drug_type_concept: l.multi_ids("DrugExposure_drug_type_concept"),
            drug_type_concept_id: l.i64s("DrugExposure_drug_type_concept_id"),
            stop_reason: l.multi_strs("DrugExposure_stop_reason"),
            refills: l.i64s("DrugExposure_refills"),
            quantity: l.i64s("DrugExposure_quantity"),
            days_supply: l.i64s("DrugExposure_days_supply"),
            sig: l.multi_strs("DrugExposure_sig"),
            route_concept: l.ids("DrugExposure_route_concept"),
            route_concept_id: l.i64s("DrugExposure_route_concept_id"),
            lot_number: l.i64s("DrugExposure_lot_number"),
            provider_id: l.i64s("DrugExposure_provider_id"),
            visit_occurrence: l.multi_ids("DrugExposure_visit_occurrence"),
            visit_occurrence_id: l.multi_i64("DrugExposure_visit_occurrence_id"),
            visit_detail_id: l.i64s("DrugExposure_visit_detail_id"),
            drug_source_value: l.strs("DrugExposure_drug_source_value"),
            drug_source_concept: l.multi_ids("DrugExposure_drug_source_concept"),
            drug_source_concept_id: l.i64s("DrugExposure_drug_source_concept_id"),
            route_source_value: l.multi_strs("DrugExposure_route_source_value"),
            dose_unit_source_value: l.multi_strs("DrugExposure_dose_unit_source_value"),
        },
        procedure_occurrence: ProcedureOccurrence {
            id: l.key("ProcedureOccurrence_row"),
            procedure_occurrence_id: l.i64s("ProcedureOccurrence_procedure_occurrence_id"),
            person: l.ids("ProcedureOccurrence_person"),
            person_id: l.i64s("ProcedureOccurrence_person_id"),
            procedure_concept: l.ids("ProcedureOccurrence_procedure_concept"),
            procedure_concept_id: l.i64s("ProcedureOccurrence_procedure_concept_id"),
            procedure_date: l.i64s("ProcedureOccurrence_procedure_date"),
            procedure_datetime: l.i64s("ProcedureOccurrence_procedure_datetime"),
            procedure_type_concept: l.multi_ids("ProcedureOccurrence_procedure_type_concept"),
            procedure_type_concept_id: l.i64s("ProcedureOccurrence_procedure_type_concept_id"),
            modifier_concept: l.ids("ProcedureOccurrence_modifier_concept"),
            modifier_concept_id: l.i64s("ProcedureOccurrence_modifier_concept_id"),
            quantity: l.multi_strs("ProcedureOccurrence_quantity"),
            provider_id: l.multi_strs("ProcedureOccurrence_provider_id"),
            visit_occurrence: l.multi_ids("ProcedureOccurrence_visit_occurrence"),
            visit_occurrence_id: l.multi_i64("ProcedureOccurrence_visit_occurrence_id"),
            visit_detail_id: l.i64s("ProcedureOccurrence_visit_detail_id"),
            procedure_source_value: l.i64s("ProcedureOccurrence_procedure_source_value"),
            procedure_source_concept: l.ids("ProcedureOccurrence_procedure_source_concept"),
            procedure_source_concept_id: l.i64s("ProcedureOccurrence_procedure_source_concept_id"),
            modifier_source_value: l.multi_strs("ProcedureOccurrence_modifier_source_value"),
        },
        observation: Observation {
            id: l.key("Observation_row"),
            observation_id: l.i64s("Observation_observation_id"),
            person: l.ids("Observation_person"),
            person_id: l.i64s("Observation_person_id"),
            observation_concept: l.ids("Observation_observation_concept"),
            observation_concept_id: l.i64s("Observation_observation_concept_id"),
            observation_date: l.i64s("Observation_observation_date"),
            observation_datetime: l.i64s("Observation_observation_datetime"),
            observation_type_concept: l.multi_ids("Observation_observation_type_concept"),
            observation_type_concept_id: l.i64s("Observation_observation_type_concept_id"),
            value_as_number: l.multi_strs("Observation_value_as_number"),
            value_as_string: l.multi_strs("Observation_value_as_string"),
            value_as_concept: l.ids("Observation_value_as_concept"),
            value_as_concept_id: l.i64s("Observation_value_as_concept_id"),
            qualifier_concept: l.ids("Observation_qualifier_concept"),
            qualifier_concept_id: l.i64s("Observation_qualifier_concept_id"),
            unit_concept: l.ids("Observation_unit_concept"),
            unit_concept_id: l.i64s("Observation_unit_concept_id"),
            provider_id: l.i64s("Observation_provider_id"),
            visit_occurrence: l.multi_ids("Observation_visit_occurrence"),
            visit_occurrence_id: l.i64s("Observation_visit_occurrence_id"),
            visit_detail_id: l.i64s("Observation_visit_detail_id"),
            observation_source_value: l.i64s("Observation_observation_source_value"),
            observation_source_concept: l.ids("Observation_observation_source_concept"),
            observation_source_concept_id: l.i64s("Observation_observation_source_concept_id"),
            unit_source_value: l.multi_strs("Observation_unit_source_value"),
            qualifier_source_value: l.multi_strs("Observation_qualifier_source_value"),
        },
        measurement: Measurement {
            id: l.key("Measurement_row"),
            measurement_id: l.i64s("Measurement_measurement_id"),
            person: l.ids("Measurement_person"),
            person_id: l.i64s("Measurement_person_id"),
            measurement_concept: l.ids("Measurement_measurement_concept"),
            measurement_concept_id: l.i64s("Measurement_measurement_concept_id"),
            measurement_date: l.i64s("Measurement_measurement_date"),
            measurement_datetime: l.i64s("Measurement_measurement_datetime"),
            measurement_time: l.i64s("Measurement_measurement_time"),
            measurement_type_concept: l.multi_ids("Measurement_measurement_type_concept"),
            measurement_type_concept_id: l.i64s("Measurement_measurement_type_concept_id"),
            operator_concept: l.ids("Measurement_operator_concept"),
            operator_concept_id: l.i64s("Measurement_operator_concept_id"),
            value_as_number: l.multi_strs("Measurement_value_as_number"),
            value_as_concept: l.ids("Measurement_value_as_concept"),
            value_as_concept_id: l.i64s("Measurement_value_as_concept_id"),
            unit_concept: l.ids("Measurement_unit_concept"),
            unit_concept_id: l.i64s("Measurement_unit_concept_id"),
            range_low: l.multi_strs("Measurement_range_low"),
            range_high: l.multi_strs("Measurement_range_high"),
            provider_id: l.i64s("Measurement_provider_id"),
            visit_occurrence: l.multi_ids("Measurement_visit_occurrence"),
            visit_occurrence_id: l.i64s("Measurement_visit_occurrence_id"),
            visit_detail_id: l.i64s("Measurement_visit_detail_id"),
            measurement_source_value: l.strs("Measurement_measurement_source_value"),
            measurement_source_concept: l.ids("Measurement_measurement_source_concept"),
            measurement_source_concept_id: l.i64s("Measurement_measurement_source_concept_id"),
            unit_source_value: l.multi_strs("Measurement_unit_source_value"),
            value_source_value: l.multi_strs("Measurement_value_source_value"),
        },
    }
}

pub fn load(dir: &Path) -> Db {
    build(&mut Loader::new(dir))
}

