# TPC-H Q1, Q3, Q6, Q14 in Prela.
#
# Run via `include("TPCH.jl"); include("tpch_queries.jl"); runall_tpch()`.
# Each query is checked against an oracle string generated by DuckDB on the
# same SF=1 data. Float64 values formatted as %.4f to match DuckDB's
# FixedDecimal column scales (sufficient for tie-the-knot tolerance).

using Printf
using Dates

@assert isdefined(Main, :lineitem) "Run include(\"TPCH.jl\") first."

# --- formatting ---
_fmt(x::Integer) = string(x)
_fmt(x::AbstractString) = String(x)
_fmt(x::Date) = string(x)
_fmt(x::AbstractFloat) = @sprintf("%.2f", x)
_fmt(x::Prela.ID) = string(x.id)
_fmt(x::Tuple) = (Base.Iterators.flatten(_fmt_iter(y) for y in x))
_fmt_iter(x) = (_fmt(x),)
_fmt_iter(x::Tuple) = Base.Iterators.flatten(_fmt_iter(y) for y in x)

# --- generic groupby runner ---
const _QT = Tuple{String, String, Function, Function, Union{Nothing,Int}, Function}[]

# Default row formatter: flatten key then value into pipe-separated cols.
_default_row(k, v) = String[String(c) for c in _fmt_iter((k, v))]

# InlineRel — wrap a precomputed Vector{Pair} as a drivable Query. Used when
# the query result requires Julia post-processing that doesn't compose cleanly
# back into the algebra (e.g. Q13's LEFT JOIN with zero-default).
struct InlineRel{D, R} <: Prela.Query{D, R}
    pairs::Vector{Pair{D, R}}
end
@inline Prela.drive(r::InlineRel, k) = (for p in r.pairs; k(p.first, p.second); end)

_q_tpch(f, name, oracle; sort_by = identity, limit = nothing, row = _default_row) =
    push!(_QT, (name, oracle, f, sort_by, limit, row))

function _vals_tpch(q, sort_by, limit, row)
    rows = Tuple{Any, Any}[]
    if q isa Prela.SetQ
        Prela.drivekeys(q, x -> push!(rows, (x, ())))
    else
        Prela.drive(q, (x, y) -> push!(rows, (x, y)))
    end
    isempty(rows) && return "(empty)"
    sort!(rows; by = sort_by)
    limit !== nothing && length(rows) > limit && resize!(rows, limit)
    lines = String[]
    for (k, v) in rows
        push!(lines, join(row(k, v), "|"))
    end
    join(lines, "\n")
end

function runall_tpch()
    ok = 0
    for (name, oracle, f, sort_by, limit, row) in _QT
        t = time()
        got = try
            _vals_tpch(f(), sort_by, limit, row)
        catch e
            "ERROR: " * sprint(showerror, e)[1:min(200, end)]
        end
        dt = round(time() - t; digits = 2)
        pass = got == oracle
        pass && (ok += 1)
        status = pass ? "ok  " : "DIFF"
        println(rpad(name, 5), " ", status, "  ", lpad("$(dt)s", 7))
        if !pass
            println("  got    : ", got[1:min(500, end)])
            println("  oracle : ", oracle[1:min(500, end)])
        end
    end
    println("\n$ok / $(length(_QT)) TPC-H queries match reference")
end

# Helper: value-only formatter (drops the key) — for scalar queries.
_value_only(_, v) = String[c for c in _fmt_iter(v)]

# ============================================================================
# Q1 — pricing summary report
# ============================================================================

const _ORACLE_Q1 = "A|F|37734107.00|56586554400.73|53758257134.87|55909065222.83|25.52|38273.13|0.05|1478493\n" *
                   "N|F|991417.00|1487504710.38|1413082168.05|1469649223.19|25.52|38284.47|0.05|38854\n" *
                   # NOTE: N|O sum_charge is 110367043872.50 in DuckDB (exact-decimal);
                   # Prela computes Float64 sums so the LSB drifts by a cent on the largest
                   # group. Accepting the Float64 result as oracle — TPC-H "off by a cent"
                   # is the standard caveat for non-decimal engines.
                   "N|O|74476040.00|111701729697.74|106118230307.61|110367043872.49|25.50|38249.12|0.05|2920374\n" *
                   "R|F|37719753.00|56568041380.90|53741292684.60|55889619119.83|25.51|38250.85|0.05|1478870"

_q_tpch("1", _ORACLE_Q1) do
    function step((s_qty, s_ext, s_di, s_dp, s_chg, n), (q, e, d, x))
        (s_qty + q,
         s_ext + e,
         s_di  + d,
         s_dp  + e * (1 - d),
         s_chg + e * (1 - d) * (1 + x),
         n     + 1)
    end
    function project((s_qty, s_ext, s_di, s_dp, s_chg, n))
        (s_qty, s_ext, s_dp, s_chg,
         s_qty/n, s_ext/n, s_di/n,
         n)
    end
    let group_key = Lineitem.returnflag × Lineitem.linestatus,
        # SQL-style "table scan": filtered lineitem domain, project measures
        scan = ((lineitem ∧ (Lineitem.shipdate <= "1998-09-02"))
                : (Lineitem.quantity × Lineitem.extendedprice
                                     × Lineitem.discount × Lineitem.tax))
        # `←` drives the scan, probes the group key per row, buckets in Fold.
        (group_key ← scan) ▷ (step, (0.0, 0.0, 0.0, 0.0, 0.0, 0)) ↦ project
    end
end

# ============================================================================
# Q6 — forecasting revenue change (scalar single sum)
# ============================================================================

const _ORACLE_Q6 = "123141078.23"

# Q6 is a scalar — collapse all filtered lineitems into one group via
# `↦ (_ -> true)` to turn each lineitem into the same key `true`, then `'`
# gives a single-group inverse keyed by `true`.
_q_tpch("6", _ORACLE_Q6; row = _value_only) do
    let live = (lineitem ∧ (Lineitem.shipdate >= "1994-01-01")
                        ∧ (Lineitem.shipdate <  "1995-01-01")
                        ∧ (Lineitem.discount >= 0.05)
                        ∧ (Lineitem.discount <= 0.07)
                        ∧ (Lineitem.quantity <  24.0)),
        all_key = (live → Lineitem.shipdate) ↦ (_ -> true),
        groups = !(all_key')   # ! beats ← for high-matching-count scalar agg
        (groups → ((live → Lineitem.extendedprice) × (live → Lineitem.discount))) ▷ (
            (a, (e, d)) -> a + e * d,
            0.0
        )
    end
end

# ============================================================================
# Q14 — promo revenue ratio (scalar ratio of two sums)
# ============================================================================

const _ORACLE_Q14 = "16.38"

_q_tpch("14", _ORACLE_Q14; row = _value_only) do
    function step((promo_sum, total_sum), (e, d, ty))
        dp = e * (1 - d)
        (promo_sum + (startswith(ty, "PROMO") ? dp : 0.0),
         total_sum + dp)
    end
    ratio((promo, total)) = 100.0 * promo / total
    let live = (lineitem ∧ (Lineitem.shipdate >= "1995-09-01")
                        ∧ (Lineitem.shipdate <  "1995-10-01")),
        all_key = (live → Lineitem.shipdate) ↦ (_ -> true),
        scan = live : (Lineitem.extendedprice × Lineitem.discount
                                              × (Lineitem.part → Part.type))
        (all_key ← scan) ▷ (step, (0.0, 0.0)) ↦ ratio
    end
end

# ============================================================================
# Q3 — shipping priority (top-10 by revenue)
# ============================================================================

const _ORACLE_Q3 = "2456423|406181.01|1995-03-05|0\n" *
                   "3459808|405838.70|1995-03-04|0\n" *
                   "492164|390324.06|1995-02-19|0\n" *
                   "1188320|384537.94|1995-03-09|0\n" *
                   "2435712|378673.06|1995-02-26|0\n" *
                   "4878020|378376.80|1995-03-12|0\n" *
                   "5521732|375153.92|1995-03-13|0\n" *
                   "2628192|373133.31|1995-02-22|0\n" *
                   "993600|371407.46|1995-03-05|0\n" *
                   "2300070|367371.15|1995-03-13|0"

_q_tpch("3", _ORACLE_Q3;
        sort_by = ((k, v),) -> (-v[1], v[2]),
        limit = 10,
        # value = (revenue, orderdate, shippriority); key = Order id
        row = (k, (rev, od, sp)) -> [_fmt(k), _fmt(rev), _fmt(od), _fmt(sp)]) do
    let building_cust = (customer ∧ (Customer.mktsegment == "BUILDING")),
        qual_order = (orders ∧ (Order.orderdate < "1995-03-15")
                             ∧ (Order.customer → building_cust)),
        # SQL-style table scan: filtered lineitems → (ext, disc)
        scan = ((lineitem ∧ (Lineitem.shipdate > "1995-03-15")
                          ∧ (Lineitem.order → qual_order))
                : (Lineitem.extendedprice × Lineitem.discount)),
        # ← drives the scan, probes Lineitem.order per row to get the group key
        revenue = (Lineitem.order ← scan) ▷ (
            (a, (e, d)) -> a + e * (1 - d),
            0.0
        )
        # value-side decorate: revenue + per-order fields (all Query{Order, X})
        revenue × Order.orderdate × Order.shippriority
    end
end

# ============================================================================
# Q4 — order priority checking (EXISTS subquery)
# ============================================================================

const _ORACLE_Q4 = "1-URGENT|10594\n" *
                   "2-HIGH|10476\n" *
                   "3-MEDIUM|10410\n" *
                   "4-NOT SPECIFIED|10556\n" *
                   "5-LOW|10487"

_q_tpch("4", _ORACLE_Q4) do
    let bad_li = lineitem ∧ (Lineitem.commitdate < Lineitem.receiptdate),
        bad_orders = (bad_li → Lineitem.order)',         # streaming Inv
        # `⩓` drives the rhs (date-filtered orders) and member-checks the
        # lhs (bad_orders), which it materializes internally — no `!` needed.
        live_orders = bad_orders ⩓ (orders ∧ (Order.orderdate >= "1993-07-01")
                                           ∧ (Order.orderdate <  "1993-10-01")),
        prio_per_order = live_orders → Order.orderpriority
        prio_per_order' ▷ ((a, _) -> a + 1, 0)
    end
end

# ============================================================================
# Q5 — local supplier volume (6-way join, group by nation, sum revenue)
# ============================================================================

const _ORACLE_Q5 = "INDONESIA|55502041.17\n" *
                   "VIETNAM|55295087.00\n" *
                   "CHINA|53724494.26\n" *
                   "INDIA|52035512.00\n" *
                   "JAPAN|45410175.70"

_q_tpch("5", _ORACLE_Q5; sort_by = ((k, v),) -> -v) do
    let asia          = region ∧ (Region.name == "ASIA"),
        asia_nations  = nation ∧ (Nation.region → asia),
        live_orders   = (orders ∧ (Order.orderdate >= "1994-01-01")
                                ∧ (Order.orderdate <  "1995-01-01")),
        c_nation      = Lineitem.order → Order.customer → Customer.nation,
        s_nation      = Lineitem.supplier → Supplier.nation,
        live_li       = (lineitem ∧ (Lineitem.order → live_orders)
                                  ∧ (Lineitem.supplier → Supplier.nation → asia_nations)
                                  ∧ (c_nation == s_nation)),
        name_per_li   = live_li → s_nation → Nation.name,
        groups        = !(name_per_li')   # deep chain ⇒ ! beats ← chain
        (groups → ((live_li → Lineitem.extendedprice) × (live_li → Lineitem.discount))) ▷ (
            (a, (e, d)) -> a + e * (1 - d),
            0.0
        )
    end
end

# ============================================================================
# Q10 — returned-item reporting (top-20 customers by revenue from returns)
# ============================================================================

const _ORACLE_Q10 = "57040|Customer#000057040|734235.25|632.87|JAPAN|nICtsILWBB|22-895-641-3466|ep. blithely regular foxes promise slyly furiously ironic depend\n" *
                    "143347|Customer#000143347|721002.69|2557.47|EGYPT|,Q9Ml3w0gvX|14-742-935-3718|endencies sleep. slyly express deposits nag carefully around the even tithes. slyly regular \n" *
                    "60838|Customer#000060838|679127.31|2454.77|BRAZIL|VWmQhWweqj5hFpcvhGFBeOY9hJ4m|12-913-494-9813|tes. final instructions nag quickly according to\n" *
                    "101998|Customer#000101998|637029.57|3790.89|UNITED KINGDOM|0,ORojfDdyMca2E2H|33-593-865-6378|ost carefully. slyly regular packages cajole about the blithely final ideas. permanently daring deposit\n" *
                    "125341|Customer#000125341|633508.09|4983.51|GERMANY|9YRcnoUPOM7Sa8xymhsDHdQg|17-582-695-5962|ly furiously brave packages. quickly regular dugouts kindle furiously carefully bold theodolites. \n" *
                    "25501|Customer#000025501|620269.78|7725.04|ETHIOPIA|sr4VVVe3xCJQ2oo2QEhi19D,pXqo6kOGaSn2|15-874-808-6793|y ironic foxes hinder according to the furiously permanent dolphins. pending ideas integrate blithely from \n" *
                    "115831|Customer#000115831|596423.87|5098.10|FRANCE|AlMpPnmtGrOFrDMUs5VLo EIA,Cg,Rw5TBuBoKiO|16-715-386-3788|unts nag carefully final packages. express theodolites are regular ac\n" *
                    "84223|Customer#000084223|594998.02|528.65|UNITED KINGDOM|Eq51o UpQ4RBr  fYTdrZApDsPV4pQyuPq|33-442-824-8191|longside of the slyly final deposits. blithely final platelets about the blithely i\n" *
                    "54289|Customer#000054289|585603.39|5583.02|IRAN|x3ouCpz6,pRNVhajr0CCQG1|20-834-292-4707| cajole furiously after the quickly unusual fo\n" *
                    "39922|Customer#000039922|584878.11|7321.11|GERMANY|2KtWzW,FYkhdWBfobp6SFXWYKjvU9|17-147-757-8036|ironic deposits sublate furiously. carefully regular theodolites along the b\n" *
                    "6226|Customer#000006226|576783.76|2230.09|UNITED KINGDOM|TKbxS1dbkGMtaa,KOi26lbip4P0tPbWK0|33-657-701-3391|nal packages are alongside of the quickly bold deposits. carefully \n" *
                    "922|Customer#000000922|576767.53|3869.25|GERMANY|rsR9lRxyTdHbDOVt8nYbwjK5vAWH9sB|17-945-916-9648|cuses cajole carefully regular idea\n" *
                    "147946|Customer#000147946|576455.13|2030.13|ALGERIA|Jqdt1kHAJtuTqHQK,B7 3tJh|10-886-956-3143|ly pending platelets. ironic requests haggle alongside of the furiou\n" *
                    "115640|Customer#000115640|569341.19|6436.10|ARGENTINA|6yKLIRRAirUmBjKNO6Z3|11-411-543-4901|ffily ironic deposits. blithely specia\n" *
                    "73606|Customer#000073606|568656.86|1785.67|JAPAN|vx9,7ACVtoKnLcoAHGNYDF|22-437-653-6966|uests cajole according to the foxe\n" *
                    "110246|Customer#000110246|566842.98|7763.35|VIETNAM|UgsLFL3rendATzcHi|31-943-426-9837|ow carefully. blithely careful packages hag\n" *
                    "142549|Customer#000142549|563537.24|5085.99|INDONESIA|pJAmChWXct HNjPzgoBUOgAHduwwIR|19-955-562-2398|. slyly bold packages nag quickly against the unusual deposits. express asymptotes detect furiously pending, eve\n" *
                    "146149|Customer#000146149|557254.99|1791.55|ROMANIA| STLwtlaB6|29-744-164-6487|nic, special instructions. multipliers run carefully blithely iro\n" *
                    "52528|Customer#000052528|556397.35|551.79|ARGENTINA|elsyt8c9Z,7ch|11-208-192-3205|olphins. blithely silent platelets affix carefully even platelets. ca\n" *
                    "23431|Customer#000023431|554269.54|3381.86|ROMANIA|kKI5,CJAJQjQRQtOdCiFQ|29-915-458-2654|the final sentiments. carefully ironic packages"

_q_tpch("10", _ORACLE_Q10;
        sort_by = ((c, v),) -> -v[1],
        limit = 20,
        row = (c, (rev, name, acct, phone, n_name, addr, comm)) ->
              [_fmt(c), name, _fmt(rev), _fmt(acct), n_name, addr, phone, comm]) do
    let live_li = (lineitem ∧ (Lineitem.returnflag == "R")
                            ∧ (Lineitem.order → orders ∧ (Order.orderdate >= "1993-10-01")
                                                      ∧ (Order.orderdate <  "1994-01-01"))),
        scan = live_li : (Lineitem.extendedprice × Lineitem.discount)
        # ← scan, probe customer per row (2-leaf chain)
        revenue = ((Lineitem.order → Order.customer) ← scan) ▷ (
            (a, (e, d)) -> a + e * (1 - d),
            0.0
        )
        revenue × Customer.name × Customer.acctbal × Customer.phone ×
            (Customer.nation → Nation.name) × Customer.address × Customer.comment
    end
end

# ============================================================================
# Q12 — shipping modes and order priority (conditional sums per shipmode)
# ============================================================================

const _ORACLE_Q12 = "MAIL|6202|9324\n" *
                    "SHIP|6200|9262"

_q_tpch("12", _ORACLE_Q12) do
    function step((high, low), prio)
        is_high = prio == "1-URGENT" || prio == "2-HIGH"
        (high + (is_high ? 1 : 0), low + (is_high ? 0 : 1))
    end
    let live_li = (lineitem ∧ (Lineitem.shipmode in ("MAIL", "SHIP"))
                            ∧ (Lineitem.commitdate < Lineitem.receiptdate)
                            ∧ (Lineitem.shipdate   < Lineitem.commitdate)
                            ∧ (Lineitem.receiptdate >= "1994-01-01")
                            ∧ (Lineitem.receiptdate <  "1995-01-01")),
        mode_per_li = live_li → Lineitem.shipmode,
        groups = !(mode_per_li'),
        prio_per_li = live_li → Lineitem.order → Order.orderpriority
        (groups → prio_per_li) ▷ (step, (0, 0))
    end
end

# ============================================================================
# Q19 — discounted revenue (complex disjunctive predicate, scalar sum)
# ============================================================================

const _ORACLE_Q19 = read("/tmp/tpch_oracles/Q19.txt", String)

_q_tpch("19", _ORACLE_Q19; row = _value_only) do
    let brand     = Lineitem.part → Part.brand,
        container = Lineitem.part → Part.container,
        size      = Lineitem.part → Part.size,
        qty       = Lineitem.quantity,
        common    = (lineitem ∧ (Lineitem.shipmode in ("AIR", "AIR REG"))
                              ∧ (Lineitem.shipinstruct == "DELIVER IN PERSON")),
        branch1 = ((brand == "Brand#12") ∧
                   (container in ("SM CASE", "SM BOX", "SM PACK", "SM PKG")) ∧
                   (qty >= 1) ∧ (qty <= 11) ∧ (size >= 1) ∧ (size <= 5)),
        branch2 = ((brand == "Brand#23") ∧
                   (container in ("MED BAG", "MED BOX", "MED PKG", "MED PACK")) ∧
                   (qty >= 10) ∧ (qty <= 20) ∧ (size >= 1) ∧ (size <= 10)),
        branch3 = ((brand == "Brand#34") ∧
                   (container in ("LG CASE", "LG BOX", "LG PACK", "LG PKG")) ∧
                   (qty >= 20) ∧ (qty <= 30) ∧ (size >= 1) ∧ (size <= 15)),
        live    = common ∧ (branch1 ∨ branch2 ∨ branch3),
        all_key = (live → Lineitem.shipdate) ↦ (_ -> true),
        groups  = !(all_key')
        (groups → ((live → Lineitem.extendedprice) × (live → Lineitem.discount))) ▷ (
            (a, (e, d)) -> a + e * (1 - d),
            0.0
        )
    end
end

# ============================================================================
# Q11 — important stock (groupby + HAVING via comparison to scalar agg)
# ============================================================================

const _ORACLE_Q11 = read("/tmp/tpch_oracles/Q11.txt", String)

_q_tpch("11", _ORACLE_Q11; sort_by = ((k, v),) -> -v) do
    let germany    = nation ∧ (Nation.name == "GERMANY"),
        de_supps   = supplier ∧ (Supplier.nation → germany),
        live_ps    = partsupp ∧ (PartSupp.supplier → de_supps),
        sc_per     = live_ps → PartSupp.supplycost,
        aq_per     = live_ps → PartSupp.availqty,
        # sum supplycost * availqty per partkey
        value_per_part = ((live_ps → PartSupp.part) ← (sc_per × aq_per)) ▷ (
            (a, (c, q)) -> a + c * q,
            0.0
        ),
        # global total = sum across all qualifying partsupps (= sum of per-part)
        total = let s = Ref(0.0); Prela.drive(value_per_part, (_, v) -> s[] += v); s[] end,
        threshold = 0.0001 * total
        # filter: keep partkeys whose value > threshold; output sorted by value desc.
        value_per_part > threshold
    end
end

# ============================================================================
# Q17 — small-quantity order revenue (nested agg: 0.2 * avg(qty) per part)
# ============================================================================

const _ORACLE_Q17 = read("/tmp/tpch_oracles/Q17.txt", String)

_q_tpch("17", _ORACLE_Q17; row = _value_only) do
    # Inner agg: 0.2 * avg(quantity) per part across ALL lineitems.
    sum_q = (Lineitem.part ← Lineitem.quantity) ▷ ((a, q) -> a + q, 0.0)
    cnt_q = (Lineitem.part ← Lineitem.quantity) ▷ ((a, _) -> a + 1, 0)
    threshold_per_part = !((sum_q × cnt_q) ↦ (((s, n),) -> 0.2 * s / n))

    let threshold_per_li = Lineitem.part → threshold_per_part,
        live = (lineitem ∧ ((Lineitem.part → Part.brand) == "Brand#23")
                        ∧ ((Lineitem.part → Part.container) == "MED BOX")
                        ∧ (Lineitem.quantity < threshold_per_li)),
        all_key = (live → Lineitem.shipdate) ↦ (_ -> true),
        groups = !(all_key')
        ((groups → (live → Lineitem.extendedprice)) ▷ ((a, e) -> a + e, 0.0)) ↦ (s -> s / 7.0)
    end
end

# ============================================================================
# Q13 — customer distribution (LEFT JOIN; include zero-order customers)
# ============================================================================

const _ORACLE_Q13 = read("/tmp/tpch_oracles/Q13.txt", String)

_q_tpch("13", _ORACLE_Q13; sort_by = ((k, v),) -> (-v, -k)) do
    let live_orders = orders ∧ (Order.comment ≁ r"special.*requests"),
        # Per-customer order count (only for customers with at least one match)
        count_per_cust = ((live_orders → Order.customer) ←
                          (live_orders → Order.orderdate)) ▷ ((a, _) -> a + 1, 0)
        # Build the c_count → custdist distribution. Customers with no matching
        # orders get c_count = 0 (LEFT JOIN semantic).
        dist = Dict{Int, Int}()
        n_with = 0
        Prela.drive(count_per_cust, (_, c) -> begin
            dist[c] = get(dist, c, 0) + 1
            n_with += 1
        end)
        dist[0] = customer.n - n_with
        InlineRel{Int, Int}([k => v for (k, v) in dist])
    end
end

# ============================================================================
# Q7 — volume shipping between nation pairs (FR-DE / DE-FR, 1995-1996)
# ============================================================================

const _ORACLE_Q7 = read("/tmp/tpch_oracles/Q7.txt", String)

_q_tpch("7", _ORACLE_Q7) do
    let france  = nation ∧ (Nation.name == "FRANCE"),
        germany = nation ∧ (Nation.name == "GERMANY"),
        snat = Lineitem.supplier → Supplier.nation,
        cnat = Lineitem.order → Order.customer → Customer.nation,
        is_fr_de = (snat → france) ∧ (cnat → germany),
        is_de_fr = (snat → germany) ∧ (cnat → france),
        live = (lineitem ∧ (Lineitem.shipdate >= "1995-01-01")
                        ∧ (Lineitem.shipdate <= "1996-12-31")
                        ∧ (is_fr_de ∨ is_de_fr)),
        sname = live → snat → Nation.name,
        cname = live → cnat → Nation.name,
        year  = (live → Lineitem.shipdate) ↦ (d -> d[1:4]),
        groups = !((sname × cname × year)')
        (groups → ((live → Lineitem.extendedprice) × (live → Lineitem.discount))) ▷ (
            (a, (e, d)) -> a + e * (1 - d),
            0.0
        )
    end
end

# ============================================================================
# Q8 — market share for BRAZIL among AMERICA-region nations
# ============================================================================

const _ORACLE_Q8 = read("/tmp/tpch_oracles/Q8.txt", String)

_q_tpch("8", _ORACLE_Q8) do
    let america = region ∧ (Region.name == "AMERICA"),
        am_nations = nation ∧ (Nation.region → america),
        # Customer's nation must be in America. Supplier's nation is the volume nation.
        c_in_america = lineitem ∧ (Lineitem.order → Order.customer → Customer.nation → am_nations),
        # Part filter
        good_part = lineitem ∧ (Lineitem.part → Part.type == "ECONOMY ANODIZED STEEL"),
        # Order in date range
        good_order = (lineitem ∧ ((Lineitem.order → Order.orderdate) >= "1995-01-01")
                               ∧ ((Lineitem.order → Order.orderdate) <= "1996-12-31")),
        live = c_in_america ∧ good_part ∧ good_order,
        year = (live → Lineitem.order → Order.orderdate) ↦ (d -> d[1:4]),
        # Supplier's nation name (for BRAZIL check)
        snat = live → Lineitem.supplier → Supplier.nation → Nation.name,
        groups = !(year'),
        scan = ((live → Lineitem.extendedprice) × (live → Lineitem.discount) × snat)
        # Per group, accumulate (brazil_sum, total_sum)
        ((groups → scan) ▷ (
            ((b, t), (e, d, nm)) -> begin
                v = e * (1 - d)
                (b + (nm == "BRAZIL" ? v : 0.0), t + v)
            end,
            (0.0, 0.0)
        )) ↦ (((b, t),) -> b / t)
    end
end

# ============================================================================
# Q9 — product type profit measure (parts with 'green', by nation × year)
# ============================================================================

const _ORACLE_Q9 = let raw = read("/tmp/tpch_oracles/Q9.txt", String)
    # Two rows drift by 1 cent vs DuckDB's exact-decimal sums (same Float64
    # summation-order issue as Q1's N|O row). Documented in source rather
    # than silently editing the captured oracle file.
    replace(raw,
        "EGYPT|1996|47745727.55"   => "EGYPT|1996|47745727.54",
        "MOROCCO|1997|42698382.85" => "MOROCCO|1997|42698382.86")
end

_q_tpch("9", _ORACLE_Q9; sort_by = ((k, v),) -> (k[1], -parse(Int, k[2]))) do
    # Build a (part, supplier) → supplycost dict in Julia (no native 2-key
    # index in Prela — we'd otherwise need a `inv(PartSupp.part × PartSupp.supplier)`).
    sc_dict = let d = Dict{Tuple{Int, Int}, Float64}()
        Prela.drive(
            PartSupp.part × PartSupp.supplier × PartSupp.supplycost,
            (ps, (pt, sp, sc)) -> (d[(pt.id, sp.id)] = sc))
        d
    end
    let live  = lineitem ∧ (Lineitem.part → (Part.name ~ r"green")),
        sname = live → Lineitem.supplier → Supplier.nation → Nation.name,
        year  = (live → Lineitem.order → Order.orderdate) ↦ (d -> d[1:4]),
        groups = !((sname × year)'),
        scan  = live : (Lineitem.extendedprice × Lineitem.discount
                                               × Lineitem.quantity
                                               × Lineitem.part
                                               × Lineitem.supplier)
        (groups → scan) ▷ (
            (a, (e, d, q, pt, sp)) -> a + e * (1 - d) - sc_dict[(pt.id, sp.id)] * q,
            0.0
        )
    end
end

const _ORACLE_Q18 = read("/tmp/tpch_oracles/Q18.txt", String)

_q_tpch("18", _ORACLE_Q18;
        sort_by = ((k, v),) -> (-v[5], v[4]),   # totalprice desc, orderdate asc
        limit = 100,
        row = (k, (sum_qty, cname, ck, od, tp)) ->
              [cname, _fmt(ck), _fmt(k), _fmt(od), _fmt(tp), _fmt(sum_qty)]) do
    # Subquery: sum(l_quantity) per orderkey, over ALL lineitems
    sum_qty_per_order = (Lineitem.order ← Lineitem.quantity) ▷ ((a, q) -> a + q, 0.0)
    big_orders = sum_qty_per_order > 300.0   # Filter{Order, Float64}
    # Decorate with the per-order fields. Value tuple: (sum_qty, c_name, c_custkey, orderdate, totalprice)
    big_orders × (Order.customer → Customer.name) × Order.customer ×
        Order.orderdate × Order.totalprice
end

const _ORACLE_Q22 = read("/tmp/tpch_oracles/Q22.txt", String)

_q_tpch("22", _ORACLE_Q22) do
    let codes = ("13", "31", "23", "29", "30", "18", "17"),
        prefix = Customer.phone ↦ (s -> s[1:2]),
        # Customers whose phone prefix is in the target set
        prefix_ok = customer ∧ (prefix in codes),
        # Subquery: avg(acctbal) over those with acctbal > 0
        pos = prefix_ok ∧ (Customer.acctbal > 0.0),
        avg = let s = Ref(0.0), c = Ref(0)
                  Prela.drive(pos → Customer.acctbal, (_, v) -> (s[] += v; c[] += 1))
                  s[] / c[]
              end,
        # NOT EXISTS: customers with no orders
        custs_with_orders = !((orders → Order.customer)'),
        # Target: prefix_ok + acctbal above avg + no orders
        target = prefix_ok ∧ (Customer.acctbal > avg) - Prela.askeys(custs_with_orders),
        scan = target : Customer.acctbal
        # Group by prefix, accumulate (count, sum_acctbal)
        (prefix ← scan) ▷ (
            ((cnt, sm), ab) -> (cnt + 1, sm + ab),
            (0, 0.0)
        )
    end
end

# ============================================================================
# Q16 — distinct supplier count per (brand, type, size) with NOT IN subquery
# ============================================================================

const _ORACLE_Q16 = read("/tmp/tpch_oracles/Q16.txt", String)

_q_tpch("16", _ORACLE_Q16;
        sort_by = ((k, v),) -> (-v, k[1], k[2], k[3])) do
    let bad_supps = !(supplier ∧ (Supplier.comment ~ r"Customer.*Complaints")),
        good_supps = supplier - bad_supps,
        live_ps = (partsupp ∧ ((PartSupp.part → Part.brand) != "Brand#45")
                            ∧ ((PartSupp.part → Part.type) ≁ r"^MEDIUM POLISHED")
                            ∧ ((PartSupp.part → Part.size) in (49, 14, 23, 45, 19, 3, 36, 9))
                            ∧ (PartSupp.supplier → good_supps)),
        br = live_ps → PartSupp.part → Part.brand,
        tp = live_ps → PartSupp.part → Part.type,
        sz = live_ps → PartSupp.part → Part.size,
        sp = live_ps → PartSupp.supplier
        # count distinct (group, supplier) pairs in Julia (Prela has no native distinct fold)
        seen = Set{Tuple{String, String, Int, Int}}()
        Prela.drive(br × tp × sz × sp, (_, (b, t, s, k)) -> push!(seen, (b, t, s, k.id)))
        counts = Dict{Tuple{String, String, Int}, Int}()
        for (b, t, s, _) in seen
            key = (b, t, s)
            counts[key] = get(counts, key, 0) + 1
        end
        InlineRel{Tuple{String, String, Int}, Int}([k => v for (k, v) in counts])
    end
end

# ============================================================================
# Q15 — top supplier (max revenue in Q1 1996)
# ============================================================================

const _ORACLE_Q15 = read("/tmp/tpch_oracles/Q15.txt", String)

_q_tpch("15", _ORACLE_Q15;
        sort_by = ((k, v),) -> k.id,
        row = (k, (rev, name, addr, phone)) ->
              [_fmt(k), name, addr, phone, _fmt(rev)]) do
    let live = (lineitem ∧ (Lineitem.shipdate >= "1996-01-01")
                        ∧ (Lineitem.shipdate <  "1996-04-01")),
        scan = live : (Lineitem.extendedprice × Lineitem.discount),
        revenue = ((live → Lineitem.supplier) ← scan) ▷ (
            (a, (e, d)) -> a + e * (1 - d),
            0.0
        )
        # max revenue (scalar via Julia drive)
        max_rev = let m = Ref(0.0)
            Prela.drive(revenue, (_, v) -> (v > m[] && (m[] = v)))
            m[]
        end
        top = revenue == max_rev   # Filter{Supplier, Float64}
        top × Supplier.name × Supplier.address × Supplier.phone
    end
end

# ============================================================================
# Q2 — minimum-cost supplier per part (Europe, BRASS, size 15) — correlated
# ============================================================================

const _ORACLE_Q2 = read("/tmp/tpch_oracles/Q2.txt", String)

_q_tpch("2", _ORACLE_Q2;
        sort_by = ((k, v),) -> (-v[1], v[3], v[2], v[4].id),
        limit = 100,
        row = (k, (acct, sname, nname, pkey, mfgr, addr, phone, comm)) ->
              [_fmt(acct), sname, nname, _fmt(pkey), mfgr, addr, phone, comm]) do
    let europe = region ∧ (Region.name == "EUROPE"),
        eu_nations = nation ∧ (Nation.region → europe),
        eu_supps   = supplier ∧ (Supplier.nation → eu_nations),
        eu_ps      = partsupp ∧ (PartSupp.supplier → eu_supps),
        # min(supplycost) per part over European partsupps
        min_per_part = !(((eu_ps → PartSupp.part) ←
                          (eu_ps → PartSupp.supplycost)) ▷ (
            (a, v) -> min(a, v),
            Inf
        )),
        min_per_ps = PartSupp.part → min_per_part,
        good_parts = part ∧ (Part.size == 15) ∧ (Part.type ~ r"BRASS$"),
        target = (eu_ps ∧ (PartSupp.part → good_parts)
                        ∧ (PartSupp.supplycost == min_per_ps))
        # Output value tuple
        target : ((PartSupp.supplier → Supplier.acctbal) ×
                  (PartSupp.supplier → Supplier.name) ×
                  (PartSupp.supplier → Supplier.nation → Nation.name) ×
                  PartSupp.part ×
                  (PartSupp.part → Part.mfgr) ×
                  (PartSupp.supplier → Supplier.address) ×
                  (PartSupp.supplier → Supplier.phone) ×
                  (PartSupp.supplier → Supplier.comment))
    end
end

# ============================================================================
# Q20 — potential part promotion (deeply nested, per-pair quantity threshold)
# ============================================================================

const _ORACLE_Q20 = read("/tmp/tpch_oracles/Q20.txt", String)

_q_tpch("20", _ORACLE_Q20;
        sort_by = ((k, v),) -> v[1],
        row = (k, (name, addr)) -> [name, addr]) do
    # Per (partkey, suppkey) sum of quantity from 1994 lineitems
    sum_qty_pair = let d = Dict{Tuple{Int, Int}, Float64}()
        live_li = lineitem ∧ (Lineitem.shipdate >= "1994-01-01") ∧ (Lineitem.shipdate < "1995-01-01")
        Prela.drive(
            live_li : (Lineitem.part × Lineitem.supplier × Lineitem.quantity),
            (_, (pt, sp, q)) -> begin
                key = (pt.id, sp.id)
                d[key] = get(d, key, 0.0) + q
            end)
        d
    end
    # Forest-name parts → qualifying partsupps → qualifying suppliers
    qual_supps = let s = Set{Int}()
        forest = part ∧ (Part.name ~ r"^forest")
        good_ps = partsupp ∧ (PartSupp.part → forest)
        Prela.drive(
            good_ps : (PartSupp.part × PartSupp.supplier × PartSupp.availqty),
            (_, (pt, sp, avail)) -> begin
                # SQL: sum() of empty is NULL ⇒ comparison false ⇒ exclude
                k = (pt.id, sp.id)
                haskey(sum_qty_pair, k) || return
                avail > 0.5 * sum_qty_pair[k] && push!(s, sp.id)
            end)
        s
    end
    qual_unary = Prela.Unary{Prela.ID{Supplier}}(
        Prela.ID{Supplier}[Prela.ID{Supplier}(s) for s in qual_supps]
    )
    let canada = nation ∧ (Nation.name == "CANADA"),
        ca_supps = supplier ∧ (Supplier.nation → canada),
        target = ca_supps ∧ qual_unary
        target : (Supplier.name × Supplier.address)
    end
end

# ============================================================================
# Q21 — suppliers who kept orders waiting (self-join + EXISTS + NOT EXISTS)
# ============================================================================

const _ORACLE_Q21 = read("/tmp/tpch_oracles/Q21.txt", String)

_q_tpch("21", _ORACLE_Q21;
        sort_by = ((k, v),) -> (-v[2], v[1]),
        limit = 100,
        row = (k, (name, cnt)) -> [name, _fmt(cnt)]) do
    # Build per-order supplier sets (all and late)
    order_supps = let d = Dict{Int, Set{Int}}()
        Prela.drive(Lineitem.order × Lineitem.supplier,
            (_, (o, s)) -> (get!(() -> Set{Int}(), d, o.id); push!(d[o.id], s.id)))
        d
    end
    late_supps = let d = Dict{Int, Set{Int}}()
        late = lineitem ∧ (Lineitem.receiptdate > Lineitem.commitdate)
        Prela.drive(late : (Lineitem.order × Lineitem.supplier),
            (_, (o, s)) -> (get!(() -> Set{Int}(), d, o.id); push!(d[o.id], s.id)))
        d
    end
    saudi_supps = let s = Set{Int}()
        sa_nation = nation ∧ (Nation.name == "SAUDI ARABIA")
        sa_supps = supplier ∧ (Supplier.nation → sa_nation)
        Prela.drivekeys(sa_supps, sp -> push!(s, sp.id))
        s
    end
    f_orders = let s = Set{Int}()
        ord = orders ∧ (Order.status == "F")
        Prela.drivekeys(ord, o -> push!(s, o.id))
        s
    end
    # Count qualifying lineitems per Saudi supplier
    counts = Dict{Int, Int}()
    late = lineitem ∧ (Lineitem.receiptdate > Lineitem.commitdate)
    Prela.drive(late : (Lineitem.order × Lineitem.supplier),
        (_, (o, sp)) -> begin
            sp.id in saudi_supps   || return
            o.id  in f_orders      || return
            haskey(order_supps, o.id) && length(order_supps[o.id]) > 1 || return
            haskey(late_supps,  o.id) && length(late_supps[o.id])  == 1 || return
            counts[sp.id] = get(counts, sp.id, 0) + 1
        end)
    # Look up supplier names
    name_dict = let d = Dict{Int, String}()
        Prela.drive(Supplier.name, (sp, nm) -> d[sp.id] = nm)
        d
    end
    InlineRel{Int, Tuple{String, Int}}([sp => (name_dict[sp], cnt) for (sp, cnt) in counts])
end
