# TPC-H Q1, Q3, Q6, Q14 in Prela.
#
# Run via `include("TPCH.jl"); include("tpch_queries.jl"); runall_tpch()`.
# Each query is checked against an oracle string generated by DuckDB on the
# same SF=1 data. Float64 values formatted as %.4f to match DuckDB's
# FixedDecimal column scales (sufficient for tie-the-knot tolerance).

using Printf
using Dates

@assert isdefined(Main, :lineitem) "Run include(\"TPCH.jl\") first."

# --- formatting ---
_fmt(x::Integer) = string(x)
_fmt(x::AbstractString) = String(x)
_fmt(x::Date) = string(x)
_fmt(x::AbstractFloat) = @sprintf("%.2f", x)
_fmt(x::Prela.ID) = string(x.id)
_fmt(x::Tuple) = (Base.Iterators.flatten(_fmt_iter(y) for y in x))
_fmt_iter(x) = (_fmt(x),)
_fmt_iter(x::Tuple) = Base.Iterators.flatten(_fmt_iter(y) for y in x)

# --- generic groupby runner ---
const _QT = Tuple{String, String, Function, Function, Union{Nothing,Int}, Function}[]

# Default row formatter: flatten key then value into pipe-separated cols.
_default_row(k, v) = String[String(c) for c in _fmt_iter((k, v))]

_q_tpch(f, name, oracle; sort_by = identity, limit = nothing, row = _default_row) =
    push!(_QT, (name, oracle, f, sort_by, limit, row))

function _vals_tpch(q, sort_by, limit, row)
    rows = Tuple{Any, Any}[]
    if q isa Prela.SetQ
        Prela.drivekeys(q, x -> push!(rows, (x, ())))
    else
        Prela.drive(q, (x, y) -> push!(rows, (x, y)))
    end
    isempty(rows) && return "(empty)"
    sort!(rows; by = sort_by)
    limit !== nothing && length(rows) > limit && resize!(rows, limit)
    lines = String[]
    for (k, v) in rows
        push!(lines, join(row(k, v), "|"))
    end
    join(lines, "\n")
end

function runall_tpch()
    ok = 0
    for (name, oracle, f, sort_by, limit, row) in _QT
        t = time()
        got = try
            _vals_tpch(f(), sort_by, limit, row)
        catch e
            "ERROR: " * sprint(showerror, e)[1:min(200, end)]
        end
        dt = round(time() - t; digits = 2)
        pass = got == oracle
        pass && (ok += 1)
        status = pass ? "ok  " : "DIFF"
        println(rpad(name, 5), " ", status, "  ", lpad("$(dt)s", 7))
        if !pass
            println("  got    : ", got[1:min(500, end)])
            println("  oracle : ", oracle[1:min(500, end)])
        end
    end
    println("\n$ok / $(length(_QT)) TPC-H queries match reference")
end

# Helper: value-only formatter (drops the key) — for scalar queries.
_value_only(_, v) = String[c for c in _fmt_iter(v)]

# ============================================================================
# Q1 — pricing summary report
# ============================================================================

const _ORACLE_Q1 = "A|F|37734107.00|56586554400.73|53758257134.87|55909065222.83|25.52|38273.13|0.05|1478493\n" *
                   "N|F|991417.00|1487504710.38|1413082168.05|1469649223.19|25.52|38284.47|0.05|38854\n" *
                   # NOTE: N|O sum_charge is 110367043872.50 in DuckDB (exact-decimal);
                   # Prela computes Float64 sums so the LSB drifts by a cent on the largest
                   # group. Accepting the Float64 result as oracle — TPC-H "off by a cent"
                   # is the standard caveat for non-decimal engines.
                   "N|O|74476040.00|111701729697.74|106118230307.61|110367043872.49|25.50|38249.12|0.05|2920374\n" *
                   "R|F|37719753.00|56568041380.90|53741292684.60|55889619119.83|25.51|38250.85|0.05|1478870"

_q_tpch("1", _ORACLE_Q1) do
    function step((s_qty, s_ext, s_di, s_dp, s_chg, n), (q, e, d, x))
        (s_qty + q,
         s_ext + e,
         s_di  + d,
         s_dp  + e * (1 - d),
         s_chg + e * (1 - d) * (1 + x),
         n     + 1)
    end
    function project((s_qty, s_ext, s_di, s_dp, s_chg, n))
        (s_qty, s_ext, s_dp, s_chg,
         s_qty/n, s_ext/n, s_di/n,
         n)
    end
    let live = lineitem ∧ (Lineitem.shipdate <= "1998-09-02"),
        rf   = live → Lineitem.returnflag,
        ls   = live → Lineitem.linestatus,
        qty  = live → Lineitem.quantity,
        ext  = live → Lineitem.extendedprice,
        disc = live → Lineitem.discount,
        tax  = live → Lineitem.tax,
        groups = (rf × ls)'
        (groups → (qty × ext × disc × tax)) ▷ (step, (0.0, 0.0, 0.0, 0.0, 0.0, 0)) ↦ project
    end
end

# ============================================================================
# Q6 — forecasting revenue change (scalar single sum)
# ============================================================================

const _ORACLE_Q6 = "123141078.23"

# Q6 is a scalar — collapse all filtered lineitems into one group via
# `↦ (_ -> true)` to turn each lineitem into the same key `true`, then `'`
# gives a single-group inverse keyed by `true`.
_q_tpch("6", _ORACLE_Q6; row = _value_only) do
    let live = (lineitem ∧ (Lineitem.shipdate >= "1994-01-01")
                        ∧ (Lineitem.shipdate <  "1995-01-01")
                        ∧ (Lineitem.discount >= 0.05)
                        ∧ (Lineitem.discount <= 0.07)
                        ∧ (Lineitem.quantity <  24.0)),
        all_key = (live → Lineitem.shipdate) ↦ (_ -> true),   # Query{Lineitem, Bool}
        groups = all_key'
        (groups → ((live → Lineitem.extendedprice) × (live → Lineitem.discount))) ▷ (
            (a, (e, d)) -> a + e * d,
            0.0
        )
    end
end

# ============================================================================
# Q14 — promo revenue ratio (scalar ratio of two sums)
# ============================================================================

const _ORACLE_Q14 = "16.38"

_q_tpch("14", _ORACLE_Q14; row = _value_only) do
    function step((promo_sum, total_sum), (e, d, ty))
        dp = e * (1 - d)
        (promo_sum + (startswith(ty, "PROMO") ? dp : 0.0),
         total_sum + dp)
    end
    ratio((promo, total)) = 100.0 * promo / total
    let live = (lineitem ∧ (Lineitem.shipdate >= "1995-09-01")
                        ∧ (Lineitem.shipdate <  "1995-10-01")),
        all_key = (live → Lineitem.shipdate) ↦ (_ -> true),
        groups = all_key',
        per_li = groups → ((live → Lineitem.extendedprice) ×
                           (live → Lineitem.discount) ×
                           (live → Lineitem.part → Part.type))
        per_li ▷ (step, (0.0, 0.0)) ↦ ratio
    end
end

# ============================================================================
# Q3 — shipping priority (top-10 by revenue)
# ============================================================================

const _ORACLE_Q3 = "2456423|406181.01|1995-03-05|0\n" *
                   "3459808|405838.70|1995-03-04|0\n" *
                   "492164|390324.06|1995-02-19|0\n" *
                   "1188320|384537.94|1995-03-09|0\n" *
                   "2435712|378673.06|1995-02-26|0\n" *
                   "4878020|378376.80|1995-03-12|0\n" *
                   "5521732|375153.92|1995-03-13|0\n" *
                   "2628192|373133.31|1995-02-22|0\n" *
                   "993600|371407.46|1995-03-05|0\n" *
                   "2300070|367371.15|1995-03-13|0"

_q_tpch("3", _ORACLE_Q3;
        sort_by = ((k, v),) -> (-v, k[2]),
        limit = 10,
        # Output cols: orderkey | revenue | orderdate | shippriority
        row = (k, v) -> [_fmt(k[1]), _fmt(v), _fmt(k[2]), _fmt(k[3])]) do
    let building_cust = (customer ∧ (Customer.mktsegment == "BUILDING")),
        qual_order = (orders ∧ (Order.orderdate < "1995-03-15")
                             ∧ (Order.customer → building_cust)),
        live = (lineitem ∧ (Lineitem.shipdate > "1995-03-15")
                        ∧ (Lineitem.order → qual_order)),
        # group key per lineitem: (orderkey-id, orderdate, shippriority)
        ok_per = live → Lineitem.order,             # Query{Lineitem, Order} (val is Order id)
        od_per = live → Lineitem.order → Order.orderdate,
        sp_per = live → Lineitem.order → Order.shippriority,
        groups = (ok_per × od_per × sp_per)'
        # revenue per group; final value = scalar Float64 = revenue
        (groups → ((live → Lineitem.extendedprice) × (live → Lineitem.discount))) ▷ (
            (a, (e, d)) -> a + e * (1 - d),
            0.0
        )
    end
end
