[workspace]
resolver = "3"
members = ["harness", "mimic", "ohdsi", "tuva"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
prela = { path = "../../rust" }
harness = { path = "harness" }

[profile.dev]
opt-level = 0
debug = 0
incremental = true

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = 0
